### ISSUE TITLE
Traced Applications Leak Memory with v1.19

### ISSUE THREAD

**Issue by d47id** [DataDog/dd-trace-dotnet#1035]
**Describe the bug**
After upgrading from v1.17 to v1.19, our services started leaking memory. The amount of memory leaked was correlated with request volume into the service. One of our engineers attached a profiler to one of our services (`bff`) and reported the following: "I was able to get profiles of the bff locally. I threw a bunch of load at it, but not enough to see any run away memory usage, so comparing snap shots really didn't give me a lot to look at.  The only hint is that the profiler did call out that there is a DD event handler that gets subscribed to but is never cleaned up.  Not sure if that's the culprit, or if that is just a function of running the service locally, but not sure there's much more I can find"

**To Reproduce**
This should be reproducible in our environment by upgrading to v1.19 again, but no one else has reported it so I haven't tried to create general purpose reproduction steps as I imagine it would be fairly difficult.

**Expected behavior**
Memory usage to not grow permanently with each request handled.

**Screenshots**
![Memory Usage QA](https://user-images.githubusercontent.com/1263060/98999309-92a0ad80-2505-11eb-962f-f79c54c2ed95.png)
Memory usage for bff/webbff in QA before and after downgrading from v1.19 to v1.17

![steps](https://user-images.githubusercontent.com/1263060/98999397-b9f77a80-2505-11eb-8880-ee84fd406b4b.png)
We observed this step pattern in QA and correlated it with runs of our automated test suite, demonstrating that memory usage climbs with requests.

![Memory Usage Prod](https://user-images.githubusercontent.com/1263060/98999334-9fbd9c80-2505-11eb-9af6-d63b05427fca.png)
Memory usage for bff/webbff in production before and after downgrading from v1.19 to v1.17

**Runtime environment (please complete the following information):**
- Instrumentation mode: manual/automatic hybrid. we always match datadog tracer version and nuget package version. tracer installed via deb package.
- Tracer version: 1.17/1.19
- OS: container based on mcr.microsoft.com/dotnet/core/aspnet:3.1.9-buster-slim running in GKE
- CLR: .NET Core 3.1.9

**Comment by kevingosse** [comment]
Hello,

Can you be more precise about what version you're using? Is it 1.19.0, or another 1.19.* version?

Unfortunately it's going to be hard to diagnose with just the information you're giving. It's worth noting that we significantly reduced long-lived and LOH allocations version after version, and this in turn tends to decrease very significantly the rate of gen 2 collections. So there's a possibility that what you're observing is not a memory leak but the gc not reclaiming memory as aggressively.

One way to find out if gen 2 collections are triggered is to use [dotnet-trace](https://github.com/dotnet/diagnostics/blob/master/documentation/dotnet-trace-instructions.md):

```dotnet-trace -p <pid> --profile gc-collect```

The resulting file can be opened with Perfview, or you can join it to the issue so I can inspect it.

Either way, it would help a lot if you could capture dumps (either memory dump with [dotnet-dump](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump) or gc dumps with [dotnet-gcdump](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-gcdump), whichever is more convenient for you), at two separate point in time, after making sure the memory usage has grown significantly.

**Comment by d47id** [comment]
Hi Kevin,

We initially tried 1.19.2 as it contained the fix for this issue: https://github.com/DataDog/dd-trace-dotnet/issues/762

Once we discovered the memory leak, we tried 1.19.5 to see if that corrected the issue. It did not. The behavior was the same.

I know this is anecdotal, but we had containers that normally use ~350MB of RAM using several GB in production, causing pod evictions, poor performance, and general instability until the service was restarted.

Due to the nature of our deployment environment, capturing the data you request is going to be quite labor intensive. I'll attempt to provide what I can as time allows. Considering that we have experienced major bugs in this library with every version since 1.7, I'd appreciate anything you can do here with what I have provided.

**Comment by kevingosse** [comment]
Rest assured that I'll spend as much time as needed on this issue. But we have applications running around the clock in our testing environment with no sign of memory leaks, so if it's confirmed then it means that you're doing something that we're not. Identifying what is going to be tricky.

> I know this is anecdotal, but we had containers that normally use ~350MB of RAM using several GB in production, causing pod evictions, poor performance, and general instability until the service was restarted.

Eviction is indeed a strong argument in favor of a memory leak. The GC is supposed to be aware of the memory limits of the container and force compacting gen 2 collections when it gets near it. 

If it's not too much work, you could try setting the `COMPlus_GCHeapHardLimit` environment variable. It will override the memory limit that the GC is supposed to read from the cgroup. You could try set it for instance to 400MB and see how it impacts the behavior of the application. The value is in hexadecimal:

```
# Sets memory limit to 400MB
export COMPlus_GCHeapHardLimit=19000000
```

> The only hint is that the profiler did call out that there is a DD event handler that gets subscribed to but is never cleaned up.

Do you have more information about this? Any file/report from any tool that you can share would help me.
