### ISSUE TITLE
(Potentially not an issue) Random spans that don't start with parent of MVC WebAPI Request

### ISSUE THREAD

**Issue by killemth** [DataDog/dd-trace-dotnet#1110]
Perhaps this is by design, but we have web requests that aren't correlated to traces or parent spans that start with the ASP.net lifecycle entry point, but rather, have random spans that occur within the request chain.

Should we use the global tracer to start a new parent span for a "web.request" as part of the ASP lifecycle in a message handler SendAsync override?

At one point in time, it was actually picking up traces at an entry of "aspnet_mvc.request" but not anymore.

Just wondering if it would actually be a detriment to always create a span using the global tracer at the proposed lifecycle above?

![image](https://user-images.githubusercontent.com/19578658/103044791-9a616200-4547-11eb-8b9c-7dea2c8d37d7.png)

**Comment by colin-higgins** [comment]
Hi @killemth 
This looks to be a manual trace you added with the nuget package?
Would you be able to verify both the version of the installed MSI and your nuget package for me?

**Comment by killemth** [comment]
> Hi @killemth
> This looks to be a manual trace you added with the nuget package?
> Would you be able to verify both the version of the installed MSI and your nuget package for me?

**Update:** Indeed, following details in [existing instructions](https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-framework/?tab=code#manual-instrumentation) and ensuring the tracer package and the tracer MSI for the agent were running the same version seems to have fixed the issue.

The versions of each component are below;

- DataDog Agent: 7.23.1 _(from agent manager web interface)_
- DataDog Trace Nuget: 1.21.1
- DataDog Tracer for Agent: 1.19.5.0 _(cannot find on agent manager; used version from "C:\Program Files\Datadog\.NET Tracer\net461\Datadog.Trace.dll")_

Yes, the "cache" is a manual trace that I have ingested using the following;

`        public Boolean Contains(String key)
        {
            using (Scope cacheMasterScope =
                Tracer.Instance.StartActive("cache.operation", serviceName: "cache"))
            {
                cacheMasterScope.Span.SetTag("component", "cache");

                using (Scope cacheScope =
                    Tracer.Instance.StartActive("cache.operation.contains"))
                {
                    cacheScope.Span.SetTag("component", "cache");
                    cacheScope.Span.SetTag("cache.operation.name", CacheName);
                    cacheScope.Span.SetTag("cache.operation.key", key);
                    return _cache.Contains(key);
                }
            }
        }`
