### ISSUE TITLE
C# events not getting profiled, Spans are not created

### ISSUE THREAD

**Issue by farisabdulraheem** [DataDog/dd-trace-dotnet#1148]
When profiling a .net Application events are not getting profiled. In the events there is no span or trace id getting created,
I am using datadog  version 1.18 . So what i can i do to profile event methods with datadog.

**Comment by colin-higgins** [comment]
Hi @farisabdulraheem 
Would you mind providing specific detail about what the events are and what you expect to see?

**Comment by jaycdave88** [comment]
Hi @farisabdulraheem ,

We have not heard back from you in a while. So I will close the issue for now.
However, please feel free to reopen if you have additional information. 

Thank you!
