### ISSUE TITLE
about  Datadog.Native.dll

### ISSUE THREAD

**Issue by shijinmts** [DataDog/dd-trace-dotnet#1199]
Can anyone help me to know how and when the Datadog.Native.dll is triggered/called?

**Comment by colin-higgins** [comment]
Hello and thanks for reaching out. 
The Microsoft Profiling documentation would be useful for understanding this: https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/profiling/profiling-overview

In short, we implement the profiling API with that dll, and register ourselves as a profiler with environment variables.
