### ISSUE TITLE
Tracer.Instance.ActiveScope is always null

### ISSUE THREAD

**Issue by okezieokpara** [DataDog/dd-trace-dotnet#1245]
**Describe the bug**
When trying to create custom spans within the current active scope, I noticed that the `ActiveScope`

```csharp
       // From documentation
        // Access the active scope through
        // the global tracer (can return null)
        var scope = Tracer.Instance.ActiveScope;

        if (scope != null)
        {
          // This is always null

            // Add a tag to the span for use in the Datadog web UI
            scope.Span.SetTag("customer.id", customerId.ToString());
        }
```
The major problem happens when I try to create a new active scope.
```csharp
            using (var customScope = Tracer.Instance.StartActive("ussd.listbank"))
                {
                    customScope .Span.SetTag("transaction.id", "banking");
                    var response = await _service.SomeOperation();
                    return Ok(response);
                }
```
This works but totally discards the parent scope associated with this controller which is the `aspnet_core.request`.
I also tried this approach:
```csharp
       using (var scope = Tracer.Instance.ActiveScope ?? Tracer.Instance.StartActive("ussd.listbank"))
            {

                scope.Span.SetTag("transaction.id", "banking");
                var response = await _ussdService.GetBankList();
                return Ok(response);

            }
```
Then I noticed ` Tracer.Instance.ActiveScope` got assigned, but has a different TraceId totally uncorrelated with ` Tracer.Instance.StartActive`. And on the dashboard, I see two different uncorrelated traces with only single spans.

**Expected behavior**
To create additional spans within the default `aspnet_core.request` trace without creating a new uncorrelated traces.

**Screenshots**

**Runtime environment (please complete the following information):**
- Instrumentation mode: [e.g. automatic with msi installer or manual with NuGet package]
- Tracer version: [e.g. 1.24.0]
- OS: [e.g. Windows 10, Docker (Linux) ]
- CLR: [e.g. .NET Framework 4.6.2, .NET Core 3.1]

**Additional context**

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by kevingosse** [comment]
Uncorrelated traces usually mean the version of the nuget doesn't match with the version of the MSI installed on the server. Could you check that?

**Comment by okezieokpara** [comment]
Yes @kevingosse this works

**Comment by ram62836** [comment]
@kevingosse @okezieokpara I'm running into the same issue, my Nuget version (Datadog.Trace 1.28.2) and Linux docker package (datadog-dotnet-apm_1.28.2_amd64.deb) are same. I'm running this container on Kubernetes, am I missing something ?

**Comment by ram62836** [comment]
> @kevingosse @okezieokpara I'm running into the same issue, my Nuget version (Datadog.Trace 1.28.2) and Linux docker package (datadog-dotnet-apm_1.28.2_amd64.deb) are same. I'm running this container on Kubernetes and using .net5, am I missing something ?

Sorry guys, it was my problem, API is storing the state intermediately before performing few operations and loosing the headers.
