### ISSUE TITLE
No Tracking ADO.NET

### ISSUE THREAD

**Issue by SlavkaOnline** [DataDog/dd-trace-dotnet#1249]
**Describe the bug**
We have that code 

```
			await using var connection = new SqlConnection(databaseContext.Database.GetDbConnection().ConnectionString);
			connection.Open();
			const string sql = @"...";

			await using var command = new SqlCommand(sql, connection);

			await using var reader = await command.ExecuteReaderAsync();
			while (reader.Read())
			{
				var item = new Foo()
				{
					item1 = reader.GetString(0),
					item2 = reader.GetInt32(1),
					item3 = reader.GetString(2),
				};
				results.Add(item);
			}
```
and we don't see information about that in the flame graph in datalog. Other parts of code use EF Core 3.1 and all fine 			

**Runtime environment (please complete the following information):**
- Instrumentation mode: the agent in the docker container
- Tracer version: v1.20.0
- OS: bionic
- CLR: 3.1

**Comment by kevingosse** [comment]
Hello, 

Some netstandard calls are not traced by default. Could you please try setting the `DD_TRACE_NETSTANDARD_ENABLED=1` environment variable and see if it fixes your issue?

**Comment by SlavkaOnline** [comment]
I updated the version to 1.20 and it fixed my problem. Thanks.
