### ISSUE TITLE
Missing traces on IIS out-of-process hosting

### ISSUE THREAD

**Issue by andrescolodrero** [DataDog/dd-trace-dotnet#1281]
**Describe the bug**
We are missing traces from some services. 
We believe is due to the type of hosting type on IIS, that ou-of-process applications doesnt send traces to other types of applications.

**To Reproduce**
1. .Net apm tracer, automatic instrumentations.
2. .net 4.x applications running "in process" IIS, tracing well.
3. net 4.x appications "out of process" , not tracing well (only records 1 span )
4. .net core pplications running "in process" IIS, tracing well.
5. .net core "out of process", getting some traces and spans, but service map not working well

**Expected behavior**
All type of applications connected in the service map, there are many independadnt and Datadog doesnt show connectivity between them

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Tracer version: 1.19.4
- OS: windows 2008
- CLR: [multiple, from .net 4.6 to net core 3.1

**Additional context**
I have been for months in a Datadog Support ticket trying to debug this. i just recently update to latest APM.

**Comment by zacharycmontoya** [comment]
Hi @andrescolodrero , can you clarify the exact configuration for the following scenarios:

> 3. net 4.x appications "out of process" , not tracing well (only records 1 span )
> ...
> 5. .net core "out of process", getting some traces and spans, but service map not working well

On number 3, I don't understand how a .NET Framework 4.x application may be hosted out of process so maybe I'm missing some information.

On number 5, .NET Core applications that use "out of process" hosting should generate traces at the request level and should show correct distributed tracing. My first recommendation is to upgrade to the [latest .NET Tracer version](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.25.0) but if there is still some issues with visibility, please let me know what you're expecting to see vs. what you're actually seeing.

**Comment by colin-higgins** [comment]
Hi @andrescolodrero 
Would you provide more detail on how your out of process applications are configured?
> net 4.x appications "out of process" , not tracing well (only records 1 span )

**Comment by Markus-Trachsel-Scout24** [comment]
https://github.com/DataDog/dd-trace-dotnet/issues/2110
We have a similar issue here on later tracer versions.

**Comment by lucaspimentel** [comment]
Closing as stale/abandoned.
