### ISSUE TITLE
Lack of dispose method on Tracer class causes a memory leak in non static usage.

### ISSUE THREAD

**Issue by Hardconkers** [DataDog/dd-trace-dotnet#1321]
For our applications we have multiple scopes of work active within the application. Think queue polling etc. Each one produces a DI Scope that services are injected with, which lives for the lifetime of the task

Therefore, using the tracer class's static instance is insufficient as with every concurrent scope I create, the "active scope" will shift between them and end up having traces bleed into one another.

Therefore, I opted to wrap the tracer in a simple class wrap, as for some reason all the interfaces in this lib are internal, so I could inject a tracer by interface. The result looks like this:

        public OperationTracer(
            IOptions<ServiceConfig> serviceConfig,
            IServiceInformation serviceInformation,
            IScopedPrincipal scopedPrincipal,
            IScopedCorrelation scopedCorrelation)
        {
            apmSettings = serviceConfig.ThrowIfNull(nameof(serviceConfig)).Value.APM;

            this.serviceInformation = serviceInformation.ThrowIfNull(nameof(serviceInformation));
            this.scopedPrincipal = scopedPrincipal.ThrowIfNull(nameof(scopedPrincipal));
            this.scopedCorrelation = scopedCorrelation.ThrowIfNull(nameof(scopedCorrelation));

            var settings = new TracerSettings()
            {
                AgentUri = apmSettings.AgentUrl ?? new Uri("http://localhost:8126", UriKind.Absolute),
                Environment = serviceInformation.EnvironmentName,
                ServiceName = serviceInformation.ServiceName,
                ServiceVersion = $"v{serviceInformation.Version}-{serviceInformation.BuildNumber}",
                LogsInjectionEnabled = true
            };

            Tracer = new Tracer(settings);
        }

        public bool IsTracing => apmSettings.Enabled && Tracer.ActiveScope != null;

        public ulong CurrentTraceId => Tracer.ActiveScope?.Span.TraceId ?? default;

        public ulong CurrentSpanId => Tracer.ActiveScope?.Span.SpanId ?? default;

        public ITraceBuilder Builder => IsTracing
            ? new OperationTraceBuilder(this, Tracer.ActiveScope.Span)
            : (ITraceBuilder)new NoOpTraceBuilder();

        internal Tracer Tracer { get; private set; }

        public ITraceBuilder Create(TraceType type, string resourceName)
        {
            if (apmSettings.Enabled)
            {
                CreateScope(type, resourceName);
            }

            return Builder;
        }

        internal Scope CreateScope(TraceType type, string resourceName)
        {
            var scope = Tracer.StartActive(GetMemberValue(type), startTime: DateTimeOffset.UtcNow);

            scope.Span.Type = GetDataDogType(type);
            scope.Span.ServiceName = serviceInformation.ServiceName;
            scope.Span.ResourceName = resourceName;
            scope.Span.SetTag(Tags.Env, serviceInformation.EnvironmentName);
            scope.Span.SetTag(Tags.Language, CultureInfo.CurrentCulture.EnglishName);

            return scope;
        }
    }

The trouble is, on our environments we seem to be experiencing a memory leak when we enable the tracing function. Even when the code is completely disabled other than the construction of the `Tracer` class from the DataDog lib.

Seems to me that with every construction of the `Tracer` class, it builds an `IAgentWriter`, which then needs to be disposed when the `Tracer` instance is destroyed, and when constructed in large quantities even if the ref no longer is reachable in code (ready to be garbage collected), the instance lives on eating memory. 

My theory is that because you link various ON_APP_EXIT events to the tracer, even when I stop referencing the object, it persists and is not collected because the event handle still exists.

The library is pretty locked down so I think we need to be able to:
- Dispose the `Tracer` class, so that people can opt to not use the static part of the class, which will free up all underlying resources, (currently this only happens on application exit).
- Expose the `IAgentWriter` interface publically, aswell as its implementation so that we can manage this resource ourselves.
- Expose a new public constructor on `Tracer` to take the `IAgentWriter` so that all `Tracer` instances share the same writer, that way it can just become injectable in my case.

System Specs
- Instrumentation mode: manual, with agent on the same box.
- Tracer version: `1.24.0`
- OS: Ubuntu
- CLR: .NET Core 3.1

**Comment by lucaspimentel** [comment]
Thanks for reporting this, @Hardconkers. We will look into the issue and come back with a plan soon.

**Comment by pierotibou** [comment]
Hello @Hardconkers, do you still face this issue? If yes, could you help us understanding more the issue by answering the questions above?
Thanks in advance

**Comment by pierotibou** [comment]
Hello, I'm closing this issue as it's been inactive for a while.
Obviously, don't hesitate to reopen it if need be.

Thank you.
