### ISSUE TITLE
Add support for B3 propagation

### ISSUE THREAD

**Issue by backjo** [DataDog/dd-trace-dotnet#1328]
**Is your feature request related to a problem? Please describe.**
We've decided to adopt OpenTelemetry libraries for instrumentation in our new services. As it stands today, these services cannot propagate trace information to our services instrumented with dd-trace-dotnet, due to a mismatch in propagation format (the OpenTelemetry libraries are configured to use the B3 format, while dd-trace-dotnet uses the Datadog format) 

**Describe the solution you'd like**
The behavior that the Java tracing library has today would be preferable. As a user, I'd like to be able to set a configuration like DD_PROPAGATION_STYLE_INJECT=Datadog,B3 that would let me choose which style(s) I'd like to use for propagation of tracing information.

**Comment by zacharycmontoya** [comment]
Hi @backjo , thank you for contributing! I apologize that we didn't communicate before starting a PR to implement this. We have plans to support propagation of B3 headers and we'd like to accomplish this by porting the following PR from the OpenTelemetry .NET automatic instrumentation repo: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/92 (the two codebases share a significant amount of code). We have not yet scheduled the time to bring this change to dd-trace-dotnet, but we would be happy to provide feedback and review if you want to prepare the changes.

**Comment by backjo** [comment]
@zacharycmontoya no worries - that's great to hear! Let me go down that path - we're moving towards OpenTelemetry ourselves for our APM/Tracing instrumentation.
