### ISSUE TITLE
APM - Add correlation to gRPC services on Kubernetes 

### ISSUE THREAD

**Issue by GiuseppePatane** [DataDog/dd-trace-dotnet#1474]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : [e.g. `grpc-dotnet`]

**Problem**
gRPC services are correctly detected by the APM but are not correlated with the services calling them, making it difficult to find any errors or slowdowns
 

- dd-trace-dotnet 1.26 (configured on docker)

- Kubernetes agent : datadog/agent:7

**Describe the solution you'd like**
automatic correlation between the gRPC service and the caller.

**Additional context**
it would seem that this functionality has already been implemented in the [open tracing C# client:](https://github.com/opentracing-contrib/csharp-grpc/blob/master/getting_started/README.md)

**Comment by tu-artem** [comment]
We are seeing a similar issue (no automatic correlation) with C# gPRC client calling server in Python. 
Is there any workaround (e.g. manually adding traces) to solve this?

**Comment by GiuseppePatane** [comment]
> We are seeing a similar issue (no automatic correlation) with C# gPRC client calling server in Python. Is there any workaround (e.g. manually adding traces) to solve this?

updating the dd-trace-dotnet to the last version has solved the issue for me. Now i see the correlation to the gRPC services

**Comment by pierotibou** [comment]
Hello @GiuseppePatane, we've just released the support of gRPC this week.
You can find more info on libraries and versions supported in our [public documentation](https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/dotnet-core#integrations).

Thanks for your patience.
