### ISSUE TITLE
Exception "System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0" when published with "-p:PublishTrimmed=true"

### ISSUE THREAD

**Issue by ismailmmd** [DataDog/dd-trace-dotnet#1478]
When a dotnet is published with `-p:PublishTrimmed=true` parameter the App fails to start with below error,
```sh
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(IHostBuilder builder, Action`1 configure)
   at API.Program.CreateHostBuilder(String[] args) in /src/API/Program.cs:line 17
   at API.Program.Main(String[] args) in /src/API/Program.cs:line 13
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker run --rm -it  -p 5000:5000/tcp api:latest" terminated with exit code: 1.
```

-   Project setup :
    .Net 5 console app with [dd-trace-dotnet library Version 1.26.3](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.26.3). 

1. Run the app using publish command and flag `-p:PublishTrimmed=false`
    `dotnet publish "Exchange.Ingestion.API.csproj" -c Release -o /app/publish -p:PublishTrimmed=false`
    This will run the app without any issues.
2. Run the app using publish command and flag `-p:PublishTrimmed=true`
    `dotnet publish "Exchange.Ingestion.API.csproj" -c Release -o /app/publish -p:PublishTrimmed=true`
    App will fail to start with error,
```sh
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(IHostBuilder builder, Action`1 configure)
   at API.Program.CreateHostBuilder(String[] args) in /src/API/Program.cs:line 17
   at API.Program.Main(String[] args) in /src/API/Program.cs:line 13
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker run --rm -it  -p 5000:5000/tcp api:latest" terminated with exit code: 1.
```
**Expected behavior**
App should start to run and trace logs.

**Runtime environment:**
- Instrumentation mode: auto
- Tracer version: [1.26.3](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.26.3)
- OS: Containarised with `mcr.microsoft.com/dotnet/sdk:5.0.102-1-alpine3.12-amd64`
- CLR: .NET CORE 5

**Additional context**
- PublishTrimmed Docs - [https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish)
- Closed Issue - [https://github.com/DataDog/dd-trace-dotnet/issues/618](https://github.com/DataDog/dd-trace-dotnet/issues/618)

**Comment by andrewlock** [comment]
Thanks for raising this issue. You're experiencing the problem because when using trimming, the CLI strips out assemblies that are required by the Datadog Tracer. Unfortunately, as the Datadog tracer uses different assemblies to those used by your application, there's no way for the CLI to know which assemblies/methods are safe to remove, and which are required. This leads to the exception you experience at runtime. 

Currently, tracing apps built with app trimming enabled is not supported.

**Comment by andrewlock** [comment]
Hi, if you're still interested in using trimmed apps, we have added provisional support with the [Datadog.Trace.Trimming](https://www.nuget.org/packages/Datadog.Trace.Trimming/2.37.0-prerelease) NuGet package in [the v2.32.0 release](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.32.0) Add [this package](https://www.nuget.org/packages/Datadog.Trace.Trimming/2.37.0-prerelease) to your app (make sure you use the same version as the existing tracer version you're using). 

This is just beta support at the moment, so please let us know if you run into any issues trying it out! I'll close this issue for now, but feel free to open a new one if you have any problems. Thanks!
