### ISSUE TITLE
Instrumentation not working for Microsoft.Data.SqlClient.SqlCommand inside a transaction

### ISSUE THREAD

**Issue by jacob-m-nielsen** [DataDog/dd-trace-dotnet#1552]
**Describe the bug**
According to https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.21.0 support was added for automatic instrumentation of `Microsoft.Data.SqlClient.SqlCommand`.

This works as expected as long as the `SqlCommand` is not inside a `Microsoft.Data.SqlClient.SqlTransaction`. Any `SqlCommand`'s in a `SqlTransaction` do not have traces.

**To Reproduce**
1. Create a .NET 5 Console App
2. Add the `Microsoft.Data.SqlClient` and `Datadog.Trace` NuGet packages
3. Manuall start a trace and execute a query against SQL Server e.g.:

```csharp
using (var traceScope = Tracer.Instance.StartActive("some.operation"))
{
	await using var connection = new SqlConnection(_configuration.Value.SqlServerConnectionString);
	connection.Open();
	await using SqlTransaction transaction = connection.BeginTransaction();

	await using var command = new SqlCommand(@"..", connection, transaction);

	await using (SqlDataReader reader = await command.ExecuteReaderAsync())
	{
		if (reader.Read())
		{

		}
	}

	transaction.Commit();
}
```

**Expected behavior**
The query is expected to be visible in the corresponding APM trace

**Runtime environment (please complete the following information):**
- Instrumentation mode: manual
- Tracer version: 1.27.1
- OS: ASP.NET docker image on GCP (mcr.microsoft.com/dotnet/aspnet:5.0)
- CLR: .NET 5

**Additional context**
Oskar Rittsél asked me to create this ticket.

**Comment by kevingosse** [comment]
Hello,

I've tried running your code but it works fine for me, with and without transaction: https://gist.github.com/kevingosse/7cdfbdf242cfd776225448f11b68eb10

What version of `Microsoft.Data.SqlClient` are you using? Please keep in mind that we don't support 3.0.0 yet.

**Comment by jacob-m-nielsen** [comment]
We are indeed using v3.0.0, so that clarifies the problem. Do you have an idea on when 3.0.0 will be supported?

**Comment by kevingosse** [comment]
I'll try to squeeze that in the next release or the one after, so expect it in the coming weeks.

**Comment by kevingosse** [comment]
Version 1.28.0 has been released, and includes support of Microsoft.Data.SqlClient 3.*.
