### ISSUE TITLE
Support for DD_TRACE_DB_CLIENT_SPLIT_BY_INSTANCE

### ISSUE THREAD

**Issue by moonheart** [DataDog/dd-trace-dotnet#1571]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
No

**Is your feature request related to a problem? Please describe.**
The service name of spans for db operations is not clear enough.
For examples, the service name of spans for mysql query is `MyService-mysql`, which does not show the database name. And if I have multiple services that query same database, then service names are `MyService1-mysql`, `MyService2-mysql` etc.

**Describe the solution you'd like**
The service name of spans for db operations should be database names, like what we have done in `dd-trace-java`.

**Describe alternatives you've considered**
As an alternative, we can use database host name or ip address as service name of spans.

**Additional context**
https://docs.datadoghq.com/tracing/setup_overview/setup/java?tab=containers#ddtracedbclientsplit-by-instance

**Comment by andrewlock** [comment]
Thanks, we're away this is a limitation at the moment, and we're planning a long term solution to the problem of service naming across Datadog. We'll be sure to let you know when we have solid plans.

**Comment by moonheart** [comment]
@andrewlock Thanks for your reply. I'm looking forward to this feature ❤️

**Comment by lucaspimentel** [comment]
I'm closing this ticket since there are no plans to add this feature to the .NET Tracer.

**Comment by colszewski** [comment]
> Thanks, we're aware this is a limitation at the moment, and we're planning a long term solution to the problem of service naming across Datadog. We'll be sure to let you know when we have solid plans.

Has there been any progress on the long term solution to this problem? We are a subscriber with a number of services that connect to multiple databases and the functionality described in this pull request would be very beneficial to us.

**Comment by awaldow** [comment]
> > Thanks, we're aware this is a limitation at the moment, and we're planning a long term solution to the problem of service naming across Datadog. We'll be sure to let you know when we have solid plans.
> 
> Has there been any progress on the long term solution to this problem? We are a subscriber with a number of services that connect to multiple databases and the functionality described in this pull request would be very beneficial to us.

Would also love to hear about this, not uncommon for services to have multiple dbs to talk to, http clients to other services etc. and being able to name them differently to get the service map to be more representative of what that service is actually talking to would make my team leads very happy
