### ISSUE TITLE
Auto Instrumentation for Elasticsearch.Net v7

### ISSUE THREAD

**Issue by bryan-welter-orange** [DataDog/dd-trace-dotnet#1584]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : `Elasticsearch.Net`
- Library type: `.net core`
- Library version: `3.1`

**Is your feature request related to a problem? Please describe.**
After upgrading from Elastic 6 to Elastic 7 we lost our auto instrumentation for elasticsearch.

**Describe the solution you'd like**
Add auto instrumentation for `Elasticsearch.Net v7`.

**Comment by lippinio** [comment]
I think this is rather a bug than a new feature. As described in this sample https://github.com/DataDog/dd-trace-dotnet/tree/69412f253887ed528a570d47651f989bd236cada/test/test-applications/integrations/Samples.Elasticsearch
and in the documentation here https://docs.datadoghq.com/tracing/setup_overview/compatibility_requirements/dotnet-core/#integrations

As written in the release Notes from Elasticsearch-net client the diagnositcsource and setting was changed. Looks like there was a breaking change and so instrumentation is broken:
https://github.com/elastic/elasticsearch-net/releases/tag/7.0.0 (look for observablity and diagnosticsource)

It would be very nice to have this feature fixed and be able to instrument elastic search queries again.

**Comment by andrewlock** [comment]
@bryan-welter-orange, @lippinio  we have just [released version 1.28.8](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.28.8) of the tracer, which adds support for Elasticsearch.Net version 7. Thanks for flagging this!
