### ISSUE TITLE
No runtime metrics in .net core service?

### ISSUE THREAD

**Issue by vrecluse** [DataDog/dd-trace-dotnet#1712]
**Describe the bug**
I configured datadog agent with dotnet runtime metrics integration, and launch my app with app settings:
```json
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "Sazabi.World.Silo": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "DOTNET_ENVIRONMENT": "Development",
        "CORECLR_ENABLE_PROFILING": "1",
        "DD_RUNTIME_METRICS_ENABLED": "true",
        "CORECLR_PROFILER": "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
      }
    }
  }
}

```
It collects data in dotnet runtime metrics dashboard, but no data is showed in service page.
And in the dashboard, metrics are not showed sometimes, unless go back to dashboard list and click the dashboard again.

**Screenshots**
![image](https://user-images.githubusercontent.com/4232511/131253503-5d09e6dc-8e5b-408a-a9f4-85c60fceb54c.png)
![image](https://user-images.githubusercontent.com/4232511/131253541-6f835cdb-de2d-46ab-8021-6d0ae6a65a7e.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: [e.g. automatic with msi installer or manual with NuGet package]
- Tracer version: 1.28.2
- OS: Windows 10 Pro
- CLR: .NET 5.0

**Comment by vrecluse** [comment]
Sometimes the dashboard is empty:
![image](https://user-images.githubusercontent.com/4232511/131253648-5ea91ed3-4c10-48c5-86f7-c352d0acbb29.png)

**Comment by lucaspimentel** [comment]
@vrecluse, please create a support ticket by contacting support@datadoghq.com and referencing this GitHub issue. Thank you!

**Comment by lucaspimentel** [comment]
I hope our support team was able to help you get runtime metrics running. Closing this ticket as stale.
