### ISSUE TITLE
Datadog Tracing Integrations With GraphQl dotnet Version 3 + 

### ISSUE THREAD

**Issue by pmarshallandrew** [DataDog/dd-trace-dotnet#1721]
Hey, I was wondering if you could shed some light on an urgent matter : 

Since upgrading our ASP.NET core (.Net core 3.1)  GRAPHQL dotnet (https://graphql-dotnet.github.io/docs) API services from version 2.4 to version 3.3.2 , we notice that our datadog APM tracing has stopped working and we can no longer see GraphQL related data anymore, like the query etc when viewing within the APM dashboard. We can still see some span info to do with hitting caches etc  and the original HTTP request ,but no spans detailing graphql related data.

This was working as expected prior to upgrading . We are referencing the  Datadog.Tracing v 1.23.0 nuget package within the project as well as pulling in its corresponding apm lib into the container (https://github.com/DataDog/dd-trace-dotnet/releases/download/v1.23.0/datadog-dotnet-apm_1.23.0_amd64.deb). Ive tried updating to  the latest version of the tracing library also to no avail.  

Looking at the tracing code it seems the tracing interceptor code only deals with version 2.* of graphql  dotnet and hasnt been updated in a while 
https://github.com/DataDog/dd-trace-dotnet/blob/master/src/Datadog.Trace/ClrProfiler/Integrations/GraphQLIntegration.cs#L30

Please could you shed some light as to whether this will be fixed/addressed in the near future or failing that , could you give me some info on best patterns and practices to be able to write my own custom integrations to handle this within this graphql framework please.

Kind regards,

Patrick

**Comment by pmarshallandrew** [comment]
any update on this at all please?

**Comment by andrewlock** [comment]
Hi @pmarshallandrew, sorry for the delay, and thanks for flagging this. We're actively working on supporting version 3.x currently. We'll let you know once it's added!

**Comment by andrewlock** [comment]
@pmarshallandrew we have just [released version 1.28.8](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.28.8) of the tracer, which adds support for GraphQL .NET versions 3 and 4. Thanks for flagging this!
