### ISSUE TITLE
Set global tags

### ISSUE THREAD

**Issue by willyyang** [DataDog/dd-trace-dotnet#189]
Is there any way to set global tags for a trace as available in the Node `dd-trace-js` and Go `dd-trace-go` libraries?

**Comment by lucaspimentel** [comment]
There's no way to do this currently. We are adding a configuration system soon that can use `web.config`, environment variables, and possibly other sources.

**Comment by felipeleusin** [comment]
Awesome. I'll keep track on this issue then. Thanks!

**Comment by colin-higgins** [comment]
We've added support for global tags here: https://github.com/DataDog/dd-trace-dotnet/pull/533
We will update this issue again once it's released.

**Comment by bobuva** [comment]
Global tags support is added and will be released in version `1.9.0`
