### ISSUE TITLE
Unable to configure the .netcore tracer library

### ISSUE THREAD

**Issue by davenewza** [DataDog/dd-trace-dotnet#1986]
**Describe the bug**
I am configuring APM tracing in a .NET Core 5 API service.  We have managed to successfully get APM traces consumed by Datadog, but it seems the `Datadog.Tracing` library is detached from this.  We also want to use the tracing library to add custom tags to APM spans.

There are two reasons I believe the tracing library is "detached":
 1. The settings (service name, environment and version) initialised with the tracer aren't those sent to Datadog (rather they appear to be taking on the kubernete's host tags)
 2. `Tracer.Instance.ActiveScope` is null.

**Dockerfile excerpt:**
```
RUN TRACER_VERSION=$(curl -s \https://api.github.com/repos/DataDog/dd-trace-dotnet/releases/latest | grep tag_name | cut -d '"' -f 4 | cut -c2-) \
    && curl -Lo /tmp/datadog-dotnet-apm.deb https://github.com/DataDog/dd-trace-dotnet/releases/download/v${TRACER_VERSION}/datadog-dotnet-apm_${TRACER_VERSION}_amd64.deb
...
COPY --from=builder /tmp/datadog-dotnet-apm.deb /tmp/datadog-dotnet-apm.deb
RUN mkdir -p /opt/datadog \
    && mkdir -p /var/log/datadog \
    && dpkg -i /tmp/datadog-dotnet-apm.deb \
    && rm /tmp/datadog-dotnet-apm.deb
ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
ENV CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
ENV DD_DOTNET_TRACER_HOME=/opt/datadog
ENV DD_INTEGRATIONS=/opt/datadog/integrations.json
ENV DD_TRACE_ROUTE_TEMPLATE_RESOURCE_NAMES_ENABLED=true
```

**.NET Tracer configuration (in Startup.Configure):**
```
var settings = TracerSettings.FromDefaultSources();
settings.TraceEnabled = true;
settings.Environment = environment; // Not represented in Datadog
settings.ServiceName = serviceName; // Not represented in Datadog
settings.ServiceVersion = serviceVersion; // Not represented in Datadog
settings.RuntimeMetricsEnabled = true; // Not represented in Datadog

var tracer = new Tracer(settings);
Tracer.Instance = tracer;
```

**Custom span tagging:**
```
var scope = Tracer.Instance.ActiveScope; // This is null!
scope.Span.SetTag("tenantId", tenantId);
```

**Expected behavior**
 - Our Datadog APM service should be configured with the environment, service name and version configured in the .NET tracing library.
 - `Tracer.Instance.ActiveScope` should expose the Datadog tracing instance (and not be null!)

**Runtime environment (please complete the following information):**
- Datadog container agent (Kubernetes): `gcr.io/datadoghq/agent:latest`
- `Datadog.Trace` 1.29.  I have also tried with `Datadog.Monitoring.Distribution` 12.28.8-beta01 (I don't understand which is correct)
- Docker linux base `mcr.microsoft.com/dotnet/aspnet:5.0`
- .NET 5.0

**Comment by lucaspimentel** [comment]
Hi, @davenewza. Are using different versions of the installer (for automatic instrumentation) and the NuGet package (for custom instrumentation/tagging)? There is a known issue on .NET Core where the tracers get "disconnected" like your describe if the NuGet version is _older_ than the installer version. This issue is something we are actively working on and hope to resolve soon.

In the meantime, we recommend keep both versions in sync as much as possible. Updating the NuGet first so it's newer than the installer _may_ work, but YMMV.

**Comment by davenewza** [comment]
@lucaspimentel Thanks - let me try that.  Which NuGet package should I be using?  The [Datadog documentation](https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-framework/?tab=nuget) tells me to use `Datadog.Monitoring.Distribution` (which is only in prerelease) but [GitHub](https://github.com/DataDog/dd-trace-dotnet) tells me to use `Datadog.Trace`.

**Comment by andrewlock** [comment]
Hi @davenewza, 

* `Datadog.Trace` is only used for manual instrumentation, or to configure the tracer in code
* `Datadog.Monitoring.Distribution` is essentially a NuGet alternative to the _installer_, which includes everything you need for automatic instrumentation. This NuGet package also transitively references `Datadog.Trace`.

So if, as in your case, you want both automatic instrumentation _and_ manual instrumentation, you will need to _either_

* Add the `Datadog.Monitoring.Distribution` NuGet _only_, and configure the environment variables [as described in the documentation](https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-core?tab=nuget#enable-the-tracer-for-your-service).
* Add the `Datadog.Trace` NuGet _and_ [install the tracer package](https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-core?tab=linux#install-the-tracer). As described in the previous comment, it is important you keep the version of the installer and the NuGet package in sync. 

Both of these approaches work the same, but if you use the `Datadog.Monitoring.Distribution`, NuGet, then you don't have to worry about keeping things in sync; there's only one version number to worry about 🙂

Whichever approach you use, be sure to run the _createLogPath.sh_ script (or manually create the logging directory) in your Docker container, [as described in the documentation.](https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-core?tab=nuget#install-the-tracer).

**Comment by davenewza** [comment]
Thanks for the very informative explanation.  The official Datadog documentation could use your help.

Option 1 (using just the `Datadog.Monitoring.Distribution` package) sounds like the more ideal approach and I'm glad there is a push for this.

However, **I now have Option 2 working correctly** (tracer installed + `Datadog.Trace` package) with both set to v1.29.0.

**Comment by lucaspimentel** [comment]
> I now have Option 2 working correctly

Glad to see this is resolved! Thanks @andrewlock for jumping in.

**Comment by mrtristan** [comment]
@andrewlock can you comment on the mentioned note about `Datadog.Monitoring.Distribution` only being prerelease / beta? is this thing good to use?

**Comment by andrewlock** [comment]
>@andrewlock can you comment on the mentioned note about Datadog.Monitoring.Distribution only being prerelease / beta? is this thing good to use?

In terms of the contents, the NuGet is solid, and we have no problems recommending it for non-IIS workloads. The package contains a reference to the `Datadog.Trace` package and the same dlls that are [otherwise available from the releases page](https://github.com/DataDog/dd-trace-dotnet/releases). The main reason this package is currently still in beta is because we're not entirely sure about the naming.
