### ISSUE TITLE
Profiler uses environment variables instead of current module for pinvoke generation

### ISSUE THREAD

**Issue by wiktork** [DataDog/dd-trace-dotnet#2042]
When emitting pinvokes, [GetCLRProfilerPath](https://github.com/DataDog/dd-trace-dotnet/blob/d009bf0e90018a34b5322a34abdba79228979cd9/tracer/src/Datadog.Trace.ClrProfiler.Native/cor_profiler.cpp#L1432) uses `CORECLR_PROFILER_PATH` to figure out the location of the native profiler module. While this works in most cases, it can cause issues in some scenarios:
- [Raw Profiler Hook scenarios](https://github.com/microsoft/CLRInstrumentationEngine/blob/master/docs/getting_started.md#how-do-i-use-the-raw-profiler-hook) will not work, since the environment variable is set to the CLR Instrumentation Engine.
- It's possible for the process to change its environment variables, changing the behavior of `GetCLRProfilerPath`.

On Windows this could be done using `GetModuleHandleEx/GetModuleFileName`.
On Linux this could be done using `dladdr`.

**Comment by tonyredondo** [comment]
PR with the fix has been merged and it's expected to be out as part of the 2.0 release.
Closing this issue.
