### ISSUE TITLE
Memory consumption issue on manual instrumentation (.NET Core 3.1)

### ISSUE THREAD

**Issue by isaiasccruz** [DataDog/dd-trace-dotnet#2083]
**Describe the bug**
After starting to instrument manually, a few processes within the application with the Datadog.Trace lib (on v1.28.0, v1.28.8 and v1.30.0) and the agent on (1.28.0 and 1.29.0),  I've been facing an exponentially increase in memory consumption which is causing system.outofmemoryexception because the pod is exceeding the memory cap set in helm.

**Runtime environment:**
- Instrumentation mode: [manual with NuGet package]
- Tracer version: [v1.28.0, v1.28.8 and v1.30.0]
- OS: [GNU/Linux alpine]
- CLR: .NET Core 3.1

**Screenshots**

Production (without instrumentation) 
![image](https://user-images.githubusercontent.com/72766059/143131453-2cc78879-fb0e-4d12-85ae-163e00f63855.png)

Development (with instrumentation)
![image](https://user-images.githubusercontent.com/72766059/143131871-f4ff515c-037f-4b02-88c4-e10adcbf47dd.png)

**To Reproduce**
A class was created to instantiate the tracers on demand for further span creation like:

```
public class TracerRepository : ITracerRepository
    {
        public TracerRepository()
        {

        }

        public Tracer CriaTracerDatadog(string spanName)
        {
            TracerSettings settings = TracerSettings.FromDefaultSources();
            settings.TraceEnabled = true;
            settings.Environment = Configuracoes.ConfigJob.Ambiente;
            settings.ServiceName = Configuracoes.ConfigJob.NomeApp;
            settings.RuntimeMetricsEnabled = true;
            settings.AnalyticsEnabled = true;
            settings.KafkaCreateConsumerScopeEnabled = true;
            settings.PartialFlushEnabled = true;

            Tracer tracer = new Tracer(settings);
            tracer.StartActive(spanName);

            return tracer;
        }

        public async Task FlushTracerAtivo(Tracer tracer)
        {            
            await tracer.ForceFlushAsync();
        }
    }
```
And then I'm instrumenting on each call to the method, like this example for a kafka consumer:

```
public class KafkaRepository : IKafkaRepository
    {

        private readonly IEmailRepository _emailRepository;
        private readonly IUtilRepository _utilRepository;
        private readonly ITracerRepository _tracerRepository;
        Tracer dgTracer;
        Scope dgScope;        

        public KafkaRepository(IEmailRepository emailRepository, IUtilRepository utilRepository, ITracerRepository tracerRepository)
        {
            _emailRepository = emailRepository;
            _utilRepository = utilRepository;
            _tracerRepository = tracerRepository;
        }
        
        public ConsumeResult<string, VeiculoDTO> Consume(IConsumer<string, VeiculoDTO> consumer, int timeout)
        {
            ConsumeResult<string, VeiculoDTO> cr = null;

            dgTracer = _tracerRepository.CriaTracerDatadog(_utilRepository.EnumToDescriptionString(TraceTypes.aspnetcore_request));
            dgScope = dgTracer.ActiveScope;
            dgScope.Span.Type = "web";
            dgScope.Span.ResourceName = "ConsumeVeiculoLocaliza";

            try
            {
                cr = consumer.Consume(timeout);
            }
            catch (Exception ex)
            {
                dgScope.Span.Error = true;
                dgScope.Span.SetException(ex);
                dgScope.Span.Finish(DateTimeOffset.Now);
                dgScope.Close();
                dgScope.Dispose();

                Log.Error($"{DateTime.Now:HH:mm:ss} - Erro no Processamento dos offsets da thread LOCALIZA. Ex: {ex.Message}, Inner: {ex.InnerException?.Message}, Stack: {ex.StackTrace}");
            }

            dgScope.Span.Finish(DateTimeOffset.Now);
            dgScope.Dispose();

            return cr;
        }        
    }
```

I've tried several ways to optimize this usage and this is what i could accomplish so far. As for the results on datadog service trackers: it's working and showing the tracers as expected with the caveat of the growing memory consumption

Can you guys check if i'm doing this correctly? and show me how can i better this usage?

Thanks!

**Comment by kevingosse** [comment]
If I understand your code, you're creating a new instance of `Tracer` every time you call `Consume`. The tracer is designed to be used as a singleton, use `Tracer.Instance` instead and this should fix your memory leak.

**Comment by isaiasccruz** [comment]
@kevingosse In my first version of the code I was using Tracer.Instance, but what happened was that the first run of the app would register a span as expected, but every other call was just ignored, and no span would appear on Datadog. The app is a job on which it creates 2 main threads to consume 2 different topics of a same domain and then handle the offsets with a post on a rest API. 

And then I suspected that it was the usage of the static class that was hanging or concurring with each other.

I'll try to find a workaround to this usage and come back to you. Thanks!

**Comment by isaiasccruz** [comment]
So, I've re-created wrapping the desired code under using() with the `Tracer.Instance` and it is now persisting data as expected and the memory consumption is ok.

Thanks!
