### ISSUE TITLE
Add support for .NET 6

### ISSUE THREAD

**Issue by Kavignon** [DataDog/dd-trace-dotnet#2101]
I'd like to know when support for tracing in .NET 6 would be added to APM in DataDog.

**Comment by lucaspimentel** [comment]
Hello Kevin. We're adding support for .NET 6 in .NET Tracer 2.0, which should be out in a few weeks. The PR that added support was #1885.

**Comment by vbougay** [comment]
It should be really expedited. The .NET 6 is out for almost a month and RCs were available for months already. This is blocking migration to .NET 6 on our end since it breaks observability
