### ISSUE TITLE
Allow setting sampling priority for spans

### ISSUE THREAD

**Issue by vadimi** [DataDog/dd-trace-dotnet#214]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
I'd like both `Datadog.Trace` and `Datadog.Trace.OpenTracing` packages to support this feature.

**Is your feature request related to a problem? Please describe.**
I'd like to be able to pass sampling priority for some spans like described here:

https://docs.datadoghq.com/tracing/getting_further/trace_sampling_and_storage/#priority-sampling-for-distributed-tracing

**Describe the solution you'd like**
I think `span.SetTag(...)` override that parses `sampling.priority` key and `int` value would be enough.
Also for distributed tracing it would be necessary to update Propagators in Datadog.Trace to pass it through `x-datadog-sampling-priority` header and `HttpHeadersCodec` in Datadog.Trace.OpenTracing package.

**Comment by vadimi** [comment]
ok, thanks for the update.

**Comment by lucaspimentel** [comment]
@vadimi: release 1.0 allows users to set a trace's sampling priority. The docs will be updated soon, but here's some sample code:
```csharp
span.SetTag(Tags.ForceKeep, "true");
```

The older tag supported in other Tracers are also supported, but `SetTag()` only accepts string values right now:
```csharp
var value = (int)SamplingPriority.UserKeep;
span.SetTag(Tags.SamplingPriority, value.ToString()); // "2"
```

In a future release we will change tags to support different value types aside from strings.

**Comment by vadimi** [comment]
thanks @lucaspimentel, I appreciate it
