### ISSUE TITLE
http-client instrumentation broken in .net6 

### ISSUE THREAD

**Issue by lippinio** [DataDog/dd-trace-dotnet#2140]
**Describe the bug**
After an update to .net6 automatic http-client instrumentation is broken. As we would like to use new features and receive security patches it is critical for us and any others that .net updates can be made anytime.
Clone Repo https://github.com/lippinio/broken-http-tracer-net6. The example app is an adapted version of your sample from this [repo](https://github.com/DataDog/dd-trace-dotnet/tree/master/tracer/samples/ConsoleApp). It contains 2 dockerized applications with the same code. One time running on .net5 and the other on .net6. On .net5 the http call is automatically instrumentated as you can see on the picture. On .net6 nothing is received by the agent. 

![image](https://user-images.githubusercontent.com/36662277/145189195-918619e3-015f-49a8-bdd5-7b68a65f97cb.png)

**To Reproduce**
Run following commands to reproduce
```
git clone https://github.com/lippinio/broken-http-tracer-net6.git
cd broken-http-tracer-net6
docker build -f ConsoleApp6/Dockerfile ConsoleApp6/. -t consoleapp6
docker build -f ConsoleApp5/Dockerfile ConsoleApp5/. -t consoleapp5
docker run -it --rm consoleapp5
docker run -it --rm consoleapp6
```

**Expected behavior**
Automatic Instrumentation should work on .net6 as on .net5

**Comment by andrewlock** [comment]
Hello @lippinio. We're adding support for .NET 6 in .NET Tracer 2.0 - the PR that added support was #1885. We're actively working on getting this release out as soon as possible!

**Comment by lippinio** [comment]
Thank for info.
