### ISSUE TITLE
Memory leak problem when using datadog agent

### ISSUE THREAD

**Issue by lucasviniciusmachado** [DataDog/dd-trace-dotnet#2168]
Hi !!!

**Problem description**
We are facing a memory leak issue in our application when enabling the datadog agent.
We started having this problem when doing a migration from Mongo Cosmos to Mongo Atlas.

**Screenshots**
When doing a migration, observed in the following scenario on memory consumption.

![datadog_agent_memory](https://user-images.githubusercontent.com/96059267/146067738-c46cbb34-ddcc-4500-957c-e84ef44fa719.png)

Behavior of memory usage without the datadog (green) and with the datadog (red)

execution environment
- Instrumentation mode: Automatic with k8s
- OS: Linux
- CLR: .NET Core 3.1
- Tracer Version: 1.29.0

NOTE: no custom tracker is used, just a standard integration between datadog and .net.

**Comment by kevingosse** [comment]
We have a known issue with MongoDb: when creating the first instance of MongoClient (or basically anything that will cause the MongoDb driver to initialize a connection), the flow of the execution context isn't suppressed and so it captures the active trace. Then it will keep pinging the server in a background task, and every time that will add a new span to that trace. 

We opened an issue in the MongoDb repository (https://jira.mongodb.org/browse/CSHARP-3813) and we are looking at ways to mitigate the issue in the Datadog tracer.

In the meantime, assuming this is indeed the issue you are running into, you should be able to fix that by forcing the creation of one instance of `MongoClient` outside of any trace (for instance, in the startup of your application).

**Comment by lucasviniciusmachado** [comment]
@kevingosse, the solution has been applied as per your suggestion and the issue has been resolved. Thanks!

**Comment by Leonardo-Ferreira** [comment]
I'm facing a similar issue... is there a fix yet? my integration with datadog is quite recent (less than 2 weeks)

or should I look elsewhere for the problem?
