### ISSUE TITLE
Make resource names consistent across web framework integrations

### ISSUE THREAD

**Issue by swASO** [DataDog/dd-trace-dotnet#221]
**Describe the bug**
automatic instrumentation looks not like the traces from java lib. , see screenshot below

**Expected behavior**
should be the same

**Screenshots**
java: 
![image](https://user-images.githubusercontent.com/4096843/49280409-6ad7ec80-f48a-11e8-975e-ab65909b86ad.png)

.NetCore:
![image](https://user-images.githubusercontent.com/4096843/49280434-7e835300-f48a-11e8-9c01-50c08091be22.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode:  automatic with deb packages
- Tracer version: 0.5.1-beta
- OS: Linux / Docker image ( microsoft/dotnet:2.1-runtime-deps-stretch-slim )
- CLR: .Net Core 2.1

**Comment by lucaspimentel** [comment]
Thanks, @swASO. This was originally done this way due to the differences between using attribute routing or route templates in different versions of ASP.NET MVC and ASP.NET Web API. For example, when using attribute routing, we show the route as declared in the attribute, which looks like the Java routes you mention above. However, in the default MVC app template, _every_ route is `{controller}/{action}/{id}`, which is useless since every web request would be considered the same resource. In that case, we report the resource as `VERB controller.action` instead.

If we have access to the route template (i.e. `{controller}/{action}/{id}`) and the controller and action names, would it make sense to replace these values in the template and use that instead?

For example:
```csharp
// assume we got these values from the request context
string httpMethod = "POST";
string controllerName = "Contacts";
string actionName = "Edit";
string routeTemplate = "{controller}/{action}/{id}";

string route = routeTemplate.Replace("{controller}", controllerName)
                            .Replace("{action}", actionName );

// POST /Contacts/Edit/{id}
string resourceName = $"{httpMethod} /{route}";
```

**Comment by swASO** [comment]
no i think it would no fix the problem

little example 
```
[Produces("application/json")]
[Route("api/user"), Authorize]
public class UserController : Controller
{
    [HttpGet, Route("currentUser")]
    public IActionResult GetCurrentUser() { return Ok(); }
}
```
with default MVC template (`{controller}/{action}/{id}`)

would end in 
`GET user.getcurrentuser` 

but it should be
`GET api/user/currentUser`

**Comment by ffandreassoroko** [comment]
any new infos here ? 

https://forums.asp.net/t/2136122.aspx?How+to+get+the+Route+Name+

https://github.com/DataDog/dd-trace-dotnet/blob/develop/src/Datadog.Trace.ClrProfiler.Managed/Integrations/AspNetCoreMvc2Integration.cs#L33
> var routeTemplate = actionDescriptor.AttributeRouteInfo.Template;

**Comment by lucaspimentel** [comment]
Hey, @ffandreassoroko. We are rewriting the ASP.NET Core MVC integration soon to move away from using `dynamic` and instead emitting IL (like the MongoDB integration). The plan was to fix this issue at the same time.

**Comment by ffandreassoroko** [comment]
great! thanks for the information

**Comment by lucaspimentel** [comment]
We [did some work](https://github.com/DataDog/dd-trace-dotnet/pull/361) on this and included it in [release 1.3](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.3.0).

**Comment by ffandreassoroko** [comment]
> no i think it would not fix the problem
> 
> little example
> 
> ```
> [Produces("application/json")]
> [Route("api/user"), Authorize]
> public class UserController : Controller
> {
>     [HttpGet, Route("currentUser")]
>     public IActionResult GetCurrentUser() { return Ok(); }
> }
> ```
> 
> with default MVC template (`{controller}/{action}/{id}`)
> 
> would end in
> `GET user.getcurrentuser`
> 
> but it should be
> `GET api/user/currentUser`

ìs this also fixed ?

**Comment by lucaspimentel** [comment]
@ffandreassoroko: yes, in your example, you should get `api/user/currentUser` now. There are more improvements to the resource name coming in the next release. See #418 and #419.

**Comment by ffandreassoroko** [comment]
great, then i will just wait for the next release. 
thank you!!!
