### ISSUE TITLE
.net6 compatablity for dotnet tool dd-trace

### ISSUE THREAD

**Issue by lippinio** [DataDog/dd-trace-dotnet#2221]
https://github.com/DataDog/dd-trace-dotnet/blob/master/tracer/src/Datadog.Trace.Tools.Runner/Datadog.Trace.Tools.Runner.Tool.csproj

dd-trace tooling does not support .net6

run 
dotnet dd-trace
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '5.0.0' (x64) was not found.
  - The following frameworks were found:
      6.0.1 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by lucaspimentel** [comment]
Thanks, @lippinio! We are aware of this issue and there is a PR open to fix this in the next release: #2206.
