### ISSUE TITLE
v1 and v2 Public API changes

### ISSUE THREAD

**Issue by Havunen** [DataDog/dd-trace-dotnet#2234]
In v1 there is public API for starting a span with just operation name required.

in v2 Starting a new span requires 5 parameters while the internal method has 4 of them defined optional with null as default value. Is this intentional?

Public API:
```c#
        ISpan IDatadogOpenTracingTracer.StartSpan(string operationName, ISpanContext parent, string serviceName, DateTimeOffset? startTime, bool ignoreActiveScope)
        {
            return StartSpan(operationName, parent, serviceName, startTime, ignoreActiveScope);
        }
```

Internal API:

```c#
        internal Span StartSpan(string operationName, ISpanContext parent = null, string serviceName = null, DateTimeOffset? startTime = null, bool ignoreActiveScope = false)
        {
            return StartSpan(operationName, tags: null, parent, serviceName, startTime, ignoreActiveScope, spanId: null);
        }
```

If all of these parameters needs to be given is there some documentation available?

**Comment by andrewlock** [comment]
Hi @Havunen, are use using the OpenTracing API or the Datadog Tracer API? We intentionally made changes to clean things up in V2, as the old API didn't make sense any more. However, you can still start a span with just the operation name. 

For example, there is this API which uses only the operation name: https://github.com/DataDog/dd-trace-dotnet/blob/1bfbdb9c63fa0cb4d3e481a01c495046f34ba98d/tracer/src/Datadog.Trace/Tracer.cs#L246

So you can use it like this:

```csharp
using (var scope = Datadog.Tracer.Instance.StartActive("MyCustomSpan"))
{
    // ...
}
```

Alternatively, if you need to provide additional span creation options, there is this API: https://github.com/DataDog/dd-trace-dotnet/blob/1bfbdb9c63fa0cb4d3e481a01c495046f34ba98d/tracer/src/Datadog.Trace/Tracer.cs#L257

This uses the new `SpanCreationSettings` type to control span creation:

```csharp
public struct SpanCreationSettings
{
    /// <summary>
    /// Gets or sets an explicit start time for the span. If not set, uses the current time.
    /// </summary>
    public DateTimeOffset? StartTime { get; set; }

    /// <summary>
    /// Gets or sets the span's parent. If not set, the current active span context will be used,
    /// or a new one will be created if none is currently active.
    /// </summary>
    public ISpanContext Parent { get; set; }

    /// <summary>
    /// Gets or sets whether closing the scope will close the contained span.
    /// If not set, defaults to <c>true</c>.
    /// </summary>
    public bool? FinishOnClose { get; set; }
}
```

If you need to set additional properties that are no longer exposed in the method, you can set those directly on the span. For example:


```csharp
using (var scope = Datadog.Tracer.Instance.StartActive("MyCustomSpan"))
{
    scope.Span.ServiceName = "Some other service";
    //...
}
```
