### ISSUE TITLE
Add ability to build TracerSettings from ImmutableTracerSettings

### ISSUE THREAD

**Issue by fjmorel** [DataDog/dd-trace-dotnet#2257]
**Is your feature request related to a problem? Please describe.**

I would like to easily enable/disable automatic instrumentation of various integrations at runtime. For example, there is an API request in our admin site that can generate thousands of RabbitMQ messages (and traces) for which I want to disable the RabbitMQ integration, but then re-enable it for everything else. I have backend processes that can generate _millions_ which has caused OOM exceptions in the past.

Before v2, I would get `Tracer.Instance.Settings`, modify `DisabledIntegrationNames`, and then put a new tracer using that in `Tracer.Instance`.

After v2, I have to rebuild `TracerSettings` manually, then call `Tracer.Configure(settings)`.

I would like to not have to worry about not copying newly added settings in the future from the current immutable settings to my new settings, and make it easier to convert `ImmutableIntegrationSettingsCollection` into `DisabledIntegrationNames`.

**Describe the solution you'd like**

A constructor for `TracerSettings` that takes `ImmutableTracerSettings`

**Describe alternatives you've considered**

* Ability to enable/disable specific integrations at runtime directly. While this would be nice, I believe my proposed solution would be more useful for anyone else who might want to modify certain settings.
* `TracerSettings ToMutable()` on `ImmutableTracerSettings` (not a huge fan of the name, but it's the first that came to mind)

**Additional context**

My initial cloning attempt:

```csharp
public static TracerSettings Clone(ImmutableTracerSettings immutable)
{
    var exporter = new ExporterSettings
    {
        AgentUri = immutable.Exporter.AgentUri,
        DogStatsdPort = immutable.Exporter.DogStatsdPort,
        MetricsPipeName = immutable.Exporter.MetricsPipeName,
        PartialFlushEnabled = immutable.Exporter.PartialFlushEnabled,
        PartialFlushMinSpans = immutable.Exporter.PartialFlushMinSpans,
        TracesPipeName = immutable.Exporter.TracesPipeName,
        TracesPipeTimeoutMs = immutable.Exporter.TracesPipeTimeoutMs,
    };
    var settings = new TracerSettings
    {
        DisabledIntegrationNames = new(),
        ServiceName = immutable.ServiceName,
        Environment = immutable.Environment,
        Exporter = exporter,
        GlobalTags = immutable.GlobalTags.ToDictionary(x => x.Key, x => x.Value),
        HeaderTags = immutable.HeaderTags.ToDictionary(x => x.Key, x => x.Value),
        ServiceVersion = immutable.ServiceVersion,
        TraceEnabled = immutable.TraceEnabled,
        CustomSamplingRules = immutable.CustomSamplingRules,
        DiagnosticSourceEnabled = true,// todo: not sure what this is on the immutable class
        GlobalSamplingRate = immutable.GlobalSamplingRate,
        LogsInjectionEnabled = immutable.LogsInjectionEnabled,
        TracerMetricsEnabled = immutable.TracerMetricsEnabled,
        StartupDiagnosticLogEnabled = immutable.StartupDiagnosticLogEnabled,
        KafkaCreateConsumerScopeEnabled = immutable.KafkaCreateConsumerScopeEnabled,
        MaxTracesSubmittedPerSecond = immutable.MaxTracesSubmittedPerSecond,
        Integrations = { },// todo: convert enabled integrations to disabled integrations
#pragma warning disable CS0618// keep cloning setting until it's actually removed
        AnalyticsEnabled = immutable.AnalyticsEnabled,
#pragma warning restore CS0618
    };
    return settings;
}
```

**Comment by andrewlock** [comment]
Hi @fjmorel,

If I understand correctly, what you're trying to achieve can be done with the existing API. For example, if you want to disable the `RabbitMQ` integration you can do the following in v2:

```csharp
var settings = TracerSettings.FromDefaultSources();
settings.Integrations["RabbitMQ"].Enabled = false;

Tracer.ConfigureSettings(settings);
```

The static `TracerSettings.FromDefaultSources()` method uses all of the default sources (e.g. environment variables, datadog.json [as defined in the docs](https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-core/?tab=windows#configuration)) to build a mutable `TracerSettings` instance. You can then disable the integration in code if required, and update the tracer settings.

A potentially easier alternative (as it doesn't require changing the Tracer instance at all) is to disable the integration using environment variables or other settings. For example, setting `DD_TRACE_RabbitMQ_ENABLED=false` will achieve the same thing, without the need to reconfigure the `Tracer`.

We were considering adding an additional constructor overload to `TracerSettings` to make the `FromDefaultSources()` option more discoverable, e.g.

```csharp
/// <summary>
/// Initializes a new instance of the <see cref="TracerSettings"/> class with default values, or using the default sources.
/// </summary>
/// <param name="source">If <c>true</c>, creates a <see cref="TracerSettings"/> populated from the default sources such as environment variables etc. If <c>false</c>, uses the default values.</param>
public TracerSettings(bool useDefaultSources) 
    : this(useDefaultSources ? TracerSettings.FromDefaultSources() : null)
{
}
```

Do you think this would be valuable? Thanks!

**Comment by fjmorel** [comment]
Oh, that is exactly what I needed, but I completely missed it! Yes, I think adding that constructors would definitely help with discoverability.

This is what I ended up doing:

```csharp
private static readonly HashSet<string> _currentlyDisabledIntegrations = new();

/// <summary>
/// Disable tracing of a integration automatically by DataDog.
/// This can be useful to avoid memory issues in backfills
/// that do millions of queries/updates.
/// </summary>
public static void DisableIntegration(string integration)
{
    var settings = CreateNewSettings();
    settings.DisabledIntegrationNames.Add(integration);
    _currentlyDisabledIntegrations.Add(integration);
    Tracer.Configure(settings);
}

/// <summary>
/// Re-enable tracing of a integration automatically by DataDog.
/// This is intended to be called after whatever process
/// called <see cref="DisableIntegration"/> is complete.
/// </summary>
public static void EnableIntegration(string integration)
{
    var settings = CreateNewSettings();
    settings.DisabledIntegrationNames.Remove(integration);
    _currentlyDisabledIntegrations.Remove(integration);
    Tracer.Configure(settings);
}

private static TracerSettings CreateNewSettings()
{
    var settings = TracerSettings.FromDefaultSources();
    foreach (var integration in _currentlyDisabledIntegrations)
        settings.DisabledIntegrationNames.Add(integration);
    return settings;
}
```

**Comment by andrewlock** [comment]
That's great to hear @fjmorel. I've created #2266 adding this API, so will close this one for now, thanks!
