### ISSUE TITLE
Errors were encountered while processing datadog-dotnet-apm_2.1.1-profiler-beta1_amd64.deb

### ISSUE THREAD

**Issue by Darsan04** [DataDog/dd-trace-dotnet#2360]
We are getting this below error in the docker build. We face this error in the latest release (https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.1.1-profiler-beta1)

It is unable to process with the latest .deb files.

RUN mkdir -p /opt/datadog     && mkdir -p /var/log/datadog     && TRACER_VERSION=$(curl -s https://api.github.com/repos/DataDog/dd-trace-dotnet/releases/latest | grep tag_name | cut -d '"' -f 4 | cut -c2-)     && curl -LO https://github.com/DataDog/dd-trace-dotnet/releases/download/v${TRACER_VERSION}/datadog-dotnet-apm_${TRACER_VERSION}_amd64.deb     && dpkg -i ./datadog-dotnet-apm_${TRACER_VERSION}_amd64.deb     && rm ./datadog-dotnet-apm_${TRACER_VERSION}_amd64.deb
 ---> Running in d11684a220d3
[91m  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                         [0m[91m        Dload  Upload   Total   Spent    Left  Speed

  0     0    0[0m[91m     0    0     0 [0m[91m     0      [0m[91m0 --:--:-- --[0m[91m:--:-- --:-[0m[91m-:-- [0m[91m    0[0m[91m
100     9  100     9    0     0     97      0 --:--:-- --:--:-- --:--:--    97
[0m[91mdpkg-deb: error: './datadog-dotnet-apm_2.1.1-profiler-beta1_amd64.deb' is not a Debian format archive
[0m[91mdpkg: error processing archive ./datadog-dotnet-apm_2.1.1-profiler-beta1_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
[0m[91mErrors were encountered while processing:
 ./datadog-dotnet-apm_2.1.1-profiler-beta1_amd64.deb
[0mThe command '/bin/sh -c mkdir -p /opt/datadog     && mkdir -p /var/log/datadog     && TRACER_VERSION=$(curl -s https://api.github.com/repos/DataDog/dd-trace-dotnet/releases/latest | grep tag_name | cut -d '"' -f 4 | cut -c2-)     && curl -LO https://github.com/DataDog/dd-trace-dotnet/releases/download/v${TRACER_VERSION}/datadog-dotnet-apm_${TRACER_VERSION}_amd64.deb     && dpkg -i ./datadog-dotnet-apm_${TRACER_VERSION}_amd64.deb     && rm ./datadog-dotnet-apm_${TRACER_VERSION}_amd64.deb' returned a non-zero code: 1

**Comment by pierotibou** [comment]
Hello @ValdasDienas, thanks for reporting this. 
We have indeed missed to flag this release a a prerelease. This is the case now, you shouldn't face the issue anymore)

FYI, we are starting to work on sharing Datadog .Net Continuous Profiler in this very repository, which is the reason of this morning release.

Sorry for any inconvenience caused

**Comment by petepry** [comment]
Use version 2.1.1 instead, like:

> TRACER_VERSION=2.1.1

The newest release broke our build pipeline as well.
Worth to mention that 2.2.1-profiler-beta1 DOES NOT support other OS than windows...

**Comment by pierotibou** [comment]
> Use version 2.1.1 instead, like:

This shouldn't be necessary. Indeed, https://api.github.com/repos/DataDog/dd-trace-dotnet/releases/latest now points back to the Tracer 2.1.1 release, so the issue should be fixed

**Comment by Darsan04** [comment]
@pierotibou Thanks for your quick response and for resolving the issue.
Thanks again
