### ISSUE TITLE
Don't recursively acquire std::shared_mutex in rejit_handler

### ISSUE THREAD

**Issue by johnbley** [DataDog/dd-trace-dotnet#2366]
Hi!

In the file `rejit_handler.cpp` there is extensive use of a reader/writer lock
set around `m_shutdown_lock`.  The logic there looks generally sound except for
one thing: msvc `std::shared_mutex`es use [Slim Reader/Writer locks 
(SRW)](https://docs.microsoft.com/en-us/windows/win32/sync/slim-reader-writer--srw--locks), and these are not reentrant/recursive. (Another source for msvc shared_mutex being non-recursive is 
https://docs.microsoft.com/en-us/cpp/standard-library/shared-mutex?view=msvc-170 )

There are several paths in `RejitHandler` where a snippet like the following happens:
```
void RejitHandler::SomeMethod() 
{
  ReadLock r_lock(m_shutdown_lock);
  if (m_shutdown) 
  {
     return;
  }
  ...
  // note that r_lock is still in-scope and active here
  OtherRejitHandlerMethod(); // which will also check m_shudown_lock and m_shutdown
}
```
One current example is `AddNGenModule` calling `RequestRejitForInlinersInModule` - after I found 3 of these I stopped counting.

The cleanest fix I see for this is to scope the lock ownership to just what's needed to check shutdown, most likely 
by the addition of a helper method:
```
bool RejitHandler::ShuttingDown()
{
    ReadLock r_lock(m_shutdown_lock);
    return m_shutdown;
}

void RejitHandler::SomeMethod()
{
  if (ShuttingDown())
  {
    // variations exist returning nullptr, false, etc. so this can't easily be a macro
    return;
  }
  ...
  OtherRejitHandlerMethod();
}
```

I'm happy to submit such a PR; just wanted to open a discussion first to see if this was OK or if anybody had a better idea.

**Comment by andrewlock** [comment]
Hi @johnbley, thanks for flagging this! 

Your proposal sounds good, thanks, we'd be very happy with a PR 🙂 

However, there is a largish PR (https://github.com/DataDog/dd-trace-dotnet/pull/2250) currently in review that will change that file quite a lot, so you may want to hold off until that is merged? Up to you, thanks either way! 🙂

**Comment by johnbley** [comment]
> However, there is a largish PR (#2250) currently in review that will change that file quite a lot, so you may want to hold off until that is merged? Up to you, thanks either way! 🙂

Makes sense; I'll keep an eye out.  Giving that PR a skim it looks like this issue might already be addressed in there.  Thanks!
