### ISSUE TITLE
Erro: "Unable to load one or more of the requested types."

### ISSUE THREAD

**Issue by caiovms** [DataDog/dd-trace-dotnet#2425]
**Describe the bug**

After adding the Datadog.Monitoring.Distribution in my API project, any request I make returns the error below:

```
{
  "errors": [
    "Unable to load one or more of the requested types.\nCould not load type 'Microsoft_AspNetCore_Routing__ADB9793829DDAE60.Microsoft_AspNetCore_Routing_Patterns_RoutePatternParameterPart.Datadog_Trace_DiagnosticListeners_AspNetCoreDiagnosticObserver__RoutePatternContentPartStruct_30' from assembly 'DuckTypeNotVisibleAssembly.RoutePatternParameterPart_30, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'."
  ]
}
```

The curious thing is that this only happens when the API is running in the container on AWS, locally on IIS or docker, I couldn't replicate the behavior.

**To Reproduce**
To reproduce the behavior you can create an API using .NET 6, install Datadog.Monitoring.Distribution 2.3.0-beta01 and upload it to an ECS on AWS. Following [this documentation](https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-core/?tab=windows#linux-docker-container), the commands below were included in the docker container image:

```
# Enable Datadog automatic instrumentation -> App is being copied to /app, so Datadog assets are at /app/datadog
ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
ENV CORECLR_PROFILER_PATH=/app/datadog/linux-x64/Datadog.Trace.ClrProfiler.Native.so
ENV DD_DOTNET_TRACER_HOME=/app/datadog

# Run the createLogPath script on Linux to ensure the automatic instrumentation logs are generated without permission isues
RUN /app/datadog/createLogPath.sh
```

**Screenshots**

![image](https://user-images.githubusercontent.com/5957094/153510982-e8b2048c-99a6-45cf-ae3e-a00b28968fe7.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: NuGet Package Datadog.Monitoring.Distribution 2.3.0-beta01
- Tracer version: 2.3.0
- OS: Ubuntu 20.04.3 LTS
- CLR: .NET 6

**Additional context**

API Endpoint:

```
curl -X 'GET' \
  'https://myapi.com/api/v1/portfolios/5c0178237a6c1e000f6a72b8/returns/global/current/profit-and-loss-statement?referenceDate=2021-01-01&liquidity=10' \
  -H 'accept: text/plain'
```

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by caiovms** [comment]
Hi @andrewlock , off course, i'm using **AWS ECS Fargate** to run my container, bellow my dockerfile:

```
FROM mcr.microsoft.com/dotnet/aspnet:6.0

ENV ASPNETCORE_ENVIRONMENT Development

WORKDIR /app

# dotnet publish "Project.csproj" -c Release -o ./publish
COPY ./publish .

# Enable Datadog automatic instrumentation -> App is being copied to /app, so Datadog assets are at /app/datadog
ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
ENV CORECLR_PROFILER_PATH=/app/datadog/linux-x64/Datadog.Trace.ClrProfiler.Native.so
ENV DD_DOTNET_TRACER_HOME=/app/datadog

# Run the createLogPath script on Linux to ensure the automatic instrumentation logs are genereated without permission isues
RUN /app/datadog/createLogPath.sh

CMD ["dotnet Project.dll"] 
```

Also, the following line was added to my `API.csproj`:

`<PackageReference Include="Datadog.Monitoring.Distribution" Version="2.0.1-beta01" /> `

**Comment by andrewlock** [comment]
Hi @caiovms, thanks for that. That's very strange, I can't replicate the behaviour with a sample app unfortunately.

I think to get to the bottom of this it would be useful to collect more detailed info about your configuration. Can you please create a support ticket by emailing [support@datadoghq.com](mailto:support@datadoghq.com)? Please include a link to this github issue so we can tie the problems together. Thanks!

**Comment by bigred8982** [comment]
I ran into something similar. 

We run in containers and we inject the DataDog .NET Tracer package into our base containers. See https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-core/?tab=linux#install-the-tracer for details.

I have some code in my application that is dynamically loading Types from Assemblies. This fails when datadog assemblies are loaded in the app domain.

__Stack Trace Snippet__

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Microsoft_AspNetCore_Routing__ADB9793829DDAE60.Microsoft_AspNetCore_Routing_Patterns_RoutePatternParameterPart.Datadog_Trace_DiagnosticListeners_AspNetCoreDiagnosticObserver__RoutePatternContentPartStruct_15' from assembly 'DuckTypeNotVisibleAssembly.RoutePatternParameterPart_15, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   ...
```

__Code__
```
System.AppDomain.CurrentDomain.GetAssemblies()
  .SelectMany(a => a.GetTypes());
```

A workaround for us is to exclude Assemblies prefixed with `DuckTypeNotVisibleAssembly` or rewrite our code to expect potential failures on GetTypes() by incorporating exception handling into the mix.

**Comment by andrewlock** [comment]
Thanks for the context @bigred8982! That makes sense - we've reproduced the issue, and are working on a fix.

**Comment by denisp13** [comment]
Upvoting for the same issue 

``System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Could not load type 'Microsoft_AspNetCore_Routing__ADB9793829DDAE60.Microsoft_AspNetCore_Routing_Patterns_RoutePatternParameterPart.Datadog_Trace_DiagnosticListeners_AspNetCoreDiagnosticObserver__RoutePatternContentPartStruct_24' from assembly 'DuckTypeNotVisibleAssembly.RoutePatternParameterPart_24, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'.    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)    at System.Reflection.RuntimeModule.GetTypes()    at System.Reflection.Assembly.GetTypes()    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()    at Cvs.service.Api.Contracts.DocumentFilter.OpenApiIncludeAttributeDocumentFilter`1.Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context) in /Cvs.service.Api.Contracts/DocumentFilter/OpenApiIncludeAttributeDocumentFilter.cs:line 25    at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context) System.TypeLoadException: Could not load type 'Microsoft_AspNetCore_Routing__ADB9793829DDAE60.Microsoft_AspNetCore_Routing_Patterns_RoutePatternParameterPart.Datadog_Trace_DiagnosticListeners_AspNetCoreDiagnosticObserver__RoutePatternContentPartStruct_24' from assembly 'DuckTypeNotVisibleAssembly.RoutePatternParameterPart_24, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null'.``

**Comment by andrewlock** [comment]
Thanks all, we've just merged #2716 which should fix this issue. The next release should include this change. Once it's released if you could test it out and let us know if you have any issues that would be great!

**Comment by pierotibou** [comment]
Hello, the [2.8.0 ](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.8.0) has been released today. It contained the fix mentionned. Could you please update and let us know if it indeed fixes the issue?

**Comment by caiovms** [comment]
Hi @pierotibou , of course, I just tested it here and it worked perfectly for me.
