### ISSUE TITLE
Azure App Service Crashes since updating from 2.3 to 2.4.4. 

### ISSUE THREAD

**Issue by asalvo** [DataDog/dd-trace-dotnet#2599]
**Describe the bug**
Since we updated from 2.3 to 2.4.4 our Azure App Services are seeing a large number of native crashes. I also opened a support Ticket (720023) but have not received a response yet. 

Here is an analysis file from a memory dump. This line stood out to me `FAILURE_BUCKET_ID:  INVALID_POINTER_READ_80000003_clr.dll!ProfToEEInterfaceImpl::EnumNgenModuleMethodsInliningThisMethod` as did this note in in the change log for version 2.4.0 `Refactor all EnumNgenModuleMethodsInliningThisMethod call sites to resolve NGEN issues`

[CrashAnalysis.txt](https://github.com/DataDog/dd-trace-dotnet/files/8346259/CrashAnalysis.txt)

**Runtime environment (please complete the following information):**
- Instrumentation mode: [e.g. automatic with msi installer or manual with NuGet package]
- Tracer version: 2.4.4
- OS: Azure App Services
- CLR: .NET Framework 4.8

**Comment by kevingosse** [comment]
Sorry about that. The change you're quoting was supposed to fix this error, so I guess we missed something.
Is there any chance you could provide an actual memory dump? The stacktrace looks incomplete in the text file.

Until we come up with a fix, you can mitigate the issue by setting the `DD_CLR_ENABLE_NGEN=1` environment variable. The application should stop crashing, at the expense of taking a bit longer to load.

**Comment by asalvo** [comment]
The memory dumps are ~500MB. What is the best way to upload those to you?

**Comment by kevingosse** [comment]
We believe that https://github.com/DataDog/dd-trace-dotnet/pull/2602 will fix this issue. It will ship with the next release.

**Comment by pierotibou** [comment]
Hello @asalvo . Thanks again for the report and providing the memory dumps.
The PR quoted above has been released today as part of [2.6.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.6.0) release. 
Let us know if it's solving your issue.

**Comment by JCPWX** [comment]
@kevingosse @pierotibou we had the same problem described here on version 2.1.0 but specifically (and immediately) after the Microsoft March updates were deployed. We didn't have the problem when we downgraded to 1.27.1. Are you aware whether the problem that @asalvo describes was introduced with the Microsoft March updates? 

Specifically the crash we were experiencing matched the second known issue under this link: https://support.microsoft.com/en-us/topic/march-8-2022-kb5011497-os-build-20348-587-d7197493-db3c-486d-94bd-37c6235d2fbf: You might also receive an access violation (0xc0000005) error. 

2.6.0 is working for us a well I'm just still curious whether there was truly a correlation with the Microsoft March updates as we had been running fine on 2.1.0 (only for 10 days) and the problem hit us the very first minute after March updates had been deployed.

**Comment by kevingosse** [comment]
@JCPWX  It's likely that the update is linked, but not in the way you think. The access violation mentioned in the KB is unrelated. However, sometimes the assemblies are not NGEN'd after updating the .NET Framework (I don't really know why). It's possible that in your case the assemblies weren't NGEN'd following the previous update, and then they were NGEN'd following this update.
The bug in the Datadog tracer affects the loading of NGEN assemblies, so that last update created the condition for the crash to happen.
