### ISSUE TITLE
DynamicMethodBuilder.CreateMethodCallDelegate  BUG

### ISSUE THREAD

**Issue by wang9563** [DataDog/dd-trace-dotnet#266]
When I use `DynamicMethodBuilder.CreateMethodCallDelegate`  and `delegateType` is `Action` 
It throw `Value cannot be null.` exception in code `dynamicMethod.CastClass(returnType);`

I see `line 78` of code
```
returnType = null; //before modify
```
should be 
```
returnType = typeof(void);
```

I try modify code and it runing well.

**Comment by lucaspimentel** [comment]
Thanks @wang9563. We hit this issue ourselves recently and is fixed as part of #263.
