### ISSUE TITLE
build.ps1 doesn't work

### ISSUE THREAD

**Issue by CooperLiu** [DataDog/dd-trace-dotnet#268]
**Describe the bug**

when i tried to build by run script of build.ps1, had some issues。

**To Reproduce**
1. clone new repo
2. just run [build.ps1](https://raw.githubusercontent.com/DataDog/dd-trace-dotnet/develop/build.ps1)

**Expected behavior**

just want all of projects ,build success

**Screenshots**

**Runtime environment (please complete the following information):**
- Instrumentation mode: [e.g. automatic with msi installer or manual with NuGet package]
- Tracer version: [e.g. 0.7.1]
- OS: [e.g. Windows 10 ]
- CLR: [e.g. .NET Framework 4.6.2, .NET Core 2.1]

**Additional context**

**Comment by lucaspimentel** [comment]
Thanks for feedback, @CooperLiu. `build.ps1` is a leftover from previous versions of the Tracer that used [Cake](https://cakebuild.net/) as the build system. We don't use `build.ps1` anymore and it should be replaced.

For now, you can use these commands from a VS2017 Developer Command Prompt to build everything:
```cmd
rem Install vcpkg packages, only needed once
scripts\install-vcpkgs.ps1

rem Restore NuGet packages
nuget restore Datadog.Trace.sln

rem Build C++ code (either x64 or x86)
msbuild Datadog.Trace.sln /t:BuildCpp;BuildCppTests /p:Configuration=Debug;Platform=x64

rem Build C# code
msbuild Datadog.Trace.sln /t:BuildCsharp,BuildCsharpTests /p:Configuration=Debug;Platform=AnyCPU

rem Build MSI installer
msbuild Datadog.Trace.sln /t:msi /p:Configuration=Debug;Platform=x64
```

Note: I just pulled these from the CI build and didn't run them myself directly, so they might need a little tweaking. Also, if you have VS2019 preview installed, you might need to specify the MSBuild version to restore NuGet packages:
```cmd
nuget restore Datadog.Trace.sln -MSBuildVersion 15.9
```

I'll keep this issue open until we replace `build.ps1` with a working build script.

**Comment by lucaspimentel** [comment]
I edited the commands above to remove `install-vcpkgs.ps1`, since we don't use vcpkg anymore. I will add these to the readme file and close this issue.

**Comment by lucaspimentel** [comment]
Closing this issue since we added command line build steps for Windows in https://github.com/DataDog/dd-trace-dotnet/pull/354.
