### ISSUE TITLE
Datadog 2.6.0 doesn't have backward compatibility ?

### ISSUE THREAD

**Issue by sravangontla** [DataDog/dd-trace-dotnet#2711]
**Describe the bug**
It throws an error after using latest version of Nuget package in our .Net core Application.

we are using 
  .Net Core 3 WebAPI
  Angular 8 

**To Reproduce**
1.  Download latest version from Nuget
2.  Change the trace setting as per new syntax using Tracer.Configure method
3. Build the application 
4. Deploy the application in IIS and browse the application.
5. See error
"Method not found
Datadog.Trace.Vendors.Statsdclient.IDogstatsd"
 
**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/86965039/164500296-5acce305-46c8-43e0-9881-3176418a65b0.png)

 
- Instrumentation mode: [manual with NuGet package]
- Tracer version: [e.g. 1.28.7]
- OS: [e.g. Windows Server 2019 ]
- CLR: [ .NET Core 3.1]

**Comment by andrewlock** [comment]
Hi @sravangontla,

This error is typically a symptom of when you are using both the installer _and_ the NuGet, and you have used different version numbers in each. The fact you are seeing `Method not found` indicates a very old version of Datadog.Trace. 


If you have updated _both_ your installer and NuGet to 2.x versions, then it's technically possible to have mis-matched version numbers. However this has a small performance penalty, so we recommend always keeping your version numbers in-sync.

**Comment by lucaspimentel** [comment]
Closing as state since we got no reply or additional information from OP. If you need further assistance, please contact support@datadoghq.com. Thanks!
