### ISSUE TITLE
Readme code example doesn't compile with 2.8.0

### ISSUE THREAD

**Issue by Jamie-Clayton** [DataDog/dd-trace-dotnet#2778]
**Describe the bug**

**To Reproduce**
1. Go to '[Custom .net Configuration](https://github.com/DataDog/dd-trace-dotnet/blob/master/docs/Datadog.Trace/README.md)'
2. Create a blank webapi .net core solution with <PackageReference Include="Datadog.Trace.OpenTracing" Version="2.8.0" />  '....'
3. Scroll down to '[Simplification of the tracer interface](https://github.com/DataDog/dd-trace-dotnet/blob/master/docs/Datadog.Trace/README.md#simplification-of-the-tracer-interface)'
4. Copy and paste the example code into a sample controller method.
```
var spanCreationSettings = new SpanCreationSettings() { Parent = spanContext };
```
5. Compiler warning for spanContext 

**Expected behavior**
Quickly copy sample code into a solution and get the expected log/trace interaction working.

Ideally, logs and tracing for (web ui, webapi,SQL Server Database [3 tier]) solutions should work to ensure logging (including debugging logging) links traces and errors with custom spans. There are some differences to the api examples provided for open telemetry, see https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/examples/Console/InstrumentationWithActivitySource.cs.

**Runtime environment (please complete the following information):**
- Instrumentation mode: [e.g. automatic with msi installer or manual with NuGet package]
- Tracer version: 2.8.0
- OS: Windows Server 2016
- CLR: net5.0

**Comment by lucaspimentel** [comment]
It seems like we have the simple "create a span" example in the repository readme and the NuGet readme (same file, iirc). There are also more examples in the official docs: https://docs.datadoghq.com/tracing/trace_collection/custom_instrumentation/dotnet/
