### ISSUE TITLE
SamplingPriority is not propagated properly for B3ContextPropagator and W3CContextPropagator

### ISSUE THREAD

**Issue by moonheart** [DataDog/dd-trace-dotnet#2826]
Hello,

When I using b3 style, I found outbound `x-b3-sampled` is always `0`.

After digging the code, I found in `DatadogContextPropagator` ,  `SamplingPriority` is retrived from `TraceContext `and `SpanContext`:
https://github.com/DataDog/dd-trace-dotnet/blob/5d649190c36b11f76a0cdcade5c1a129d8a45d9b/tracer/src/Datadog.Trace/Propagators/DatadogContextPropagator.cs#L27

But in `B3ContextPropagator` and `W3CContextPropagator`, only `SpanContext` is used:
https://github.com/DataDog/dd-trace-dotnet/blob/5d649190c36b11f76a0cdcade5c1a129d8a45d9b/tracer/src/Datadog.Trace/Propagators/B3ContextPropagator.cs#L36
https://github.com/DataDog/dd-trace-dotnet/blob/5d649190c36b11f76a0cdcade5c1a129d8a45d9b/tracer/src/Datadog.Trace/Propagators/W3CContextPropagator.cs#L25

Is this an expected behavior or a bug?

**Comment by andrewlock** [comment]
Thanks for flagging this @moonheart, you're right, this looks like a bug. We've opened a PR to fix it #2828, so it should be included in a future release

**Comment by pierotibou** [comment]
Hello, this has been released today as part of [v.210.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.10.0)

**Comment by moonheart** [comment]
@pierotibou Thanks, thats awesome!
