### ISSUE TITLE
/opt/datadog/createLogPath.sh: Permission denied

### ISSUE THREAD

**Issue by danilobbezerra** [DataDog/dd-trace-dotnet#2908]
Ubuntu : 22.04
I'm trying to install Agent trace 
`sudo dpkg -i ./datadog-dotnet-apm_2.10.0_amd64.deb && /opt/datadog/createLogPath.sh`

and I'm getting the following error:

`-bash: /opt/datadog/createLogPath.sh: Permission denied`

Can someone help me?

I'm using root user

**Comment by pierotibou** [comment]
Hello @danilobbezerra,
it seems that starting our last release, the createLogPath.sh do not have the right access permissions. We'll look into that. Sorry for the inconvenience.
Meanwhile, I assume you could use something like this to do your setup:
`dpkg -i data/datadog-dotnet-apm_2.10.0_amd64.deb && chmod +x /opt/datadog/createLogPath.sh && /opt/datadog/createLogPath.sh`

**Comment by pierotibou** [comment]
FYI, this should normally be released tomorrow.

**Comment by pierotibou** [comment]
FYI, this has been indeed released as part of our [2.11.0 release](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.11.0).
