### ISSUE TITLE
Automatically inject correlation identifiers into log messages

### ISSUE THREAD

**Issue by parraclaudio** [DataDog/dd-trace-dotnet#2910]
I am trying  to enable automatic correlation identifier injection using the package version 2.10.0. However, the logged properties (dd_trace_id, dd_version, dd_service, dd_env) are not being logged anymore. 

I am using the [SerilogExample](https://github.com/DataDog/dd-trace-dotnet/tree/master/tracer/samples/AutomaticTraceIdInjection/SerilogExample) as project to do the tests and I didn`t change anything, only the version of DataDog.Trace package.  And the results are:
```
Datadog.Trace  Version 1.31.2
-------------------------------
{"Timestamp":"2022-06-20T23:47:18.8214709-03:00","Level":"Information","MessageTemplate":"Message before a trace.","Properties":{"order-number":1024,"serviceName":"SerilogExample","applicationVersion":"1.0.0.0"}}
{"Timestamp":"2022-06-20T23:47:19.1242922-03:00","Level":"Information","MessageTemplate":"Message during a trace.","Properties":{"dd_service":"SerilogExample","dd_version":"1.0.0","dd_env":"dev","dd_trace_id":"8448889662018737848","dd_span_id":"6686629885022921939","order-number":1024,"serviceName":"SerilogExample","applicationVersion":"1.0.0.0"}}
{"Timestamp":"2022-06-20T23:47:19.1355577-03:00","Level":"Information","MessageTemplate":"Message after a trace.","Properties":{"order-number":1024,"serviceName":"SerilogExample","applicationVersion":"1.0.0.0"}}


Datadog.Trace  Version 2.10.0
-------------------------------
{"Timestamp":"2022-06-20T23:48:18.8324620-03:00","Level":"Information","MessageTemplate":"Message before a trace.","Properties":{"order-number":1024,"serviceName":"SerilogExample","applicationVersion":"1.0.0.0"}}
{"Timestamp":"2022-06-20T23:48:19.1069486-03:00","Level":"Information","MessageTemplate":"Message during a trace.","Properties":{"order-number":1024,"serviceName":"SerilogExample","applicationVersion":"1.0.0.0"}}
{"Timestamp":"2022-06-20T23:48:19.1106834-03:00","Level":"Information","MessageTemplate":"Message after a trace.","Properties":{"order-number":1024,"serviceName":"SerilogExample","applicationVersion":"1.0.0.0"}}
```

**Comment by pierotibou** [comment]
Hello @parraclaudio, starting #2152, log injection needs automatic instrumentation enabled. 
I realized we haven't been super vocal in the release notes at the time and we haven't changed the samples since then, I'll fix that. 

So to fix the issue and test locally, you can install the tracer and set the following variables in the `lauchSettings.json` of the test project:
```
        "CORECLR_ENABLE_PROFILING": "1",
        "CORECLR_PROFILER": "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}",
        "DD_DOTNET_TRACER_HOME": $PATH_TO_THE_TRACER_FOLDER,
        "CORECLR_PROFILER_PATH": $PATH_TO_THE_TRACER_NATIVE_LIBRARY
```

Regardless, we assumed that this changed wouldn't be an issue as most of our users rely on automatic instrumentation, isn't it your case?

**Comment by parraclaudio** [comment]
Thank you for your support @pierotibou, was a misunderstanding of the docs and  this is not an issue. 

Following your instructions the properties are being logged.
Added the package [Datadog.Monitoring.Distribution](https://www.nuget.org/packages/Datadog.Monitoring.Distribution#versions-body-tab) and set the variables in the launchsettings. 

The package added is a prerelease (beta version), would you recommend use it in production env ?

**Comment by pierotibou** [comment]
First, you seem to have properly handled context propagation in your code. 

Then, regarding the tracer setup (the document linked is mainly linked to the agent), you could follow this [inapp docs filtered on your setup](https://app.datadoghq.com/apm/docs?architecture=container-based&collection=Same%20host&environment=docker&framework=windows_iis&language=net) where you setup the tracer in the container itself, setting the right environment variables: 

Basically, it could look like something like this if you run on linux:
```
# Please select the corresponding download for your Linux containers https://github.com/DataDog/dd-trace-dotnet/releases/latest

# Download and install the Tracer
RUN mkdir -p /opt/datadog \
    && mkdir -p /var/log/datadog \
    && TRACER_VERSION=$(curl -s https://api.github.com/repos/DataDog/dd-trace-dotnet/releases/latest | grep tag_name | cut -d '"' -f 4 | cut -c2-) \
    && curl -LO https://github.com/DataDog/dd-trace-dotnet/releases/download/v${TRACER_VERSION}/datadog-dotnet-apm_${TRACER_VERSION}_amd64.deb \
    && dpkg -i ./datadog-dotnet-apm_${TRACER_VERSION}_amd64.deb \
    && rm ./datadog-dotnet-apm_${TRACER_VERSION}_amd64.deb

# Enable the tracer
ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
ENV CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so
ENV DD_DOTNET_TRACER_HOME=/opt/datadog
ENV DD_INTEGRATIONS=/opt/datadog/integrations.json
```
Then you would need to run docker by setting `-e DD_LOGS_INJECTION=true` as well. 

Here are some more examples if need be: https://www.datadoghq.com/blog/asp-dotnet-core-monitoring/
And our public documentation for complete details: https://docs.datadoghq.com/tracing/setup_overview/setup/dotnet-core?tab=windows

**Comment by parraclaudio** [comment]
Thank you so much for your time @pierotibou
