### ISSUE TITLE
Mixing Datadog and OpenTelemetry doesn't work

### ISSUE THREAD

**Issue by verdie-g** [DataDog/dd-trace-dotnet#2938]
**Describe the bug**
When using the OpenTelemetry API through an ActivitySource with the `DD_TRACE_ACTIVITY_LISTENER_ENABLED` (as described [here](https://github.com/DataDog/dd-trace-dotnet/pull/2446)) and automatic instrumentation from the Datadog tracer, it seems like Datadog spans are not mixing with the OTEL spans.

**To Reproduce**
Could you confirm this is not a known issue before I work on a easy reproduction?

**Expected behavior**
I would expect datadog spans to be attached on the current activity.

**Screenshots**
![Datadog trace](https://user-images.githubusercontent.com/9092290/177004165-44dc2fd8-df22-4e10-abe9-d19b3bb7f750.png)
![OTEL trace](https://user-images.githubusercontent.com/9092290/177004205-fc93de67-b308-45d6-8ae9-526c60eb8cf6.png)
For one request, two traces are created. The first one is the Datadog one containing spans for the calling service (nginx.request), aspnet_core.request, aspnet_core_mvc.request, postgres.query. The second one is the OTEL one containing spans for Microsoft.AspNetCore.server, my manual span produced with StartActivity, and Npgsql.

**Runtime environment:**
- Instrumentation mode: automatic + manual OTEL
- Tracer version: 2.10.0
- OS: Debian GNU/Linux 10
- CLR: .NET 6.0

**Comment by pierotibou** [comment]
Hello @verdie-g,
This isn't a know issue. We haven't yet worked on official support of interactions with OTel, even though as you've seen we've started to work on it. Official support is something we'll work on this quarter. 
If you have a bit more details for reproduction, that would be helpful. We will look into all this in a few weeks when we start working on official support.
Thanks for reporting the issue

**Comment by verdie-g** [comment]
Ok looking forward for this :) I'll try working on a repro when I have some time.

**Comment by verdie-g** [comment]
After redeploying my service the issue is gone, so probably a misconfiguration on my part. Small difference though is I didn't set the `DD_TRACE_ACTIVITY_LISTENER_ENABLED` variable this time.

![image](https://user-images.githubusercontent.com/9092290/178098677-e2d7aadc-3f42-4e32-b69f-9c257be8f383.png)

For PostgreSQL I have two spans now. I guess one from OTEL and one from DD. Any way to disable the DD one?

**Comment by verdie-g** [comment]
I think it can be disabled using `DD_TRACE_Npgsql_ENABLED=false`.
