### ISSUE TITLE
Abnormal behavior with Datadog installed on our .NET IIS machines 

### ISSUE THREAD

**Issue by pianoman4873** [DataDog/dd-trace-dotnet#2993]
Hello , 
We are running .NET IIS servers on EC2 machines  ( running on Windows 2012 R2 ) in AWS  with DataDog installed ( Tracer version 2.11.0 ,  Agent version 7.37.1.1).
We were forced to reset the machines every 24 hours , as the performance ( latencies of the calls particularly ) was starting slowly to deteriorate until it was intolerable.
The things we noticed were that the frequencies and severities of  "GC pause time" increased over time, and that the latencies of the calls , and in particular of the Redis calls which are embedded in DataDog, increased.

As we couldn't find any clue to the solution while taking memory dumps and performing profiling, we did the following experiment - 

We removed DD from half of our servers ( let's denote those servers by groupA ), and left DD running on the other servers intact ( group B).
After that, we reset all the machines, and started comparing the latency of groupA vrs. groupB  via CloudWatch in AWS.

The results were unequivocal -  groupA's pefromance continued to behave with acceptable latency over time , but groupB's latency started to increase and peaked at about 7 times that of groupA about 24 hours later.
After resetting the machines in groupB, the latency decreased and converged to the latency of groupA , thus validating again that groupA was functioning properly.
This process was repeated for a couple of  days, thus further validating the hypothesis that DataDog is the culprit for the anomalous behavior.
We've been now running without DD in any machines for a couple of days and everything's OK -  no increases in latency are observed in CW.

**Comment by pierotibou** [comment]
Hello @pianoman4873, thanks for opening the issue. 
I have a few questions:
- Was this your first usage of the library, or were you upgrading from another version? 
- Would you happen to still have one of the memory dumps you took, one when the performances were impacted?
- If GC pause time and frequency was increasing over time, I assume memory usage was increasing, do you have data points on this?

**Comment by pianoman4873** [comment]
1. We upgraded from a version 2.7.0 which was also faulty.
2. I have some memory dumps left.
3. What do you mean exactly ? You want to see screenshots of DD metrics at these times ?

**Comment by pierotibou** [comment]
Thanks for this information. So yes if you have data or screenshots of the memory footprint over time, that could help narrow the issue down. And if you have means to share the dump files that would be great, if not I'll see on our end, I think we can setup a specific google drive for that IIRC.
Finally, can you share what version of .NET you are using on the server, the specs of your instance, if you use both custom and automatic instrumentation (and in which case if the versions were aligned).

**Comment by pianoman4873** [comment]
We wouldn't like to share the memory dumps - If you like ,we can set up a zoom session where I could share with you the results online.

We currently use .NET 5 on the servers, running on Windows 2012 R2.

No custom instrumentations.

Screenshots attached - You can see how the "GC pause time" starts to escalate at the right end of the timeline.
![image](https://user-images.githubusercontent.com/25153192/180167925-2c219a20-4819-412a-819a-48bd4eff005c.png)

**Comment by pierotibou** [comment]
Ok, so from what we see, the most plausible explanation would be spans that we leave open. In order to investigate, could you please open a ticket to our support sending them an email and linking this issue so that they can collect the most info (debug logs, ideally the dump if you'd accept to ... ). It will make the investigation/reproduction way easier.
Thanks in advance

**Comment by andrewlock** [comment]
Closing this as it's a year old, hope you got the help you need from support 🙂
