### ISSUE TITLE
Allow CDN logs to be connected to traces

### ISSUE THREAD

**Issue by mlstubblefield** [DataDog/dd-trace-dotnet#3017]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
This feature request is to support tying CDN requests (and their logs) to traces.

**Is your feature request related to a problem? Please describe.**
I feed my CDN logs to datadog and want to connect them to traces, but I can't.
This likely impacts anyone customers who use a CDN such as cloudflare or AWS cloudfront.

**Describe the solution you'd like**
- Cloudflare and other CDNs provide a request ID via a header. If I could at app initialization provide the name of that header to my app-- and have subsequent trace IDs either be that value, or be based upon that value some how, then in theory they could be tied together in the datadog web app.

**Describe alternatives you've considered**
- I tried doing something like this myself, but it appears that currently the datadog trace IDs have to be integers of a certain length-- perhaps it could be accomplished via some kind of special hashing mechanism.

**Comment by andrewlock** [comment]
Hi @mlstubblefield,

Thanks for the information and the request, I agree that makes a lot of sense. This feature is more related to the Cloudflare integration rather than the .NET Tracer, so would it be possible to please raise this as a feature request in a support ticket with [support@datadoghq.com](mailto:support@datadoghq.com) and reference this ticket? Thanks!

I'll close this issue for now, feel free to re-open if there's anything I've missed. Thanks!

**Comment by mlstubblefield** [comment]
I don't 100% agree with closing this as at the end of the day, there would need to be a change to the agent so that I could provide the ID or the request header that contains the ID to the datadog agent. That said, I did reach out to support to see if we can move the idea forward that way as well.

**Comment by andrewlock** [comment]
> I don't 100% agree with closing this as at the end of the day as there would need to be a change to the agent so that I could provide the ID or the request header that contains the ID to the datadog agent. That said, I did reach out to support to see if we can move the idea forward that way as well.

Hmmm, I was thinking about this feature differently. I was thinking it would be something like 
- update the existing Datadog Cloudflare integration to generate a datadog trace-id
- inject that into the logs
- inject the trace id into the request headers that are forwarded to your .NET app 
though I'm not 100% that's possible or would work yet 🤔 This wouldn't require any changes in the .NET tracer (or other tracer languages) and would essentially add distributed tracing to the cloudflare integration. This seems like a best-case to me.

If the cloudflare id was a w3c trace context (or similar) then it _may_ have been possible to rely directly on the cloudflare header, and to extract it from the header in the .NET tracer but as it isn't, and it doesn't include all the distributed trace info we would need, I don't _think_ that's possible.

I'll leave this closed for now as we have the support ticket to track the feature, so we'll follow through from that side. 

Thanks again!

**Comment by mlstubblefield** [comment]
@andrewlock - this kind of slipped through my hands, but yea since these cloudfront logs happen "before" everything else, I think we have to go with option #3 to correlate everything back.

As far as the ID, I'm not intimately familiar with how cloud**FRONT** generates them, but it looks to be some base64 string to me.

Apparently 
> The documentation says the requestId is. An encrypted string that uniquely identifies a viewer-to-CloudFront request.

Is there any way that I can participate in this issue/has there been any progress made on this feature?

**Comment by andrewlock** [comment]
Hi @mlstubblefield, as we're going with option 3, I don't think this is connected to the .NET tracer directly, so your best option is likely to follow through with the support ticket, as they should be able to route the request to the correct team (and I'm not currently sure who that would be right now!). It certainly a reasonable request, it's just tricky to see the best solution at the moment 🤔
