### ISSUE TITLE
ActivitySource feature does not allow for meaningful resource names

### ISSUE THREAD

**Issue by lukeemery** [DataDog/dd-trace-dotnet#3027]
**Describe the bug**
Resource name is always `{ActivitySource.Name}.{Activity.OperationName}`

**Expected behavior**
Allow for customization by using 

`{Activity.DisplayName} when {Activity.DisplayName} != {Activity.OperationName}`

Doing this would enable me to give more meaningful names, example being `POST testapi.orionadvisor.com/api/v1/security/token`

**Screenshots**
![image](https://user-images.githubusercontent.com/292830/181935616-7330f766-4557-47f1-8ce8-5289a0e37939.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: lambda extension
  - arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Extension:25
  - arn:aws:lambda:us-east-1:464622532012:layer:dd-trace-dotnet:5
- CLR: dotnet 6

**Additional context**

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by zacharycmontoya** [comment]
Hi @lukeemery, this should be addressed by PR https://github.com/DataDog/dd-trace-dotnet/pull/3556 . If you have additional feedback once this change is released, we'd be happy to hear it!

**Comment by lukeemery** [comment]
> Hi @lukeemery, this should be addressed by PR #3556 . If you have additional feedback once this change is released, we'd be happy to hear it!

This is wonderful.  I'm excited to try it out.

**Comment by lukeemery** [comment]
@zacharycmontoya I very much appreciate the work you've put into this so far, but I left some feedback on your commit.  
https://github.com/DataDog/dd-trace-dotnet/commit/42f6352640e030fbfc7a3529f2823f3616a138ad#r93821895

The changes you've made have a profound impact on my immediate goals and the guidance I am able to provide to my teams.

_Copy paste:_
___

The pattern I've adopted is to instantiate a static private in each class that I intend to instrument.
`private static readonly ActivitySource _activitySource = new(nameof(ToUpper));`

Then for every method I start a new activity.
`using var activity = _activitySource.StartActivity();`

The result looks something like:
![image](https://user-images.githubusercontent.com/292830/208944688-12f3ba87-77ca-480c-86c5-fbad70db2fff.png)

Doing it this way made it so that I didn't have an unmanaged static reference/dependency littered in code.  They are always contained and scoped to a particular class.  This seems to conflict with the guidance that OTEL 
provides in their docs, whereby they instruct us to declare a static that is used throughout your application.  [Microsoft makes a similar suggestion but immediately raises the same concern](https://learn.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs#best-practices-1) I'm trying to describe:

> Create the ActivitySource once, store it in a static variable and use that instance as long as needed. Each library or library subcomponent can (and often should) create its own source. Consider creating a new source rather than reusing an existing one if you anticipate app developers would appreciate being able to enable and disable the Activity telemetry in the sources independently.

But with these new changes I am now seeing new services being created for every ActivitySource I create.  They become disconnected and lose out on service-level grouping features.  Also, they clutter the DD ui and based on the pricing model likely increases our costs.

Before change:
![image](https://user-images.githubusercontent.com/292830/208947389-d7c3b81b-7467-4e6f-8b5b-69c6562d5531.png)

After change:
![image](https://user-images.githubusercontent.com/292830/208947530-d95bbb35-3947-43bb-b28e-224c773ac0c7.png)

#3027

**Comment by zacharycmontoya** [comment]
@lukeemery thank you for the feedback! I've created a PR to address this issue and revert the problematic ServiceName change. The PR is here if you'd like to look at it: https://github.com/DataDog/dd-trace-dotnet/pull/3663

**Comment by zacharycmontoya** [comment]
Hi @lukeemery , this has now been released in v2.22.0 of the Tracer. I hope this helps your use case. Thank you for the feedback you've provided and please let us know if you have any further feedback

**Comment by zacharycmontoya** [comment]
I'll close this for now, feel free to re-open or create a new issue if you have feedback
