### ISSUE TITLE
Instrument ASP.NET lifecycle events without requiring NuGet package

### ISSUE THREAD

**Issue by jyjohnson** [DataDog/dd-trace-dotnet#310]
Hi -- for asp.net integration running in IIS (web forms, mvc, web api, etc.) using automatic instrumentation, is the adding the nuget package to the solution/project optional or required? 

In other words, can we just install the regular DD agent and the APM agent (installed via MSI)?

Thanks.

**Comment by lucaspimentel** [comment]
Hey, @jyjohnson. For a .NET Framework application running in IIS, the NuGet packages are optional.

Adding `Datadog.Trace` gives you access to the `Tracer` class which you can use for manual instrumentation or to add custom tags to span created by automatic instrumentation.

Adding `Datadog.Trace.ClrProfiler.Managed` will load an `HttpModule` into your app which adds an additional root span for `ASP.NET` applications (e.g. MVC, Web Forms). Basically, it does the equivalent of using the `BeginRequest()` and `EndRequest()` events in `Global.asax` to measure the entire request.

We will update the docs to make this more clear.

**Comment by jyjohnson** [comment]
FYI -- we've spent a lot of time trying to get this to work on our legacy (but important!) production asp.net websites. The main site would not show up in APM (http-client, sql, and redis calls were showing). I copied the Datadog.Trace.ClrProfiler.Managed.dll (version 1.0) to the \bin folder and now the main site is showing up.

**Comment by geofflamrock** [comment]
@lucaspimentel do you have any update on this? We're facing the same issue as @jyjohnson where we can't get APM to work only installing the MSI, we have to add the nuget package, which we'd rather not do to our application.

**Comment by cailin-lai** [comment]
Yep, some legacy applications may be not able to repack.... Load assemblies from a certain path will be better than repackage / republish, specially, the .net core applications.

**Comment by lucaspimentel** [comment]
I'm going to re-purpose this issue as a feature request to instrument ASP.NET lifecycle events without the need for an `HttpModule` or the NuGet package.

**Comment by lucaspimentel** [comment]
Long-due update: since release 1.12.0 ([release notes](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.12.0)), we instrument ASP.NET requests automatically without needing manual configuration like adding a nuget package or editing the `web.config` file. Closing this issue.
