### ISSUE TITLE
Allow excluding of values in Redis commands

### ISSUE THREAD

**Issue by jonjomckay** [DataDog/dd-trace-dotnet#312]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
No, this is regarding an existing instrumentation.

**Is your feature request related to a problem? Please describe.**
We're trying to use the built-in instrumentation for ServiceStack.Redis, but it is tagging spans with the entire command (including the data we cache) and we'd like to exclude that data, as it'll be confidential in most cases. Also, it makes the traces pretty large as we're caching multi-MB values.

**Describe the solution you'd like**
It would be great to have the ability to exclude any sent values for `SET` commands, just keeping the command itself (e.g. `SET the:cache:key <excluded-value>`).

**Comment by macrogreg** [comment]
This functionality is better placed in the Agent, as it should be shared across all Redis Spans collected any language Tracer.
I have submitted an issue for the Agent team: https://github.com/DataDog/datadog-agent/issues/6596

I will be closing this issue for now. Please feel to re-open and add a comment if you have any new .NET specific information. 

Thank you!

**Comment by jonjomckay** [comment]
I'm not sure delegating this to the agent would really work for us - we're caching a a lot of large blobs of data (many thousands of sometimes up to 256Mi-sized), and both recording all that data and sending it to the agent for 99% of it to be removed seems like it'll negatively impact performance.

Having an option to just never record the values would be the best solution for us at least, as we have no interest in recording any of the actual stored values in Datadog, only the keys. It would also prevent any potential accidental sending of confidential data, as we literally cannot send this data to anywhere external due to compliance reasons.
