### ISSUE TITLE
Include the continuous profiler in the NuGet Package

### ISSUE THREAD

**Issue by mikesigs** [DataDog/dd-trace-dotnet#3122]
I am in the process of upgrading to the new NuGet based install of the Tracer, but just discovered that the Continous Profiler is only available if you install it the old-school way of installing the binaries. What is the timeline for including the new profiler in the `datadog` contentFiles of the NuGet package?

Thanks!

**Comment by mikesigs** [comment]
I actually found it. But the docs don't actually mention how to install it from the NuGet package and I was expecting it to be in `/app/datadog/continuousprofiler/Datadog.Linux.ApiWrapper.x64.so`, but it's actually in `/opt/datadog/linux-x64/Datadog.Linux.ApiWrapper.x64.so`.

**Comment by andrewlock** [comment]
Hi @mikesigs, sorry, we only shipped the continuous profiler in the latest version of the NuGet package, and the docs haven't been updated yet - we'll get them updated soon, glad you figured it out!
