### ISSUE TITLE
Linux duration span issue still happens with .Net Core HttpClient

### ISSUE THREAD

**Issue by chris-cummings** [DataDog/dd-trace-dotnet#313]
**Describe the bug**
The span duration issue with Linux that was outline in https://github.com/DataDog/dd-trace-dotnet/issues/293 appears to still be there when using HttpClient. Average duration on some service is 100 to 1000 times bigger in HttpClient when compared to duration of the service it is actually calling.

**To Reproduce**
Call an api from .Net Core on Linux using HttpClient with Datadog APM enabled.

**Expected behavior**
Durations in HttpClient should closely match the durations of the service they are calling.

**Screenshots**
Most of the HttpClient calls are calling other services in the list.
![image](https://user-images.githubusercontent.com/9394512/55754899-51841580-5a13-11e9-9947-020ef5cb2791.png)

**Runtime environment (please complete the following information):**
- Auto instrumentation, .Net Core Linux
- Tracer version: 1.0.0
- OS: Linux x64 (Debian
- CLR: .NET Core 2.0

Let me know if more information is required. Original fix in 0.8.2 worked great, figured you might have just missed a spot.

**Comment by chris-cummings** [comment]
Additional info: numbers appear to be right in the flame graph, but wrong in the services view.

**Comment by colin-higgins** [comment]
@chris-cummings Is this still an issue for you?

**Comment by macrogreg** [comment]
Hi @chris-cummings ,

We have not heard back in a while (@colin-higgins 's ping above). I will close the issue for now, but please feel free to re-open if you continue experiencing this issue. Thank you!
