### ISSUE TITLE
Wrong command line argument in dd-trace-dotnet/tools/GenerateIntegrationDefinitions/Properties/launchSettings.json

### ISSUE THREAD

**Issue by alonf** [DataDog/dd-trace-dotnet#318]
Replace:
 "commandLineArgs": "\"%UserProfile%\\source\\repos\\dd-trace-**csharp**\\integrations.json\""

with 

 "commandLineArgs": "\"%UserProfile%\\source\\repos\\dd-trace-**dotnet**\\integrations.json\""

**Comment by colin-higgins** [comment]
Thank you for the catch.
dd-trace-csharp was the original name of this repository and so the original paths were setup as such.

**Comment by colin-higgins** [comment]
Solved with https://github.com/DataDog/dd-trace-dotnet/pull/329
