### ISSUE TITLE
Ability to only log traces instead of sending them to the agent

### ISSUE THREAD

**Issue by breader124** [DataDog/dd-trace-dotnet#3203]
While working on enabling tracing for Java, I spotted option named `dd.writer.type`. After setting it to `LoggingWriter` instead of default `DDAgentWriter`, it allowed me to only log traces instead of sending them to DD agent, what was very handy for debugging. Is there any similar option or set of options available in `dd-trace-dotnet` to achieve the same?

If not, do you consider it useful feature, which I could implement here and contribute?
I'm aware of existence of `DD_TRACE_DEBUG` option in .NET tracer library, but as far as I know, it sends traces to agent. Maybe the way to go would be to modify this behaviour to log only?

**Comment by pierotibou** [comment]
Hello @breader124, we don't have that capability unfortunately. 

That said, would you mind giving more details around the scenarios you would like to cover here? What kind of debugging are you talking about (eg Local debugging? To debug a Datadog tracer issue? To avoid sending traces to your backend when debugging other issues?...)

Thanks

**Comment by breader124** [comment]
Sure. As you already said, I'm thinking mostly about local debugging of application with custom instrumentation. At the moment, only option to avoid sending the data to agent is to set `DD_TRACE_AGENT_URL` to point to not existing address or socket. However, it's not a perfect way as it causes logs pollution due to error messages and makes debugging more complex. I'd like to have an option to, as you wrote, log traces in the form they'd be sent to agent, but without making any attempts to establish connection with it. This way, after debugging session, when I'm sure everything works as it should, I could switch the state of tracer from debugging to normal and test e2e with real Datadog. Does it sound reasonable for you?

**Comment by seanamos** [comment]
This can also be useful in development to sanity check the traces (especially custom ones) without having to push up to a real environment where datadog agents are available.

**Comment by lucaspimentel** [comment]
Hello. We don't have any plans to add this at the moment, so I will close this ticket as stale.

**Comment by lucaspimentel** [comment]
If it helps, I use this fake trace agent for debugging. I send traces to it instead of the real agent, and I can optionally write them to a file for inspection.

Consider this a personal project and not at all supported by Datadog 😅 
https://github.com/lucaspimentel/MockTraceAgent

It is based on an older version of the mock trace agent that we use in this repository for testing purposes:
https://github.com/DataDog/dd-trace-dotnet/tree/master/tracer/tools/MockAgent
