### ISSUE TITLE
Excessive logging from Continuous Profiler

### ISSUE THREAD

**Issue by mikesigs** [DataDog/dd-trace-dotnet#3209]
**Describe the bug**
The log file `DD-DotNet-Profiler-Native-dotnet-1.log` is filled with millions of lines like the following:

```
[2022-09-12 20:24:35.909 | info | PId: 1 | TId: 17] The profile was sent. Success?true, Http code: 200
```

This kind of logging should be reserved for Debug level shouldn't it?

**Runtime environment:**
- Instrumentation mode: automatic with NuGet installer
- Tracer version: 2.14.0
- OS: Debian GNU/Linux 10 (buster)
- CLR: .NET Core 3.1

**Comment by chrisnas** [comment]
Thanks for the feedback @mikesigs.

> **Describe the bug** The log file `DD-DotNet-Profiler-Native-dotnet-1.log` is filled with millions of lines like the following:
> 
> ```
> [2022-09-12 20:24:35.909 | info | PId: 1 | TId: 17] The profile was sent. Success?true, Http code: 200
> ```
> 
> This kind of logging should be reserved for Debug level shouldn't it?

Only errors should be logged indeed.
This change has been added into our backlog
