### ISSUE TITLE
DD_APM_FILTER_TAGS_REJECT not filtering spans

### ISSUE THREAD

**Issue by mikesigs** [DataDog/dd-trace-dotnet#3210]
I am trying to filter out traces using the `DD_APM_FILTER_TAGS_REJECT` tag as described [here](https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/?tab=datadogyaml). But I cannot get it to work. No matter what, the traces still come through. 

I have configured the container (a k8s pod) with the environment variable: `DD_APM_FILTER_TAGS_REJECT=db.instance:NServiceBus.Transport`. Here's what a span looks like in DataDog.

![image](https://user-images.githubusercontent.com/811177/189763231-74dad657-4e49-47b0-9037-3e7cc7328e5d.png)

**Comment by pierotibou** [comment]
Hello @mikesigs, `DD_APM_FILTER_TAGS_REJECT` is an agent configuration knob. Can you confirm that you've applied it  to the agent container, not the app one ?

I've asked internally if there's anything else obvious. That said, as this is an agent setting, you should move this issue to the [datadog-agent](https://github.com/DataDog/datadog-agent) repo.

**Comment by mikesigs** [comment]
Oh, that would make sense then why it's not working! I will see about adding it to the agent config. Thank you!
