### ISSUE TITLE
Exception "The profiler is not connected or is not compiled as DEBUG ..." when run CallTargetNativeTest project on .NET6.0

### ISSUE THREAD

**Issue by InCerryGit** [DataDog/dd-trace-dotnet#3215]
**Describe the bug**

I tried to build dd-trace locally and the build went well, but the test project had problems.
When I run the CallTragetNativeTest project in. NET 6.0, an exception is thrown: Unhandled exception. System.Exception: The profiler is not connected or is not compiled as DEBUG with the DD_CTARGET_TESTMODE=True environment variable.

**To Reproduce**

1. I ran the build.ps1 file, located in the tracer directory, and built the following files. 
![image](https://user-images.githubusercontent.com/36690780/190043791-332810cc-776f-4c00-acb4-b52478779210.png)

2. Then I ran the CallTargetNativeTest test project. It worked normally in. NET461, but it threw an exception in. NET6.0.
![image](https://user-images.githubusercontent.com/36690780/190043963-9d74926a-89da-4f7f-a0f0-93dbcc782539.png)

**Expected behavior**
It should be able to run the test normally

**Runtime environment (please complete the following information):**
- Tracer version: I use the https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.14.0 
- OS: Windows11 22H2
- CLR: .NET 6.0
- Environment variables:
```json
{
  "profiles": {
    "CallTargetNativeTest": {
      "commandName": "Project",
      "commandLineArgs": "0",
      "environmentVariables": {
        "DD_CTARGET_TESTMODE": "True",
        "DD_DOTNET_TRACER_HOME": "$(SolutionDir)shared\\bin\\monitoring-home",
        "COR_ENABLE_PROFILING": "1",
        "CORECLR_ENABLE_PROFILING": "1",
        "COR_PROFILER_PATH": "$(SolutionDir)shared\\bin\\monitoring-home\\win-$(Platform)\\Datadog.Trace.ClrProfiler.Native.dll",
        "DD_DUMP_ILREWRITE_ENABLED": "1",
        "CORECLR_PROFILER": "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}",
        "CORECLR_PROFILER_PATH": "$(SolutionDir)shared\\bin\\monitoring-home\\win-$(Platform)\\Datadog.Trace.ClrProfiler.Native.dll",
        "DD_VERSION": "1.0.0",
        "DD_CLR_ENABLE_INLINING": "1",
        "COR_PROFILER": "{846F5F1C-F9AE-4B07-969E-05C26BC060D8}",
        "DD_TRACE_LOG_DIRECTORY": "E:\\DDLogs\\Source",
        "DD_TRACE_DEBUG": "1"
      },
      "nativeDebugging": true
    }
  }
}
```

**Logs**

[dotnet-tracer-loader-CallTargetNativeTest-23824.log](https://github.com/DataDog/dd-trace-dotnet/files/9562160/dotnet-tracer-loader-CallTargetNativeTest-23824.log)
[dotnet-native-loader-CallTargetNativeTest-23824.log](https://github.com/DataDog/dd-trace-dotnet/files/9562161/dotnet-native-loader-CallTargetNativeTest-23824.log)
[dotnet-tracer-managed-CallTargetNativeTest-20220914.log](https://github.com/DataDog/dd-trace-dotnet/files/9562162/dotnet-tracer-managed-CallTargetNativeTest-20220914.log)
[dotnet-tracer-native-CallTargetNativeTest-23824.log](https://github.com/DataDog/dd-trace-dotnet/files/9562163/dotnet-tracer-native-CallTargetNativeTest-23824.log)

**Comment by andrewlock** [comment]
Hi @InCerryGit, Sorry for the delay. Unfortunately our build/CI process is really quite complex atm; it's something we're actively looking at trying to improve.

As for your specific issue: the sample tests aren't all designed to be run "standalone", but rather as part of the integration tests. It's best to use the Nuke Targets to run these tests.

For example, to run all the native tests, you could use:

```powershell
# Build the tracer
.\tracer\build.ps1 BuildTracerHome
# Run the native unit tests
.\tracer\build.ps1 BuildAndRunNativeUnitTests
# Run the integration tests (CallTargetNativeTests only)
.\tracer\build.ps1 BuildAndRunWindowsIntegrationTests -SampleName CallTargetNativeTest -filter CallTargetNativeTests -framework net6.0 
```

Hope that helps! I'll close the issue for now, but feel free to reopen/open a new issue if you have any more questions
