### ISSUE TITLE
The first item from DD_TRACE_SERVICE_MAPPING is ignored by the tracer

### ISSUE THREAD

**Issue by nshakhat** [DataDog/dd-trace-dotnet#3278]
**Describe the bug**
Ad described in https://github.com/DataDog/dd-trace-dotnet/issues/1935, there is a need to re-map service names. For this purpose, the variable DD_TRACE_SERVICE_MAPPING was introduced. It does its job, but the first element of this dictionary is ignored, i.e. if the following configuration is applied:
        - name: DD_TRACE_SERVICE_MAPPING
          value: '{ redis:mailboxservice, mysql:mailboxservice,
            http-client:mailboxservice, aws-sqs:mailboxservice}'

mailboxservice-redis will not be renamed, but mailboxservice-mysql, mailboxservice-http-client and mailboxservice-aws-sqs - will.

The workaround is to use a dumb entry:

        - name: DD_TRACE_SERVICE_MAPPING
          value: '{ ignore_me:ignore_me, redis:mailboxservice, mysql:mailboxservice,
            http-client:mailboxservice, aws-sqs:mailboxservice}'

**To Reproduce**
1. add DD_TRACE_SERVICE_MAPPING into your application, which uses several libraries internally, e.g. mysql or redis
2. In APM traces you can see that your mapping is applied to all sub-services except the first in the dictionary 

**Expected behavior**
All sub-services listed in the dictionary are expected to be renamed

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Tracer version: Datadog.Monitoring.Distribution Version="2.14.0-beta01
- OS: Linux
- CLR: .NET Core 5.0

**Additional context**
k8s, Datadog is deployed with Helm

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by andrewlock** [comment]
Hi @nshakhat, the format for `DD_TRACE_SERVICE_MAPPING` is _not_ JSON. It is a simple comma separated `key:value`: https://docs.datadoghq.com/tracing/trace_collection/library_config/dotnet-core/#optional-configuration

So you should remove the `{}` characters, and hopefully that will fix it 🙂 e.g.

```yaml
 - name: DD_TRACE_SERVICE_MAPPING
   value: "redis:mailboxservice, mysql:mailboxservice, http-client:mailboxservice, aws-sqs:mailboxservice"
```

**Comment by nshakhat** [comment]
Thank you a lot, @andrewlock! Yes, it has solved the issue. I had problems understanding the official statement from the docs "it accepts a map of service name keys to rename". I hope that my question here will save others some time :)

**Comment by andrewlock** [comment]
Thanks for the feedback @nshakhat 🙂 I'll try to get the documentation updated to be clearer!
