### ISSUE TITLE
How to remove parent scope

### ISSUE THREAD

**Issue by goldenc** [DataDog/dd-trace-dotnet#3323]
Hi,
      Is it possible to clear an active scope before scheduling some code to run so that the scopes that are recorded when the code runs don't have a parent scope?

I'm using the dotnet client.

The problem is we inject a custom scope which gets completed but the polling code then keeps adding child scopes to this scope even though it has completed (they get added automatically, its not our code doing the linking). As the polling can last a long time the number of spans added grows to be too big a number and we can't view it correctly.

**Comment by andrewlock** [comment]
Closing this as no reply. If this didn't solve your problem, feel free to re-open or create a new issue. Thanks!
