### ISSUE TITLE
Tracer not sending container ID to agent when using containerd on Amazon Linux

### ISSUE THREAD

**Issue by jeid64** [DataDog/dd-trace-dotnet#3351]
**Describe the bug**
We see the Dotnet tracer not send a containerID to the Datadog agent when running on EKS 1.23 on nodegroups using Amazon Linux. The tracer attempts to lookup the containerID by looking at /proc/self/cgroup and trying to match this regex https://github.com/DataDog/dd-trace-dotnet/blob/master/tracer/src/Datadog.Trace/PlatformHelpers/ContainerMetadata.cs#L25 

Our /proc/self/cgroup looks like this
`11:blkio:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope
10:cpuset:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope
9:perf_event:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope
8:memory:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope
7:pids:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope
6:cpu,cpuacct:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope
5:net_cls,net_prio:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope
4:devices:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope
3:freezer:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope
2:hugetlb:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope
1:name=systemd:/kubepods.slice/kubepods-pod9508fe66_7675_4003_b7c9_d83e9f8f85e5.slice/cri-containerd-26cfbe35e08b24f053011af4ada23d8fcbf81f27f8331a94f56de5b677c903e4.scope`

Which does not match the regex. As a result, we our APM traces from dotnet are missing Kubernetes metadata that would be used when the agent receives a containerID from the tracer. We've verified that the Ruby tracer's regex works correctly (containerID is sent to agent) https://github.com/DataDog/dd-trace-rb/blob/f1a8956baa5c1f552c89f8a6c72cc04e075e5d5a/lib/datadog/core/environment/container.rb so we know nothing is wrong with our DD agent or infra. 

We've pulled out the C# code from the tracer here https://dotnetfiddle.net/B8SCqd that runs the code and you can see the regex is not a match. 

**To Reproduce**
Launch an EKS cluster with a managed nodegroup that uses Amazon Linux (which comes with containerd by default)
Run a dotnet pod on the cluster with the tracer installed
See if you get Kubernetes/container tags in APM from the dotnet pod. 
![dd-dotnet-broken](https://user-images.githubusercontent.com/1271427/195612867-c7ff7e0b-d79e-4392-843e-1166b1e64767.png)
This is what it looks like when containerID is not being sent by the tracer
**Expected behavior**
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/1271427/195613157-1a978fa7-ea83-4479-a4da-76c2e92cc8ae.png">
This is what our Ruby traces look like, which do send the containerID to the agent. 

**Runtime environment (please complete the following information):**
- Instrumentation mode: Manual with NuGET package
- Tracer version: 2.17.0
- OS: Amazon Linux 2
- CLR: .NET Core 3.1

**Additional context**

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by lucaspimentel** [comment]
@jeid64, thanks for reporting this issue and for the detailed description. @andrewlock identified the issue and prepared #3354. We expect it will be included in the next release of the library.

**Comment by jeid64** [comment]
Thanks! Do you know when the next release is scheduled once that PR is merged? Don't know what your cadence is.
