### ISSUE TITLE
AspNet integration creates spans that doesn't wrap any subspans

### ISSUE THREAD

**Issue by ksjoberg** [DataDog/dd-trace-dotnet#336]
**Description**
We are running the AdoNet integration and AspNet integration together. For WebForms requests, spans are created that span the duration of the execution of the page, but it does not cover any of the executed database queries performed as a part of that execution. However, spans are created separately that cover the database queries, but they are orphans (no origin page/span cover them).

**To Reproduce**
Create a AspNet WebForms solution and run it in an IIS Application Pool set to Integrated Mode.

**Expected behavior**
Any spans/SQL queries executed as a part of a AspNet WebForms request should appear as subspans.

**Screenshots**
![image](https://user-images.githubusercontent.com/1130611/57136770-1a084f00-6dae-11e9-99a0-04b3c9257948.png)

**Runtime environment:**
- Instrumentation mode: automatic with msi installer and AspNet integration using the NuGet package
- Tracer version: 1.0.0 (awaiting bug-fixed 1.1.0)
- OS: Windows Server 2016 version 1607
- CLR: .NET Framework 4.6.2

**Additional context**
This is probably due to AsyncLocal used incorrectly (in an AspNet WebForms context) to store the scope in the ScopeManager. The `ExecutionContext` doesn't flow between ASP.NET pipeline events, so in that scenario you could store the scope in `HttpContext.Items` instead. See https://github.com/aspnet/AspNetKatana/issues/31#issuecomment-285206180 and https://stackoverflow.com/questions/43391498/asynclocal-value-is-null-after-being-set-from-within-application-beginrequest/43500585#43500585

**Comment by ksjoberg** [comment]
Also see https://github.com/MiniProfiler/dotnet/issues/173

I'm able to reproduce this locally, but only if I access the local webserver through an IP-address/interface that is **not** 127.0.0.1/localhost, and when I `POST` a sizable amount of data. It seems to happen more frequently if the server is remote.

Here's an .aspx you can drop into a running application to verify: [CheckActiveScope.aspx](https://github.com/DataDog/dd-trace-dotnet/files/3165434/CheckActiveScope.aspx.txt)

Debugging this, I see that for one request, several different ASP.NET worker threads of the thread pool are involved in serving it, but if it by chance is served by the same thread as `OnBeginRequest`, the scope is available.

Locally and remotely, I'm frequently seeing the log message "Trying to close a null scope." which was emitted here if `current == null` in 1.0.0: https://github.com/DataDog/dd-trace-dotnet/blob/e0260b596cc6de9e37b08762ed4f9f54bed793e4/src/Datadog.Trace/AsyncLocalScopeManager.cs#L25

In our application which is mostly synchronous, it is an error condition if you are closing a `Scope` if there are no active `Scope`s. The argument in https://github.com/DataDog/dd-trace-dotnet/pull/325 is that "Web API can raise the `EndRequest` event on a different thread", but fact of the matter is that also `BeginRequest` can be raised on a thread different from the thread that executes the request and this applies not only to Web API but ASP.NET (not Core) on IIS in general.

**Comment by lucaspimentel** [comment]
Thanks for the detailed report, @ksjoberg! Definitely looks like an issue with the aspnet lifecycle events being called from different threads. We will look into this issue as soon as we can.

**Comment by lucaspimentel** [comment]
The changes in your PR #356 were included in [release 1.2](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.2.0) and should resolve this issue. Thanks again!
