### ISSUE TITLE
What  is the signature for wrapper type?

### ISSUE THREAD

**Issue by hemant-learningforever** [DataDog/dd-trace-dotnet#337]
Hi,
I see there is "signature" associated with every wrapper method. where is this coming from?
Can anyone please help?

Thanks,
Hemant.

**Comment by hemant-learningforever** [comment]
I want to add new type and not sure about this signature part.

**Comment by lucaspimentel** [comment]
@hemant-learningforever: Please note that the `integrations.json` file is an undocumented implementation details and may change in the future.

Having said that, we generate the json file using the tool in `/tools/GenerateIntegrationDefinitions`. The code that generates the signature is in [`GetMethodSignature(MethodInfo)`](https://github.com/DataDog/dd-trace-dotnet/blob/48628f0c8235977004f7f00500349150d4228173/tools/GenerateIntegrationDefinitions/Program.cs#L102).

See also section `I.8.6.1.5 Method signatures` of the [ECMA CLI spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf).

**Comment by hemant-learningforever** [comment]
@lucaspimentel  Thanks! this was useful.
