### ISSUE TITLE
Instrumenting filesystem classes

### ISSUE THREAD

**Issue by hemant-learningforever** [DataDog/dd-trace-dotnet#344]
Hi ,
I see that clrprofiler is prohibiting instrumenting .net framework classes.
Is there a plan to support filesystem classes? Or can someone guide me how to do this?

Thanks,
Hemant.

**Comment by lucaspimentel** [comment]
The .NET Tracer doesn't support instrumenting custom methods automatically (i.e. using the profiler) yet. You can use [manual instrumentation](https://docs.datadoghq.com/tracing/setup/dotnet#manual-instrumentation) for these scenarios.

**Comment by hemant-learningforever** [comment]
@lucaspimentel  I can write my own integration and achieve this. Is that correct?
