### ISSUE TITLE
.NET 7 support

### ISSUE THREAD

**Issue by vadimi** [DataDog/dd-trace-dotnet#3451]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
Hello, is there a plan to support the newly released .NET 7?

**Comment by Digiman** [comment]
It looks like the massive changes already merged as part of #3482.
So it means we have to wait new version/release of the agent.

Thanks

**Comment by andrewlock** [comment]
.NET 7 Support has now been released. Thanks!
