### ISSUE TITLE
StackExchange.Redis instrumentation library - destination server is always set to the first configured host

### ISSUE THREAD

**Issue by masteryee** [DataDog/dd-trace-dotnet#3518]
Problem: When multiple redis hosts are configured for C# apps that use StackExchange.Redis, the Datadog traces will ALWAYS show the first host listed in the configuration as the destination server. So if I configure "master", then "replica" in my C# app, and issue a GET command to "replica", the trace will show "master".

I believe it's related to the following line: https://github.com/DataDog/dd-trace-dotnet/blob/c9ddd978ce7f1e8ca77f4b96036a28a055d08a55/tracer/src/Datadog.Trace/ClrProfiler/AutoInstrumentation/Redis/StackExchange/StackExchangeRedisHelper.cs#L40

I also tested this with OpenTelemetry and its console exporter, and it is able to correctly distinguish the destination server. Here is the library: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Instrumentation.StackExchangeRedis. It takes advantage of the StackExchange.Redis Profiling feature.

**Comment by pierotibou** [comment]
Hello @masteryee, 
thanks for flagging this. The idea of taking advantage of the StackExchange.Redis Profiling feature is interesting. Quick question for this particular use case, could you share how both host and ports tags are represented in OTEL in that case? Are they using `peer.service` as [this code](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Instrumentation.StackExchangeRedis/Implementation/RedisProfilerEntryToActivityConverter.cs#L138) suggests?

**Comment by masteryee** [comment]
Hi @pierotibou,

We use the DNS endpoints in our configuration. Here is what was logged in my example (obfuscating anything private):
```
Activity.TraceId:          793e9f4c80e8da05eb03d5fb86fb3c3c
Activity.SpanId:           f9a0969c1bd7f03e
Activity.TraceFlags:           Recorded
Activity.ParentSpanId:    65278f8509e76a47
Activity.ActivitySourceName: OpenTelemetry.Instrumentation.StackExchangeRedis
Activity.DisplayName: GET
Activity.Kind:        Client
Activity.StartTime:   2022-11-28T23:35:41.9682382Z
Activity.Duration:    00:00:00.0922975
Activity.Tags:
    db.system: redis
    db.redis.flags: PreferReplica
    db.statement: GET <obfuscated key>
    net.peer.name: replica.<obfuscated host>.com
    net.peer.port: 6379
    db.redis.database_index: 0
   StatusCode : UNSET
Activity.Events:
    Enqueued [11/28/2022 11:35:41 PM +00:00]
    Sent [11/28/2022 11:35:41 PM +00:00]
    ResponseReceived [11/28/2022 11:35:42 PM +00:00]
Resource associated with Activity:
    service.name: <obfuscated service>
```
