### ISSUE TITLE
Disable integration span that doesn't have a parent span

### ISSUE THREAD

**Issue by bilby91** [DataDog/dd-trace-dotnet#3587]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name: SqlClient
- Library type: Datastore
- Library version: 2.20
- Environment: Azure App Services (using the extension)

**Is your feature request related to a problem? Please describe.**

We are using [Hangfire](https://docs.hangfire.io/) for background job processing in our ASP.NET web application. Hangfire deploys an independent thread pool in order to process jobs that periodically poll our SQL Server database for new jobs. The polling aspect is triggering tons of useless spans that generate noise and raise our implementation cost. 

We would like to know if it's possible to disable this behavior. 

**Describe the solution you'd like**
It would be great if we could disable a given integration (SQL Client in this case based on our understanding) when the span that it's getting created doesn't have a parent span (since the execution is not dependent on an incoming web request).

**Describe alternatives you've considered**
We haven't found an alternative solution so far. Completely disabling SQL Client would prevent us from capturing valuable data in the context of incoming web requests.

**Additional context**
Example span:
![Screenshot 2022-12-20 at 16 24 52](https://user-images.githubusercontent.com/2201079/208750821-4a050a41-a820-44b4-822d-62f07215a528.png)

**Comment by bilby91** [comment]
One possible workaround that we might have is to exclude SQL Client traces for a given database. Is that possible ?

**Comment by bilby91** [comment]
Looking at the `DD_TRACE_SAMPLING_RULES` configuration it doesn't seem to be possible to target an attribute of the span (db.instance) for example. It seems to only be possible to customize per span's service and name.

**Comment by bilby91** [comment]
Updated the description to indicate that we are running with Azure App Services (using the extension).

**Comment by andrewlock** [comment]
Hi @bilby91, 

The best option is probably to drop these resources using the `DD_APM_IGNORE_RESOURCES` or `DD_APM_FILTER_TAGS_REJECT` configuration keys. These let you drop spans based on span tags or resource names.  You can read more about it here: https://docs.datadoghq.com/tracing/guide/ignoring_apm_resources/

After adding the necessary environment variables in AAS, you will need to stop and start your application for the change to take effect.

Hopefully that resolves your issue!
Thanks
