### ISSUE TITLE
WCF client integration

### ISSUE THREAD

**Issue by EricStG** [DataDog/dd-trace-dotnet#360]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : System.ServiceModel 
- Library type: SOAP client
- Library version: 4.5.3

**Is your feature request related to a problem? Please describe.**
We noticed that tracing for WCF is enabled for the full framework, but disabled for Net Standard 2.0. It would be great of the support could be extended for Net Standard, or at least .Net Core.
Note that only WCF clients are supported through Net Standard, not services.

**Describe the solution you'd like**
We would like to be able to trace outgoing WCF client connections.

**Describe alternatives you've considered**
We're currently looking at manually tracing those events, but if the existing support could be extended, it would make our life that much easier.

**Additional context**

**Comment by colin-higgins** [comment]
Thank you for the request @EricStG 
I'll let you know when there is movement on this.

**Comment by macrogreg** [comment]
Hi @EricStG ,

Thank you for your submission and sorry about allowing it to be stale for such a long time.

As of now we only support WCF only via the HTTP transport. Other transport protocols (such as TCP) are currently not supported. If you use WCF over HTTP, your overall distributed trace will contain a client-side span representing the remote call, and a server-side span representing the local root of the respective WCF sub-operation. (Of course, it will also contain all the other spans involved in the overall distributed operation.) In that sense, both, client- and server-sides are covered. 

This functionality should allow you to trace both, client- and server-side activity for WCF (when used over HTTP).

In reference to this, I will go ahead and close the issue for now.
Please feel free to re-open it, if you disagree or if you have new information.

Thanks!
