### ISSUE TITLE
Differentiate between grpc streaming and unary RPCs

### ISSUE THREAD

**Issue by seanamos** [DataDog/dd-trace-dotnet#3682]
I'll reference https://github.com/DataDog/dd-trace-go/issues/521 which had a similar issue.

At the moment we have some long running grpc streams between services (1h). At the moment their metrics and latencies in the Datadog APM UI are heavily being skewed by this. For example, their P95 latency is shown as 59m50s which is obviously not correct.

**Comment by andrewlock** [comment]
Hi @seanamos, we already implement the solution described in that issue, by tagging `grpc.method.kind`, so I think you should be able to filter based on those as described in that issue?

**Comment by seanamos** [comment]
Ahh, I do see it has been added.

So this is more a "default" UI issue then. The service catalag etc. always includes the trace data from grpc streaming without any way to filter it out.

**Comment by andrewlock** [comment]
Ah, yes, that seems to be the case. I'll close this ticket for now as it's not related to the .NET tracer, but could you please open a support ticket with support@datadoghq.com about your UI suggestions, to ensure this feedback gets routed to the correct team? Thanks! 🙂
