### ISSUE TITLE
Unable to instrument generic handler method FunctionHandlerAsync

### ISSUE THREAD

**Issue by ianpowell2017** [DataDog/dd-trace-dotnet#3717]
**Describe the bug**
Does dd-trace-dotnet support the aws serverless.AspNetCoreWebApi template? (https://github.com/aws/aws-lambda-dotnet#dotnet-cli-templates)

When dd-trace is added to my ASP NET Core Web Api project, I see this error in our cloud watch logs

```
Impossible to get Serverless Definitions System.Exception: Unable to instrument generic handler method FunctionHandlerAsync declared on Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2[Amazon.Lambda.APIGatewayEvents.APIGatewayProxyRequest,Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse]\n   at Datadog.Trace.ClrProfiler.ServerlessInstrumentation.LambdaHandler..ctor(String handlerName) in /project/tracer/src/Datadog.Trace/ClrProfiler/ServerlessInstrumentation/LambdaHandler.cs:line 44\n   at Datadog.Trace.ClrProfiler.ServerlessInstrumentation.Serverless.GetServerlessDefinitions(String handlerName) in /project/tracer/src/Datadog.Trace/ClrProfiler/ServerlessInstrumentation/Serverless.cs:line 130
2023-01-25 16:37:35:259 Impossible to get Serverless Definitions System.Exception: Unable to instrument generic handler method FunctionHandlerAsync declared on Amazon.Lambda.AspNetCoreServer.AbstractAspNetCoreFunction`2[Amazon.Lambda.APIGatewayEvents.APIGatewayProxyRequest,Amazon.Lambda.APIGatewayEvents.APIGatewayProxyResponse]\n at Datadog.Trace.ClrProfiler.ServerlessInstrumentation.LambdaHandler..ctor(String handlerName) in /project/tracer/src/Datadog.Trace/ClrProfiler/ServerlessInstrumentation/LambdaHandler.cs:line 44\n at Datadog.Trace.ClrProfiler.ServerlessInstrumentation.Serverless.GetServerlessDefinitions(String handlerName) in /project/tracer/src/Datadog.Trace/ClrProfiler/ServerlessInstrumentation/Serverless.cs:line 130
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Create WebApi application using template designed by AWS (https://github.com/aws/aws-lambda-dotnet#dotnet-cli-templates)
2. Install dd-trace APM as per instructions (https://docs.datadoghq.com/serverless/installation/dotnet/?tab=containerimage)
3. Deploy the application
4. See errors in cloudwatch

**Expected behaviour**
Trace information to appear in DataDog dashboard

**Screenshots**
If applicable, could you add screenshots to help explain your problem?

**Runtime environment (please complete the following information):**
- AWS Lambda Linux X64
- Tracer version: v2.22.0

**Additional context**
This was reported on your slack channel more than 3 months ago.

![image](https://user-images.githubusercontent.com/30384636/215040967-5a165ddc-3582-4f34-b90a-238a34deee95.png)

**Comment by tianchu** [comment]
Our serverless team will prioritize this issue in the next sprint. Thanks for your valuable feedback!

**Comment by joeyzhao2018** [comment]
Currently [generic types/methods instrumentation is not supported](https://github.com/DataDog/dd-trace-dotnet/blob/master/tracer/src/Datadog.Trace/ClrProfiler/ServerlessInstrumentation/LambdaHandler.cs#L42-L45).
One workaround is to implement the `FunctionHandlerAsync` in the **LambdaEntryPoint** class. For example, 
```c#
    public override async Task<APIGatewayProxyResponse> FunctionHandlerAsync(APIGatewayProxyRequest request, ILambdaContext lambdaContext)
    {
        return await base.FunctionHandlerAsync(request, lambdaContext);
    }
```

**Comment by tianchu** [comment]
Just an no-op update, we are still trying to figure out the optimal solution here.
