### ISSUE TITLE
Setting Tags.ManualKeep to true not retaining traces?

### ISSUE THREAD

**Issue by turacma** [DataDog/dd-trace-dotnet#3743]
**Describe the bug**
We have 2 key paths on an API that we want to see 100% of traces for. 

We added the following to our code and it seemed to be working (we saw more/all of the traces for this methods):

```
// Prevent sampling on this path because we want to see all traces
Tracer.Instance.ActiveScope?.Span.SetTag(Tags.ManualKeep, "true");
```

However, while reviewing a customer bug report, I could find RUM resources (we use DataDog RUM SDK in our mobile app), but the resources had no associated APM traces. Do I need to set the sampling priority in the app instrumented with RUM or should I be able to set sampling priority on the backend?

**To Reproduce**
1. Add the `Tags.ManualKeep` to a span
2. Generate requests to endpoint with an app instrumented with RUM SDK
3. See that not all traces are visible in APM

**Expected behavior**
Setting this value in the backend should result in traces being kept

**Screenshots**
N/A

**Runtime environment (please complete the following information):**
- Mix of automatic and manual (using `DataDog.Trace.Bundle`
- Tracer version: 2.20.0
- OS: Ubuntu Linux 
- CLR: .Net Core 6

**Additional context**

We had the above code first and it seemed to be working, then we added RUM later, so wondering if there's an interaction here I'm not understanding. It's also possible that we were missing traces before RUM was integrated, we did not do an exhaustive verification.

**Comment by pierotibou** [comment]
Hello @turacma,

Actually, Datadog relies on head based sampling. So the sampling decision is taken at the root level. The root here being generated by RUM. This sampling decision is then propagated to the tracer. So this explains why the tag you are setting do not have the same effect anymore. 

I'm no expert of the RUM sdk, it seems the [documentation](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=datadog#how-are-apm-quotas-affected) points toward using the `traceSampleRate` initialization parameter, have you tried that way. 

Let me know if that answers your question.

**Comment by pierotibou** [comment]
Hello @turacma. So I've followed up internally:

There are 2 levels of sampling on the SDK side. Session and traces. `sessionSampleRate` is evaluated first. If a session is not sampled, no tracing headers will be added to any resource. Any session that is not sampled will not have any traces sampled for any of its resources.

Then, `traceSampleRate` is applied (it is set by default at 100%). So in the case this sampling is not at 100%, then you'll drop traces whatever you do on the backend side.

In the first case though, if the RUM SDK doesn't sample the session and do not send traces, then the request received on the backend side is de facto the root of the trace, so you should see those spans without a root generated by the SDK. 

Does that makes sense given your `sessionSampleRate` and `traceSampleRate` parameters? And does it match the behaviour you see?

**Comment by turacma** [comment]
@pierotibou Thanks for the update and clarifying, it at least makes sense to me that the behavior changed because the RUM client (aka our mobile app) started initiated the root trace rather than our frontend api gateway, but the explanation of the sampling rates doesn't seem to line up with what I'm seeing in practice.

I checked our mobile app code base and we currently have `sessionSampleRate` set to 100 (we want to maintain all sessions for now and we're low enough volume that keeping everything to debug issues is still feasible). We don't have `traceSampleRate` set, but if this was in fact set to 100% by default, I would have expected all resources associated with those sessions to be retained, but that doesn't seem to be the case.

I'll work with our team that maintains the app to tune the the trace sampling configuration and only keep 100 of the operations we're focused on for right now, but if you could validate if there's some condition that might change the default of `traceSamplingRate` if `sessionSamplingRate` is 100%, that'd close the loop for me.

**Comment by yannickadam** [comment]
Hi @turacma, 
You're mentioning a mobile app, but you are using the RUM browser SDK correct? Just to be sure we have all the proper elements.

Regarding sample rates, the following process is applied:

- Check that the session (through `sessionSampleRate`) is being tracked.
- Check that the resource is targeting an allowed URL (through `allowedTracingUrls`)
If both conditions are met, tracing headers will be added to the network request. If not, no headers are added and the RUM SDK should not affect your backend tracing.

Then - if `traceSampleRate` is provided, a draw will be performed. The header `x-datadog-sampling-priority` will be set to 1 if the draw is successful, else 0. 

Nothing else should interfere in the sampling decision. If you observe a different behaviour from the browser SDK, please open an issue in the [browser-sdk repository](https://github.com/DataDog/browser-sdk).

**Comment by pierotibou** [comment]
@turacma. I'm closing this issue for now as I don't believe it's directly related to dd-trace-dotnet. Don't hesitate to reopen it or open a new one in the browser-sdk-repository if need be.
