### ISSUE TITLE
musl-arm64 support

### ISSUE THREAD

**Issue by Discolai** [DataDog/dd-trace-dotnet#3850]
I am testing out running some existing workloads on arm64. They are currently using the `6.0-alpine` [dotnet docker image](https://hub.docker.com/_/microsoft-dotnet-runtime/), but I want to transition to `6.0-alpine-arm64v8`.

Your release page includes downloads for both `musl` and `arm64`, but nothing for `musl-arm64`. Do you plan to support this or do I have to run another docker image such as `6.0-bullseye-slim-arm64v8` together with your `arm64` release?

**Comment by seanamos** [comment]
This was the same issue I run into here: https://github.com/DataDog/dd-trace-dotnet/issues/3218

**Comment by andrewlock** [comment]
FYI, this has been released in v3.2.0: https://github.com/DataDog/dd-trace-dotnet/releases/tag/v3.2.0
