### ISSUE TITLE
Activity tracing causing internal server errors with legacy trace headers

### ISSUE THREAD

**Issue by wigmorewelsh** [DataDog/dd-trace-dotnet#3857]
**Describe the bug**
A NullReferenceException thrown from inside the datadog tracer causes an aspnet core request to fail with an internal server error. This is happening when activity tracing is enabled and the application recieves a http request with a legacy trace headers (request-id). Works without issues for requests that use w3c/opentelemetry headers.

**To Reproduce**
1. Enable activity tracing DD_TRACE_ACTIVITY_LISTENER_ENABLED=1
2. Run an aspnet application
3. Send a request to the application that uses the legacy request-id http header 
4. Get an Internal Server Error

**Expected behavior**
The aspnet core application should return

**Screenshots**
Stacktrace of error
![image](https://user-images.githubusercontent.com/11813/222469808-2193988b-3d38-43fb-bc77-b8a7794fea78.png)
NullReferenceException from a memory dump captured
![image](https://user-images.githubusercontent.com/11813/222457848-f6faff5e-5493-40d2-83af-f8a6694c2ec4.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: datadog-dotnet-apm added to the docker image and DataDog.Trace nuget package installed in the application
- Tracer version: 2.23, 2.24 and 2.24.1
- OS: linux docker container
- CLR: dotnet 7.0.0, aspnet core 7.0

**Additional context**
Memory Dump avaliable

**Comment by bouwkast** [comment]
Thanks for reporting this and providing the stacktrace of the error. We're able to see what is causing this and we'll get a fix for it here https://github.com/DataDog/dd-trace-dotnet/pull/3870.

Will update again when this is merged and released.

Thanks!

**Comment by pierotibou** [comment]
This has just been released as part of [2.27.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.27.0)
