### ISSUE TITLE
ToListAsync() hangs

### ISSUE THREAD

**Issue by jyjohnson** [DataDog/dd-trace-dotnet#391]
**Describe the bug**
ASP.net WebAPI project running on IIS 8.5 (Win2012 R2). Just installing the APM breaks a method that uses "**.ToListAsync()**". 

**Runtime environment (please complete the following information):**
- automatic with msi installer
- Tracer version: we've had this issue from 0.8 - 1.3
- OS: Win2012 R2
- CLR:  .NET Framework 4.5.2, and 4.7

**Additional context**
I've opened a support case on this (#229062) but posting here in case it is helpful.

**Comment by lucaspimentel** [comment]
@jyjohnson: What's the underlying `IQueryable`? Is it Entity Framework (EF6 or EF Core), or something else? Is `ToListAsync()` called from an async Web API endpoint or a synchronous one?

A minimal project that reproduces the issue or even a small code sample would be very helpful. Thanks!

**Comment by jyjohnson** [comment]
Hi -- here are some snips from one of our developers:
`
//following code works.
public async Task<IEnumerable<SiteSetting>> GetSiteSettings1(string custID, string name)
{ 
	var id = Convert.ToInt64(custID); var siteSettings = context.SiteSettings.Where(x => (x.CustID == id && x.sName == name)).ToList();
	return await Task.FromResult(siteSettings); 
}

//following code does not works.
public async Task<IEnumerable<SiteSetting>> GetSiteSettings1(string custID, string name)
{ 
	var id = Convert.ToInt64(custID); 
	return await context.SiteSettings.Where(x => (x.CustID == id && x.sName == name)).ToListAsync(); 
}

//following code works.
public async Task<IEnumerable<SiteSetting>> GetSiteSettings1(string custID, string name)
{
    using (var conn = context.Database.Connection)
    using (var cmd = conn.CreateCommand())
    {
        cmd.CommandType = CommandType.Text;
        cmd.CommandTimeout = 60;
        cmd.CommandText = "Select * from SiteSettings where CustID=" + custID + " and sName='" + name + "'";
        cmd.Connection.Open();
        List<SiteSetting> siteSettings = new List<SiteSetting>();
        using (var reader = cmd.ExecuteReader())
        {
            while (reader.Read())
            { SiteSetting st = new SiteSetting(); st.SettingID = reader.GetInt32(reader.GetOrdinal("SettingID")); st.CustID = reader.GetInt32(reader.GetOrdinal("CustID")); st.sType = reader.GetInt32(reader.GetOrdinal("sType")); st.sName = reader.GetString(reader.GetOrdinal("sName")); st.sValue = reader.GetString(reader.GetOrdinal("sValue")); st.ActID = reader.GetInt32(reader.GetOrdinal("ActID")); siteSettings.Add(st); }
            return await Task.FromResult(siteSettings);
        }
    }
}

//following code does not works
private async Task<IEnumerable<TEntity>> GetEntityList<TEntity, TKey>(Expression<Func<TEntity, bool>> predicate, Expression<Func<TEntity, TKey>> sortBy) where TEntity : class
{ 
	return await context.Set<TEntity>().Where(predicate).OrderBy(sortBy).ToListAsync(); 
}

//following code works.
public async Task<IEnumerable<SiteSetting>> GetSiteSettings1(Expression<Func<SiteSetting, bool>> predicate)
{ 	var result = context.Set<SiteSetting>().Where(predicate).OrderBy(x => x.sName).ToList(); 
	return await Task.FromResult(result);
}

**Comment by ameybhatkar123** [comment]
> @jyjohnson: What's the underlying IQueryable? Is it Entity Framework (EF6 or EF Core), or something else? Is ToListAsync() called from an async Web API endpoint or a synchronous one?
> A minimal project that reproduces the issue or even a small code sample would be very helpful. Thanks!

   return await context.Set<TEntity>()
                .Where(predicate)
                .OrderBy(sortBy)
                .ToListAsync();
This call is failing. It use Entity framework 6.1.3 and tearget Framweork is 4.5. Yes, ToListAsync() called from an async Web API endpoint. (aync and await keyword use.)

**Comment by jyjohnson** [comment]
Hi - any update on this?

**Comment by jyjohnson** [comment]
I think v1.4 fixed this. I'm confirming with our dev team to see if they made any code changes.

**Comment by jyjohnson** [comment]
Actually, we still have this issue. Previously I thought it was fixed but if restart IIS or reboot, the webapi call still hangs. I have to uninstall the APM to get the web services running. Note: I updated to v1.4.1 (same issue).  With automatic instrumentation I can't enabled additional logging, right? Anything else I could do to t-shoot this?

**Comment by colin-higgins** [comment]
Hey @jyjohnson 
Just to update you, we are looking into this and will get back to you as soon as we have news.

**Comment by jyjohnson** [comment]
Any update?

**Comment by lucaspimentel** [comment]
@jyjohnson and @ameybhatkar123: We've tried very hard to reproduce this issue without any success. Are you able to provide a minimal project that hangs this way?

**Comment by lucaspimentel** [comment]
Closing this stale issue since we can't reproduce.
