### ISSUE TITLE
Instrument AWS SNS / SQS

### ISSUE THREAD

**Issue by btpemercier** [DataDog/dd-trace-dotnet#4007]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : `AWSSDK.SimpleNotificationService`
- Library type: `SDK Net Core`
- Library version: 3.x

**Is your feature request related to a problem? Please describe.**
We want to add SNS / SQS observability in the APM

**Describe the solution you'd like**
Use the auto instrumentation to push attributes during the publish / subscribe process between SNS/SQS to produce SPAN in APM

**Additional context**
Today SNS cannot have more than 10 attributes if raw mode is enabled

**Comment by andrewlock** [comment]
Hi @btpemercier, FYI we already have support for SQS as noted [here](https://docs.datadoghq.com/tracing/trace_collection/compatibility/dotnet-core/#integrations). We don't yet have support for SNS

**Comment by btpemercier** [comment]
Hi @andrewlock that's true but we need the link between SNS and SQS :)

**Comment by lucaspimentel** [comment]
Related: https://github.com/DataDog/dd-trace-dotnet/pull/4084
