### ISSUE TITLE
sha256/sha512 checksum file together with the releases?

### ISSUE THREAD

**Issue by marcos-rezende-ambevtech** [DataDog/dd-trace-dotnet#4032]
What is the possibility of delivering the sha256/sha512 checksum file together with the releases?

**Comment by anderson-fachini** [comment]
I have the same need. Microsoft, for example, offers a file with all checksums per release (https://dotnetcli.blob.core.windows.net/dotnet/checksums/7.0.5-sha.txt)

**Comment by andrewlock** [comment]
This is a good idea, thanks 👍 created a PR so the next release should have it. Thanks!
