### ISSUE TITLE
BadImageFormatException Using Datadog.Trace 2.28.0 In Nuget Packages

### ISSUE THREAD

**Issue by albernhagen** [DataDog/dd-trace-dotnet#4035]
**Describe the bug**
Using the 2.28.0 release of Datadog.Trace in our private nuget packages is resulting in `BadImageFormatException` in those libraries.  Our web services don't reference Datadog.Trace but instead rely on the version in those libraries to keep it consistent.  We also use the amd64 package within our containers hosted in Kubernetes in AKS.

**To Reproduce**  
1. Upgrade to 2.28.0
2. Use trace annotations
3. Get an error like `The signature is incorrect. The format of the file '/app/MyCompany.Libraries.Core.dll' is invalid.` in the first method that has a `Trace` annotation on it.

**Expected behavior**
No errors.

**Runtime environment (please complete the following information):**
- Instrumentation mode: NuGet package for apps, tracer in the container installed from: https://github.com/DataDog/dd-trace-dotnet/releases/download/v2.28.0/datadog-dotnet-apm_2.28.0_amd64.deb
- Tracer version: 2.28.0
- OS: Bullseye Slim from https://hub.docker.com/_/microsoft-dotnet-runtime/
- CLR: .NET Core 7

**Comment by pierotibou** [comment]
Hello @albernhagen, thanks for reporting this issue. 

I tried to reproduce locally and didn't manage to. Could you maybe share a redacted version of your image?

On my end, I've tried running an app that refers to `Datadog.Trace.Annotations`, has automatic instrumentation setup through the container the `2.28.0` amd64 package, on a bullseye-slim-amd64. So it seems quite close to your setup but maybe I'm missing something.

**Comment by albernhagen** [comment]
Hello @pierotibou -- I played around with this a bit more last night and I made 2 changes that seemed to resolve this, at least based on an initial test:

- I downgraded some .NET libraries from 7.0.5 to 7.0.4 that had gone out with the original change.
- I removed `ENV DD_TRACE_DEBUG=true` from our dockerfile.

I don't know exactly which one of these solved the problem.  We had a big release today so I won't be able to test more until next week most likely, so I'll try and pinpoint what particular piece seems to have caused the problem.

**Comment by pierotibou** [comment]
Great thanks for letting me know. There's really small chances that `ENV DD_TRACE_DEBUG=true` will change anything. (BTW, better not to put it in prod unless you're investigating some things obviously). Keep us posted then.

**Comment by albernhagen** [comment]
@pierotibou I was able to confirm that `ENV DD_TRACE_DEBUG=true` caused the issue.  We don't need it and it was leftover from some other setup, so I will be good to go with removing it.  I imagine you'll want to close this, but I'll defer to you.  Thanks for the help!

**Comment by pierotibou** [comment]
Thanks a lot for the extra details @albernhagen. Indeed I can now reproduce it. 
I'll leave this open while we look into it.

**Comment by zacharycmontoya** [comment]
We've just released [v2.29.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.29.0) of the .NET Tracer to fix this issue, thanks for reporting this @albernhagen !
