### ISSUE TITLE
Are Activity trace IDs and Datadog trace_id's supposed to be in sync?

### ISSUE THREAD

**Issue by IGx89** [DataDog/dd-trace-dotnet#4126]
Hello! I'm a bit new to Datadog, coming from an Application Insights background. When using Application Insights, calling System.Diagnostics.Activity.Current.Id in our code would return the current trace ID (equaling the trace ID sent in w3c traceparent request headers) and we could easily copy/paste that trace ID into AI's UI to look up all the logs, requests, etc. associated with that trace.

When using Datadog, Activity.Current.Id also matches the trace ID sent in w3c traceparent headers, however the Datadog trace_id is completely different and I'm not able to search for traces in Datadog using the former trace ID. Are those supposed to be in sync, or are my expectations wrong? I found DD_TRACE_OTEL_ENABLED and DD_TRACE_ACTIVITY_LISTENER_ENABLED and tried setting both to true, to no avail. Using automatic instrumentation and the latest agent version (2.30).

If this is supposed to work, let me know and I'll provide more information about my environment. Appreciate your help!

We occasionally present the value of Activity.Current.Id to the user as an error code, so that if they call tech support they can provide the error code and allow devs to easily look up what happened.

**Comment by lucaspimentel** [comment]
Hello, IG. `DD_TRACE_OTEL_ENABLED` is the correct setting to enable interoperability with .NET's `Activity` type and OpenTelemetry. (`DD_TRACE_ACTIVITY_LISTENER_ENABLED` is an older, deprecated name for the same setting.) Note that automatic instrumentation (which you are using) is also required for this feature to work.

> If this is supposed to work, let me know and...

Yes, we support Activities (if enabled). We also just added additional support for 128-bit trace ids in release 2.30, so it would be interesting to see if you observed any differences between 2.29 and 2.30.

> I'll provide more information about my environment.

Yes, please! You can also open a support ticket at https://help.datadoghq.com/hc/en-us/requests/new (please reference this github issue) if there's any information you can't share publicly. Thanks!

**Comment by IGx89** [comment]
Thanks @lucaspimentel! I was able to reproduce the issue pretty easily in your WindowsContainer example -- you can see my changes here: https://github.com/IGx89/dd-trace-dotnet/tree/issue-4126.

Here's what it looks like when run (I'm passing a traceparent header too, but not necessary to reproduce):

![image](https://github.com/DataDog/dd-trace-dotnet/assets/282698/51077b55-9a3a-429a-80de-7058dee9a526)

Based on what I've read and you've said, I'd expect that the trace and span IDs in Activity ID would match DD Trace ID/Span ID. That's not the case. Am I missing something?

**Comment by IGx89** [comment]
It looks like they do match, it's just hidden since DD Trace ID is just the right half converted from hex to decimal (11037627272996883860 = 0x992d878662248d94). It took me a bit to hunt down a way to get the 128b trace ID, but finally discovered that Span's ToString includes it:

![image](https://github.com/DataDog/dd-trace-dotnet/assets/282698/b1aff81f-d35f-45d6-b38d-4938b21aff32)

Some further observations:
1. Turning on/off DD_TRACE_OTEL_ENABLED doesn't seem to change anything, at least that I can see. Seems like it's on by default.
2. The trace ID in the UI is still the 64 bit version. I need to be able to search by the 128 bit, hex version (what's in the traceparent header and Activity.Id). Is there a way to do that, or is a way planned? Or will we always have to cut it in half and convert to decimal before being able to search in the UI?
3. This is a real odd one. If I pass a traceparent header when calling my k8s container, the trace never shows up in the UI. Any logs created during the request are there, but they have no trace. It's like the request never happened according to Traces. That's concerning! Any thoughts at what could be causing that behavior? I'll probably submit a support ticket, this is potentially a big issue.

**Comment by lucaspimentel** [comment]
> DD Trace ID is just the right half converted from hex to decimal (11037627272996883860 = 0x992d878662248d94)

Ah, yes! A little history first. Datadog trace ids and span ids have always been unsigned 64-bit values (`ulong` in C#). These ids are displayed as decimal strings when needed, like `11037627272996883860` in your example. Datadog APM is currently migrating to 128-bit trace ids (displayed as hexadecimal strings) to improve interoperability with industry standards (e.g. OpenTelemetry).

As of version 2.30, the .NET tracer internally supports 128-bit ids like the ones found in propagation headers like W3C's `traceparent` and in Activities. However, not all the moving parts are in place yet to show 128-bit ids in the Datadog UI. Even in the tracer libraries, we keep using the lower-order 64 bits in several places for backwards compatibility, such as the `x-datadog-trace-id` propagation header (we propagate the upper 64 bits in a separate tag). In the .NET Tracer specifically, the `ISpan.TraceId` property is a `ulong`, so it still returns only the lower 64 bits of a 128-bit id. Changing this property's type is a breaking change, so we're holding off on that or now.

> The trace ID in the UI is still the 64 bit version. I need to be able to search by the 128 bit, hex version (what's in the traceparent header and Activity.Id). Is there a way to do that, or is a way planned?

This is being worked on as we speak! I don't have a specific timeline, but I would expect this to be available soon.

> the trace never shows up in the UI... I'll probably submit a support ticket

Yes, a support ticket is the best course of action for this item. Thank you.

**Comment by Harlonxl** [comment]
Hello, @lucaspimentel. We also encountered the same problem, when will it be fixed. Thank you.

**Comment by IGx89** [comment]
> > The trace ID in the UI is still the 64 bit version. I need to be able to search by the 128 bit, hex version (what's in the traceparent header and Activity.Id). Is there a way to do that, or is a way planned?

> This is being worked on as we speak! I don't have a specific timeline, but I would expect this to be available soon.

Hi @lucaspimentel! Any updates on that functionality? Looks like it's not available yet, at least where I've looked so far.

**Comment by zacharycmontoya** [comment]
Hi folks, apologies for not updating this sooner, but all functionalities discussed here are fully supported now:
- The Datadog tracer will listen to Activities when `DD_TRACE_OTEL_ENABLED=true`. This opt-in flag was shipped in the [v2.22.0 release](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.22.0) in December 2022
- The Datadog tracer understands and propagates the W3C trace context headers, starting in the [v2.22.0 release](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.22.0) in December 2022
- The Datadog tracer generates 128-bit trace-id's by default (regardless if there was an incoming traceparent), starting in the [v2.42.0 release](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.42.0) (November 2023)
- Outside of this repository, the Datadog UI allows you to search by Datadog trace-id (64-bit decimal) or W3C trace-id (128-bit hexadecimal) starting in November 2023

If you're still seeing any issues or missing functionalities, please let us know!

**Comment by IGx89** [comment]
Thanks for following up! Following your instructions with the latest tracer was successful for me ❤️

ASP.NET Core 8 ProblemDetails response body's traceId field: 00-1b2465ee7591393b5bd1638317cff936-c2574d1a8b0cbd67-00
Trace link in Datadog: https://app.datadoghq.com/apm/trace/1b2465ee7591393b5bd1638317cff936
