### ISSUE TITLE
Direct log submission uses "@x" for exceptions which isn't supported by Datadog

### ISSUE THREAD

**Issue by Hawxy** [DataDog/dd-trace-dotnet#4130]
Unlike the rest of the direct logging fields, the C# log pipeline in Datadog is not setup to process `@x` as an exception source by default:

https://github.com/DataDog/dd-trace-dotnet/blob/58845f6fde4a7b195d99e893fc4a0ca2e6940dcf/tracer/src/Datadog.Trace/Logging/DirectSubmission/Formatting/LogFormatter.cs#L242

![image](https://user-images.githubusercontent.com/975824/236976955-0a53c649-5a21-4529-b161-f521277caa13.png)

This results in none of the log-based error tracking, parsing or monitoring working whilst using direct submission.

**Comment by andrewlock** [comment]
Thanks for pointing that out @Hawxy, sorry about that. I'm reaching out to teams internally to get this fixed, and will let you know once it is!

**Comment by andrewlock** [comment]
Hi @Hawxy, this issue should be fixed now, so exceptions sent via direct submission should be processed correctly. Thanks for flagging it, and sorry for the delay!
