### ISSUE TITLE
Datadog.Trace.Annotations doesn't seem to work with AWS Lambda functions

### ISSUE THREAD

**Issue by ganhammar** [DataDog/dd-trace-dotnet#4171]
**Describe the bug**
We're using the `Datadog.Trace.Annotations`-package to trace a method called by the lambda handler, but, the traces never seems to show up in Datadog. Using the `Datadog.Trace`-package works as expected.

**To Reproduce**

```csharp
[Trace(OperationName = "example.do-heavy-thinking", ResourceName = "Example.Think")] // This trace never shows up
private async Task Think()
{
  using (var scope = Tracer.Instance.StartActive("example.do-heavy-thinking-in-scope")) // This trace does
  {
    scope.Span.ResourceName = "Example.ThinkInScope";
    var random = new Random();
    var thinkingTime = random.Next(50, 1000);

    scope.Span.SetTag("thinking.time", $"{thinkingTime}ms");

    Logger.LogInformation($"Need to think for {thinkingTime}ms");

    await Task.Delay(thinkingTime);
  }
}
```

The source code for the project can be found [here](https://github.com/polestar/dotnet-datadog) and the function where the method above is invoked [here](https://github.com/polestar/dotnet-datadog/blob/main/src/Example/Function.cs).

**Expected behavior**
That both traces in the above example would be sent to Datadog.

**Screenshots**
<img width="523" alt="Screenshot 2023-05-23 at 13 39 56" src="https://github.com/DataDog/dd-trace-dotnet/assets/3415645/34c52eb2-29b7-4941-a25c-3695aca5efb6">
(All traces visible in Datadog)

**Runtime environment (please complete the following information):**
- Instrumentation mode: Automatic (through Serverless Framework plugin)
- Tracer version: 2.30.0 (1.0.0 for Annotations package)
- OS: Amazon Linux 2 (arm64) 
- CLR: .NET Core 6.0

**Additional context**
The infrastructure is deployed using Serverless Framework and the `serverless-plugin-datadog` is used to instrument the Lambda. Using the default values for the configuration of the plugin.

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by joeyzhao2018** [comment]
Hi @ganhammar , thank you for raising this issue. To clarify, dd-trace-dotnet layer v7 is actually using dd-trace-dotnet= 2.22.0. We just released dd-trace-dotnet layer and dd-trace-dotnet-ARM layer version 8 yesterday, which uses dd-trace-dotnet=2.31.0. Do you mind trying testing it with version 8 layers? And for ARM please use dd-trace-dotnet-ARM layer. Thank you.

**Comment by ganhammar** [comment]
Well, we're deploying the layers through Serverless framework, where we are at the latest version, and yes, for arm64 we're using the arm version. Which is also set up through the Serverless plugin.

**Comment by hghotra** [comment]
@ganhammar thank you for raising this issue. This is an issue with the plugin not being up to date - we'll cut a new release tomorrow that should have the new version for the tracer as well as the ARM layers which seem to be missing.

**Comment by joeyzhao2018** [comment]
Hi @ganhammar, I have deployed and tested using the code your provided. I believe they work in both example and Example2. Thank you again for providing a clean example. I really appreciate it.
<img width="1135" alt="Screenshot 2023-06-01 at 10 59 54 PM" src="https://github.com/DataDog/dd-trace-dotnet/assets/5253430/94bbd7f7-9c83-4e2e-93c3-a7ea85153be3">
<img width="1122" alt="Screenshot 2023-06-01 at 11 05 05 PM" src="https://github.com/DataDog/dd-trace-dotnet/assets/5253430/48447834-b1c2-4402-9f4f-72a55b7fd5a7">

As @hghotra has pointed out, there's some delay between the layer release and the serverless framework plugin release this time. I'll try to update the plugin tomorrow and update here once done.
Meanwhile, if you want to manually fix it. The working layer should be : `arn:aws:lambda:<AWS-REGION>:464622532012:layer:dd-trace-dotnet-ARM:8` Note that its `dd-trace-dotnet-ARM` and the version is 8.

**Comment by ganhammar** [comment]
@joeyzhao2018 Thanks for deploying and testing the example! Great to see that it works for you, I'll do some cleanup and retry the deployment with the latest version of the layers.

But, looking at the print screens you provided, there is a difference between the functions, the Example function gets the outer `aws.lambda` trace, while Example2 only gets the trace that comes from the annotation (`trace.annotation`) that I have wrapped the entry point with. Is that expected due to how the functions are structured?

**Comment by joeyzhao2018** [comment]
Hi @ganhammar, [serverless-plugin-datadog v5.33.0](https://github.com/DataDog/serverless-plugin-datadog/releases/tag/v5.33.0) just got released. It should point to dd-trace-dotnet-ARM v8.

I need to take a closer look at the issue why the `aws.lambda` is missing in example2. I will keep this issue open for now and update here soon

**Comment by joeyzhao2018** [comment]
Hi @ganhammar, the `aws.lambda` span was missing previously in example2 due to **double instrumenting** the handler. If you remove [this line here](https://github.com/polestar/dotnet-datadog/blob/main/src/Example2/Function.cs#L16), it would work as expected. This is because our lambda extension is already instrumenting the handler.
I'll close this issue based on this finding for now. Please feel free to leave any comments if you have further questions.

**Comment by ganhammar** [comment]
@joeyzhao2018 Thanks for the update, I guess that makes sense! I still feel it's a bit weird that `Example` and `Example2` behave differently when they have [the same](https://github.com/polestar/dotnet-datadog/blob/main/src/Example/Function.cs#L19) annotations. But, since it's not meant to be done in that way, I'll drop it, thanks for your time and effort!

**Comment by ganhammar** [comment]
Yes, it does, thank you for the clarification!
