### ISSUE TITLE
GitMetadataTagsProvider.TryExtractGitMetadata Extremely Slow

### ISSUE THREAD

**Issue by abner-diaz** [DataDog/dd-trace-dotnet#4226]
**Describe the bug**
Our files are located on a share and this is unnecessarily scanning the folder structure for PDBs.

**To Reproduce**
1. Run the profiler on a .NET app that uses a network share or slow drive.

**Expected behavior**
The DataDog tracer should not be impacting performance at this level.

**Screenshots**
![image](https://github.com/DataDog/dd-trace-dotnet/assets/94029731/4422d035-4e81-4851-9878-c7b2a2206b16)

**Runtime environment (please complete the following information):**
- Instrumentation mode: MSI Installer
- Tracer version: 2.30
- OS: Windows 2019 Standard
- CLR: .NET Framework 4.8

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by abner-diaz** [comment]
Is there a config setting to disable this?  We don't need this additional metadata attached to every span.

**Comment by abner-diaz** [comment]
Found a config setting `DD_TRACE_GIT_METADATA_ENABLED` here, seems like this should be default _false_, though.
https://github.com/DataDog/dd-trace-dotnet/blob/e1fea541a6ef8e301b7016281f500eef049eba03/tracer/src/Datadog.Trace/Configuration/ConfigurationKeys.cs#L62

**Comment by OmerRaviv** [comment]
Thank you very much for the detailed report, and our apologies for the trouble this issue caused. 

To confirm, setting `DD_TRACE_GIT_METADATA_ENABLED` to `0` should work as a workaround while we investigate further.

We will of course keep you posted as soon as we discover more and come up with a fix.

**Comment by OmerRaviv** [comment]
Hi @abner-diaz , thanks again for reporting this. 
This issue has been fixed in the latest version (v2.32.0). Please let us know whether this indeed solved the issue for you.

Thank you for your patience and have a great day.

**Comment by abner-diaz** [comment]
Thanks @OmerRaviv for the quick resolution :)
