### ISSUE TITLE
NullReference exception when LogsInjectionEnabled = true and accessing Trace on multiple threads.

### ISSUE THREAD

**Issue by andyast** [DataDog/dd-trace-dotnet#423]
[DataDogThreadTest.zip](https://github.com/DataDog/dd-trace-dotnet/files/3327322/DataDogThreadTest.zip)

**To Reproduce**
1. Run attached program.

**Expected behavior**
Exception should not be thrown

**Runtime environment (please complete the following information):**
- Nuget Package version: 1.4
- OS: OSX and microsoft/dotnet:2.2-aspnetcore-runtime-stretch-slim docker image
- CLR: .NET Core 2.2

We found this testing AspNetCore applications using IHostedService background services and sharing the Trace instance between them.

**Comment by andyast** [comment]
This is the sample program we used to replicate this bug.
`class Program
    {
        static void Main(string[] args)
        {
            var ddTraceSettings = TracerSettings.FromDefaultSources();
            ddTraceSettings.AnalyticsEnabled = true;
            ddTraceSettings.LogsInjectionEnabled = false;
            ddTraceSettings.TraceEnabled = true;

            var tracer = new Tracer(ddTraceSettings);

            var threads = Enumerable.Range(0, 2).Select(idx =>
            {
                return new Thread(o =>
                {
                    Thread.Sleep(2000);
                    var i = 0;
                    while (i++ < 10_000)
                    {
                        try
                        {
                            using (var span = tracer.StartActive("test"))
                            {
                            }
                        }
                        catch (Exception ex)
                        {
                           Console.WriteLine($"Error making span. {ex}");
                        }
                    }
                });
            }).ToList();

            foreach (var thread in threads)
            {
                thread.Start();
            }

            while (threads.Any(x => x.IsAlive))
            {
                Thread.Sleep(1000);
            }

            Console.WriteLine("Done");
        }
    }`

**Comment by andrewsouthard1** [comment]
Hey @andyast thanks for flagging this and the example program - our team is taking a look.

**Comment by lucaspimentel** [comment]
@andyast: This should now be fixed in [release 1.4.1](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.4.1). Thanks again for reporting it.
