### ISSUE TITLE
OpenTelemetry activity exception tag mapping

### ISSUE THREAD

**Issue by dotTrench** [DataDog/dd-trace-dotnet#4267]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : OpenTelemetry.Api
- Library type: Tracing (Activities)
- Library version: 1.5.0

**Is your feature request related to a problem? Please describe.**
Whenever using the `DD_TRACE_OTEL_ENABLED` and calling the extension method `Activity.RecordException(Exception ex)` defined in the `OpenTelemetry.Api` package. we expect the exception to be recorded in a way similiar to `ISpan.SetException(Exception ex)`.

Currently the span displayed in the UI does not contain any stack trace or error type.

**Describe the solution you'd like**
Translate the semantic conventions for exception tags described [here](https://github.com/open-telemetry/semantic-conventions/blob/main/specification/trace/semantic_conventions/exceptions.md) into datadog specific "error" tags. i.e.

```
exception.stack -> error.stack
exception.message -> error.message
exception.type -> error.type
```

**Describe alternatives you've considered**
As a workaround we could manually set tags to the datadog specific tags when manually creating activities or using "Enrichers" when using instrumentation libraries where it's supported.

**Comment by andrewlock** [comment]
Hi @dotTrench, thanks for flagging that, this is actually something @bouwkast is working on at the moment, so we should have a fix for it soon. Thanks!
