### ISSUE TITLE
Performance overhead/latency on ASP.NET MVC App

### ISSUE THREAD

**Issue by boskya** [DataDog/dd-trace-dotnet#428]
Hello, 

We are noticing that when we have datadog tracer/APM (v1.1.0) turned on our ASP.NET MVC 5 site, some samples report greater than 40 seconds time to first byte. When I look at the flame graph, I get no information on what is taking so long except it is doing something on ASP.NET engine.  When I uninstall the datadog tracer, the request consistently come back within 4-5 seconds. Do you know if datadog tracer can have that much of impact on performance? Also I installed redgate profilers and turned that on instead and that DID Not add any noticeable overhead to the request.  See the two requests below - one takes really long and other doesn't. 

 
![highTTFB](https://user-images.githubusercontent.com/2257673/60542813-a7422400-9cc9-11e9-98ed-d9a101e4289c.PNG)

This happens on not just this page within APP but any page can sporadically return a high time to first byte/stuck at server. Again this doesn't happen when I uninstall datadog tracer. Any ideas?

**Comment by colin-higgins** [comment]
Thank you for the report @boskya 
We are constantly looking to improve the stability and speed of our tracer, so thank you for bringing this to our attention.
Would you be able to upgrade your tracer to the latest version to see if this still occurs?
https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.4.1

**Comment by boskya** [comment]
Hi @colin-higgins I have installed the latest agent, we will monitor for a couple of days and let you know what we find! Thank you.

**Comment by colin-higgins** [comment]
Hey @boskya 
Any new developments here?

**Comment by boskya** [comment]
Sorry for the delay on this. So its MUCH better than what we saw before. We saw an overhead of ~40 seconds before but now I am only seeing an overhead of 4-5 seconds. So a request that takes generally 500 ms can take 5 seconds or so. Thats still a significant overhead. Is there a way we can turn on logging or some other way to see if the profiler is getting stuck somewhere?

**Comment by boskya** [comment]
Any update on this @colin-higgins ?

**Comment by colin-higgins** [comment]
On our current priority list is getting better benchmarks and performance tests in place to track down these sorts of problems. If you wouldn't mind posting a few details about your particular setup, it would greatly help us to track down where this is happening.
For clarification, does this overhead of 4-5 seconds happen on subsequent requests for a given url, or only the first request?
Would you be able to send me your packages.config contents so that we can understand which libraries are being instrumented?

**Comment by boskya** [comment]
4-5 seconds happens only on first request for a given page/url and not on subsequent ones. I also updated to 1.6.1
I am attaching the paket lock and paket dependecies file we use. 

[paket.zip](https://github.com/DataDog/dd-trace-dotnet/files/3517416/paket.zip)

**Comment by boskya** [comment]
More info to add here to clarify the behavior: Once an app pool recycles, the first time we request **any** page on the MVC page we see high latencies. Subsequent requests to each of those pages are fine. So something like that:
ehr/TransferCharge 1st time: 5 seconds, second time: 450ms, third time: 500ms
ehr/ViewCharge 1st time: 4 seconds, second time: 400ms, third time: 450ms

**Comment by BarryDahlberg** [comment]
My experience with the .NET Core agent is very similar. We have an application which _needs_ to respond quickly on first request as we are under strict time constraints. The overhead added by enabling the DataDog profiler (CORECLR_ENABLE_PROFILING=1) means we usually miss this on our first couple of requests before things settle.

We have logic to run warmup cycles and hold new instances out of the pool until ready, so a start up time isn't an issue, as long as we can control when it occurs. Is there any way we can ensure the profiler has done everything it needs before moving on?

**Comment by macrogreg** [comment]
Hey folks, we have made a ton of perf improvements in the recent month, please check out the latest release:
https://github.com/DataDog/dd-trace-dotnet/releases

We focused on steady-state performance first, and we will also approach start-up performance going forward.
For now, there is no hook or event you can listen to to know when the Tracer finished initializing. Note that the overhead is not only at the very start, but generally when your application first loads the libraries we are instrumenting (which is typically very close to the start, but ultimately it depends on your application). As a workaround you can just delay by a few seconds.

@kevingosse , do you have any additional insights?

**Comment by macrogreg** [comment]
All: I will close this tracker for now, but please feel free to re-open if you disagree or if you have new information to share.
Thank you!
