### ISSUE TITLE
Support Serilog v3.0.0

### ISSUE THREAD

**Issue by Hawxy** [DataDog/dd-trace-dotnet#4287]
It's finally that time of the decade for a new serilog release :). https://github.com/serilog/serilog/releases/tag/v3.0.0

Would appreciate instrumentation support so we can take advantage of the performance and allocation improvements in this update.

**Comment by bouwkast** [comment]
Thanks @Hawxy, we'll take a look at getting v3 supported

**Comment by andrewlock** [comment]
Hi @Hawxy - @bouwkast tested the change, but it didn't appear to actually require any changes to the tracer code, which means it should _already_ work for you 🤔 Have you tested it and found that it didn't?

**Comment by andrewlock** [comment]
No worries, glad to hear it, thanks! 😄
