### ISSUE TITLE
Configuring the DataDog tracer through code is ignored by the spans generated through the automatic instrumentation

### ISSUE THREAD

**Issue by sergiobernafm** [DataDog/dd-trace-dotnet#4311]
We have a net framework 4.8 API server application that is running in our windows EKS cluster. 

The container receives the standard datadog tags for the service version and name but then we configure the final tags through code on the globals.ashx using the Application_Start method as in the following example:

`var settings = TracerSettings.FromDefaultSources();
settings.ServiceName = "XXXXXX";
settings.ServiceVersion = 'version';
settings.HeaderTags["SOAPAction"] = "http.request.headers.SOAPAction";
settings.HeaderTags["user_agent"] = "http.request.headers.User-Agent";
Tracer.Configure(settings);`

After deploying we find that only the custom traces added contain the right configuration, while the automatic traces produced by the automatic instrumentation library come with the environment variable data.

As an example, for given post to the server we have first the automatic trace aspnet.request POST where the tag for the version is
version: 0.0.1.0

Which is the one on the environment variable, while for the custom trace that appears right after we have the following:

the version is correclty reported as the one configured in the globals.ashx

version: 'version'

**Comment by kevingosse** [comment]
Can you check that the version of the automatic instrumentation (installed with the MSI) is the same as the version of the nuget package? If that's not the case then the tracer gets loaded twice, and your call to `Tracer.Configure` will only affect the nuget one (and therefore only custom traces).

**Comment by sergiobernafm** [comment]
After ensuring that both the library and the installed instrumentation are in the same version everything works fine and the automatic instrumentation traces are properly configured.
Thanks!
