### ISSUE TITLE
Invalid MessageAttributes on SNS

### ISSUE THREAD

**Issue by jnyrup** [DataDog/dd-trace-dotnet#4316]
**Describe the bug**
After we upgraded to 2.32.0 our subscription filters on AWS SNS unfortunately broke, so messages were not forwarded to SQS queues.
Looking into AWS CloudWatch metrics we saw `NumberOfNotificationsFilteredOut-InvalidAttributes` had started to happen.

> The NumberOfNotificationsFilteredOut-InvalidAttributes metric shows messages that your filter policy rejected because the message attributes weren't in a valid format.

https://repost.aws/knowledge-center/sns-subscription-filter-policy-issues

After downgrading to  2.31.0 we stopped getting `NumberOfNotificationsFilteredOut-InvalidAttributes`.

Here's the `MessageAttributes` of one of our messages, but nothing in there immediately looks suspicious to me.

```
"MessageAttributes" : {
  "ourKey" : {"Type":"String","Value":"OurData"},
  "_datadog" : {"Type":"String","Value":"{\"traceparent\":\"00-000000000000000023b62f1bd3212848-1fe678cc9b22cbd2-01\",\"tracestate\":\"dd=s:1;t.dm:-1\",\"x-datadog-trace-id\":\"2573296033641605192\",\"x-datadog-parent-id\":\"2298657479990627282\",\"x-datadog-sampling-priority\":\"1\",\"x-datadog-tags\":\"_dd.p.dm=-1\"}"}
}
```

**To Reproduce**

**Expected behavior**
`MessageAttributes` should contain valid data, parsable by AWS SNS subscription filters.

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Tracer version: 2.32.0
- OS: Windows Server 2019 ([AWS EB Windows Server](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2023-06-26-windows.html))
- CLR: .NET 6.0.18
- AWSSDK.SimpleNotificationService: 3.3.101.11

**Additional context**

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by astuyve** [comment]
Hey @jnyrup thanks for reaching out, this is a known issue and we're working on a fix [here](https://github.com/DataDog/dd-trace-dotnet/pull/4305)

**Comment by jnyrup** [comment]
Looking forward to see a release with the fix then 👍 

I hate to be the person asking, but since it was fixed in https://github.com/DataDog/dd-trace-py/pull/3404 15 months ago, is there are way you could have known about this and avoided enabling SNS support for dotnet before including a similar fix?

**Comment by astuyve** [comment]
Hey @jnyrup that's my fault personally, I didn't properly communicate this possibility when assigning the task, and it seems that there was misunderstanding about AWS actually fixing this [issue within SNS](https://github.com/DataDog/dd-trace-py/issues/3384#issuecomment-1061194291), it appears they have not.

I apologize for overlooking this risk.

**Comment by zARODz11z** [comment]
If you'd like to continue using Tracer version: 2.32.0 you can disable the sns integration using `DD_TRACE_AwsSns_ENABLED=0` I take responsibility for this issue as well, apologies for any inconvenience. The release is coming soon.

**Comment by pierotibou** [comment]
Fix released in https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.33.0
