### ISSUE TITLE
version missmatch on nuget packages correct ?

### ISSUE THREAD

**Issue by ffandreassoroko** [DataDog/dd-trace-dotnet#444]
[Datadog.Trace 1.4.1](https://www.nuget.org/packages/Datadog.Trace/)
[Datadog.Trace.ClrProfiler.Managed 1.5.0](https://www.nuget.org/packages/Datadog.Trace.ClrProfiler.Managed/)

is that correct ? in the past was everytime the same version for both packages

**Comment by lucaspimentel** [comment]
It's correct. Only `Datadog.Trace.ClrProfiler.Managed` had changes this time.

When `Datadog.Trace` has changes, then we bump the version up on both to encourage users who reference only `Datadog.Trace.ClrProfiler.Managed` to update.
