### ISSUE TITLE
Add MediatR interception

### ISSUE THREAD

**Issue by daniel-white** [DataDog/dd-trace-dotnet#446]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : MediatR
- Library type: workflow library
- Library version: any

**Describe the solution you'd like**
I would like to see automatic instrumentation for [jbogard/MediatR](https://github.com/jbogard/MediatR). I use this to manage the workflow of my service.

**Describe alternatives you've considered**
* Adding my own interceptors. Looks like generics are hard to intercept.
* Manually instrumenting.

**Comment by colin-higgins** [comment]
Thanks for the feature request @daniel-white

**Comment by macrogreg** [comment]
Hi @daniel-white ,

Thanks for the submission. We are working on new integrations as fast as we can. :)
I have added this to our backlog and I will close this item for now. Please fee free to re-open and to commend if new information becomes available. Thank you!
