### ISSUE TITLE
.net6 hosted service not sending metrics automatically

### ISSUE THREAD

**Issue by kadufmoraes** [DataDog/dd-trace-dotnet#4492]
Hi there,

I have a HostedService in .net6 but this service doesn't send metrics automatically.
If I use Datadog.Trace library and call Tracer.Instance.StartActive, I can send it.

The purpose of my service is to get messages from AWS SQS and call a Web API.

**Comment by andrewlock** [comment]
>I have a HostedService in .net6 but this service doesn't send metrics automatically.

Have you instrumented the service using automatic instrumentation, and [enabled runtime metrics](https://docs.datadoghq.com/tracing/metrics/runtime_metrics/dotnet/)? If you have taken these steps and it's still not working for you, I suggest you contact support here: https://www.datadoghq.com/support/ so we can capture all the required details. Thanks!

**Comment by kadufmoraes** [comment]
Hi @andrewlock 
Automatic instrumentation is enabled.
I'll contact support. tks!

**Comment by andrewlock** [comment]
The .NET tracer itself makes HTTP requests to send trace data, if that's what you mean, yes!

**Comment by andrewlock** [comment]
Hi @kadufmoraes, have you had any more luck getting this working?

**Comment by andrewlock** [comment]
Closing this one for now as no answer, feel free to re-open if you're still having issues
