### ISSUE TITLE
Could not access AspNetAmbientContext

### ISSUE THREAD

**Issue by daninden** [DataDog/dd-trace-dotnet#450]
**Describe the bug**
When making a call to an asp.net core controller using version 1.5.0 we get an error: Could not access AspNetAmbientContext for Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow( context) in our datadog log files.

**To Reproduce**

Install version 1.5.0 of the tracer in an asp.net core application.
Make a random call to a controller.

**Expected behavior**
No errors in the log

**Screenshots**

![image](https://user-images.githubusercontent.com/7497671/61356514-cd91c300-a876-11e9-8eb0-6479f5291f4c.png)

**Runtime environment:**
- Instrumentation mode: both automatic and manual
- Tracer version: 1.5.0
- OS: Windows Server 2012 R2
- CLR: .NET Core 2.2

**Comment by colin-higgins** [comment]
Thanks for the report @daninden 
Does this occur only with that Rethrow message? 
Or are there any about BeginAction?

**Comment by daninden** [comment]
only the Rethrow here
