### ISSUE TITLE
Too many spans created for Npgsql INSERT statements

### ISSUE THREAD

**Issue by andreas-soroko** [DataDog/dd-trace-dotnet#453]
**Describe the bug**
puh. i will try my best. 
today we implement someting with a "temp" tabel in postgres. 
so what do we do ? 

1. rest request
2. insert message into db 
3. produce kafka message
4. read exactly this message
5. proccess message
6. delete message

we noticed in datadog that we had 2x more inserts then deletes. ( FYI: we created manuel spans for kafka.produce) 

- produce count: 1,6k
- insert count: 3,3k
- delete count: 1,6k

**Additional info**
- using EF Core
- with Npgsql

**Screenshots**
![image](https://user-images.githubusercontent.com/47380084/61457344-6a805900-a968-11e9-9e88-730dfda35ba2.png)

![image](https://user-images.githubusercontent.com/47380084/61457373-7a983880-a968-11e9-9e07-820df4959c10.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Datadog.Trace: 1.4.1
- Datadog.Trace.ClrProfiler.Managed: 1.4.1
- OS: Docker ( mcr.microsoft.com/dotnet/core/aspnet:2.2.6-stretch-slim )
- CLR: NET Core 2.2.6

**Comment by lucaspimentel** [comment]
@ffandreassoroko: thanks for reporting this. Just to be clear, these are spans created with automatic instrumentation of the `Npgsql` library?

**Comment by ffandreassoroko** [comment]
> with automatic instrumentation of the Npgsql library

Yes :)

**Comment by bobuva** [comment]
@ffandreassoroko We have produced a Pre-Release version [1.13.3-prerelease](https://github.com/DataDog/dd-trace-dotnet/issues/581) that addresses postgres instrumentation issues. I don't know if it would apply to your case here, but want to let you know that you can try this out.

**Comment by bobuva** [comment]
We had a small issue with the versioning in this prerelease and replaced the artifacts in the github release a moment ago to have the correct release version. Sorry for the inconvenience.

**Comment by macrogreg** [comment]
This issue should no longer occur. Please consider the latest release:
https://github.com/DataDog/dd-trace-dotnet/releases

If this issue re-occurs, please re-open and tag me directly. Thank you!
