### ISSUE TITLE
None of the errors are being reported with ASP.NET Core MVC 2.2

### ISSUE THREAD

**Issue by ahmettahasakar** [DataDog/dd-trace-dotnet#464]
I have everything working, however, none of the errors are being reported to Datadog. I even have some exceptions thrown that result error 500 on the server-side. Is there a setting or some registration that must be added to application startup for Dotnet core 2.2? Also, is it possible to manually report errors for handled exceptions?

**Comment by colin-higgins** [comment]
Hi @ahmettahasakar thank you for the report.
Are the exceptions being added to the traces in datadog? 
There is a known issue with the status code not being set when exceptions bubble up past core.mvc and into middleware or later.

**Comment by ahmettahasakar** [comment]
I don't think so. 

This is my sample code. Is this suppose to work out of the box? Am I suppose to see it as an error on Datadog APM Services view?

```
// GET: api/Todo
[HttpGet]
public async Task<ActionResult<IEnumerable<TodoItem>>> GetTodoItems()
{
    throw new Exception("Some message");
}
```

**Comment by colin-higgins** [comment]
Current expected behavior is that the status code would be incorrectly set to 200, but the Exception itself should be on the trace (even though the trace is not labelled as in error in the UI)

**Comment by lucaspimentel** [comment]
Hello. We released [.NET Tracer 1.12.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.12.0) which includes a complete rewrite of the ASP.NET Core instrumentation to use the telemetry that is built into the framework. This should resolve issue with missing exceptions or spans with exceptions not flagged as error.
