### ISSUE TITLE
Add instrumentation for SqlBulkCopy to the ADO.NET Integration

### ISSUE THREAD

**Issue by mikesigs** [DataDog/dd-trace-dotnet#482]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : ADO.NET
- Library type: data store

**Is your feature request related to a problem? Please describe.**
- I expected all my SQL code to be automatically instrumented, but after looking in the code it only seems that `SqlCommand` is instrumented. Would like to see `SqlBulkCopy` included.

**Describe the solution you'd like**
- I would like to see tracing added to the existing ADO.NET integration for `SqlBulkCopy`.

**Describe alternatives you've considered**
- Manual instrumentation

**Comment by macrogreg** [comment]
Thank you for your submission, @mikesigs .

I have added this to our backlog, and I will close this issue for now.
Please feel free to re-open if you have additional information that you would like to add.

If you are an existing customer and you are experiencing concrete hardship for the lack of this feature, could you please open a support case here:
https://www.datadoghq.com/support/

Our support team will work with you directly to see if there are any workarounds and to prioritize product improvements as appropriate.

Thanks!
