### ISSUE TITLE
MQ integration prepends BOM to message body

### ISSUE THREAD

**Issue by dmytroett** [DataDog/dd-trace-dotnet#4964]
We have an azure function, that posts messages into IBM MQ queue. This function also posts all logs/metrics/traces into DataDog via DataDog azure app service extension. We recently upgraded the extension from version 2.23 to 2.43, and right after that the consumers of the messages in the queue started complaining that messages are coming corrupted. Once we disabled DataDog MQ integration (by setting env variable DD_DISABLED_INTEGRATIONS=IbmMq) everything went back to normal. After some analysis I discovered that DataDog MQ integration started prepending big-endian BOM to every message (FE FF), whereas it wasn't happening before.

Runtime environment:
Azure Function App. Runtime version 4.27.5.21549, OS Windows.
DataDog extension version: 2.43.
DataDog configuration env variables:
- DD_API_KEY=
- DD_ENV=
- DD_LOGS_DIRECT_SUBMISSION_INTEGRATIONS=ILogger
- DD_LOGS_DIRECT_SUBMISSION_MINIMUM_LEVEL=Information
- DD_LOGS_INJECTION=true
- DD_PROFILING_ENABLED=true
- DD_RUNTIME_METRICS_ENABLED=true
- DD_SITE=us3.datadoghq.com

**Comment by kr-igor** [comment]
Hi @dmytroett 
Thanks for reporting this issue. 
I'll investigate and get back to you.

**Comment by dmytroett** [comment]
Hi @kr-igor ,

Regarding the version, I was able to reproduce it with both 9.2.5 and 9.3.2.

Example of sending code:

```
        using var queueManager = new MQQueueManager(_mqSettings.Value.QueueManagerName, _mqSettings.Value.Properties);

        using var queue = queueManager.AccessQueue("Q.TEST", MQC.MQOO_OUTPUT + MQC.MQOO_INPUT_AS_Q_DEF + MQC.MQOO_FAIL_IF_QUIESCING);

        MQPutMessageOptions pmo = new()
        {
            Options = MQC.MQPMO_NO_SYNCPOINT + MQC.MQPMO_SYNC_RESPONSE + MQC.MQPMO_FAIL_IF_QUIESCING
        };

        MQMessage message = new()
        {
            Format = MQC.MQFMT_STRING,
            Persistence = MQC.MQPER_PERSISTENT
        };

        message.WriteString("This is test message");

        queue.Put(message, pmo);
```
Regarding receiving code, I cannot provide you that, because it is not even .NET and is using some kind of IBM integration library. What I can tell you for certain, it was consuming messages ok, until BOM started to appear in the messages.

**Comment by kr-igor** [comment]
@dmytroett Thank you! I'll investigate and get back to you.

**Comment by kr-igor** [comment]
@dmytroett This issue should be resolved in the latest version of the tracer.
