### ISSUE TITLE
System.NullReferenceException in RedisExecuteAsyncIntegration.OnMethodBegin(RedisBase , Message& , ResultProcessor`1& , ServerEndPoint& )

### ISSUE THREAD

**Issue by cpaolucci-technogym** [DataDog/dd-trace-dotnet#5094]
**Describe the bug**
The application consistently throws many System.NullReferenceException. There are no unexpected behaviour except the flooding of handled exceptions. Via the FirstChanceExceptionHandler we logged: "System.NullReferenceException: Object reference not set to an instance of an object.    at RedisExecuteAsyncIntegration.OnMethodBegin(RedisBase , Message& , ResultProcessor`1& , ServerEndPoint& )"

**To Reproduce**
Start the application

**Expected behavior**
No exceptions

**Runtime environment (please complete the following information):**
- Instrumentation mode: NuGet package
- Tracer version: Bundle 2.36.0
- OS: Linux 5.10.201-191.748.amzn2.x86_64 #1 SMP Mon Nov 27 18:28:14 UTC 2023
- CLR: .NET Core 6

![image](https://github.com/DataDog/dd-trace-dotnet/assets/153937949/ca5136cc-5a44-490e-9b7f-2993984f96a9)

**Comment by andrewlock** [comment]
Hi @cpaolucci-technogym, [we fixed an issue](https://github.com/DataDog/dd-trace-dotnet/pull/4921) related to this in version 2.43.0 of the tracer. Could you please try updating to the latest and see if that resolves your issue? Thanks!

**Comment by cpaolucci-technogym** [comment]
Hi, updating to 2.45.0 has actually fixed the issue in our test environment. We scheduled a deploy in the next hours, I'll let you know whether is fixed or not.
Thank you!
