### ISSUE TITLE
OpSysTools::IsSafeToStartProfiler always returns false 

### ISSUE THREAD

**Issue by lodmfjord** [DataDog/dd-trace-dotnet#5245]
**Describe the bug**
We recently upgraded our dd-trace agent and now tracing no longer works on our kubernetes cluster

OpSysTools::IsSafeToStartProfiler seems to always return false.

**Expected behavior**
Should be able to run or at least force it to run even though it fails the check.

**Runtime environment (please complete the following information):**
- Instrumentation mode: [e.g. automatic with msi installer or manual with NuGet package]
- Tracer version: 2.47.0
- OS: Ubuntu Chiseled
- CLR: 8

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by gleocadie** [comment]
👋 @lodmfjord 
Thanks for the report.
Can you provide the logs file please (in `/var/log/datadog/dotnet/*`) ?

**Comment by lodmfjord** [comment]
I found the solution. 
I can skip the test by defining DD_PROFILING_MIN_CORES_THRESHOLD
