### ISSUE TITLE
auto-instrument SqlCommand.ExecuteXmlReader()

### ISSUE THREAD

**Issue by lucaspimentel** [DataDog/dd-trace-dotnet#534]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Method name: `System.Data.SqlClient.SqlCommand.ExecuteXmlReader()`
- Library type: data store
- Library version: versions built into .NET Framework and [NuGet package](https://www.nuget.org/packages/System.Data.SqlClient) 4.1+

Note that this method is specific to the SQL Server client and is not part the standard ADO.NET API (i.e. providers that derive from `DbCommand`).

**Comment by macrogreg** [comment]
We are currently working on new and on improved integrations with SQL-backing client libraries. Primarily, we focus on `Microsoft.Data.SqlClient` and its flavors. The particular API described by _this_ issue is _not_ in scope of this effort in the current planning cycle.

We discussed this with @lucaspimentel who filed this issue, and we decided not to track it for now. We can re-open this tracker if we receive a specific request to instrument this API. Closing for now.
