### ISSUE TITLE
AspNet Core 3.0 MVC Endpoint routing not traced

### ISSUE THREAD

**Issue by zikhan** [DataDog/dd-trace-dotnet#536]
**Description**
When using the datadog agent, datadog .net tracer, and the Datadog.Trace.ClrProfiler.Managed nuget, I'm not seeing the endpoint routing in the apm traces. However, other integrations like the HttpClient are still working.

**To Reproduce**
1. Update application to .net core 3.0
2. Update mvc to endpoint routing as seen in [2.2 to 3.0 Migration Doc](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#routing-startup-code)
3. Update Datadog nuget and tracer to 1.8.0 (really any version)

**Expected behavior**
Service traces for the service's Endpoint routes to appear in Datadog.

**Runtime environment:**
- Instrumentation mode: Automatic with .tar.gz files in docker container and nuget package, recreated with Automatic msi installer and nuget package in Windows environment.
- Tracer version: 1.8.0
- OS: Windows 10 build 18362.418 and aspnet Linux docker containers
- CLR: .Net Core 3.0

**Additional context**
I'm thinking that the endpoint routing middleware works differently than the .net core 2 mvc routing middleware, and there is no interceptor for the .net core 3 routing middleware, especially since the Microsoft.AspNet.Mvc.Internal.ResourceInvoker is gone in core 3.

**Comment by bogdbo** [comment]
When runnning a WebApi on dotnet core 2.2 rider reports this message:

`Loading module Datadog.Trace.ClrProfiler.Managed.Loader in application domain 1:clrhost`

I do not see it when switching to dotnetcore 3.0, same configuration, just a barebones scaffolded webapi project.

Is there something specific that initiates that Loader? Let me know if I can provide more info about my setup

**Comment by colin-higgins** [comment]
Thank you for reporting this @zikhan 
We need to add new integrations for .net core 3 to support the changed methods as we currently rely on `ResourceInvoker` as you mentioned.
We will keep you updated on this thread.

**Comment by bogdbo** [comment]
@colin-higgins does this mean that this 'Important' line in the release notes is not entirely correct? I'm just trying to confirm to make sure there's no confusion on either side. Thanks!

![image](https://user-images.githubusercontent.com/889997/67687472-4208f180-f990-11e9-965b-a46365a223d1.png)

**Comment by colin-higgins** [comment]
For clarification on that line: it means that our tracer is safe to use with netcore 3, not that every integration supported in netcore 2 has been ported, as some libraries and frameworks have changed.
Other libraries and frameworks have not changed the signatures we rely on, so those work out of the box.

**Comment by bogdbo** [comment]
Thanks for the clarification @colin-higgins.

**Comment by dan655t** [comment]
Is there an ETA being targeted for aspnet core 3 integration support?  Thank you in advance.

**Comment by colin-higgins** [comment]
coremvc3 support has been added with https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.10.0

**Comment by ffandreassoroko** [comment]
does not work for us. we still dont see any traces on incoming requests

DockerImage: mcr.microsoft.com/dotnet/core/runtime-deps:3.0
Datadog.Trace: 1.10.0
Datadog.Trace.ClrProfiler.Managed: 1.10.0

**Comment by colin-higgins** [comment]
@ffandreassoroko Would you be able to provide an example configuration and controller action?

**Comment by ffandreassoroko** [comment]
Looks basically like this
[FFStartupBase.txt](https://github.com/DataDog/dd-trace-dotnet/files/3901321/FFStartupBase.txt)


and it makes no difference if we use 
`services.AddMvc()` or `services.AddControllers()`

**Comment by ffandreassoroko** [comment]
any update on this ?

**Comment by colin-higgins** [comment]
@ffandreassoroko Not yet, I still need to circle back around to this. I'll update here when I do.

**Comment by scanham** [comment]
I'm running into the same thing - no traces (other than manual ones) from our a 3.0 app using 1.10.0. If you need another example startup I can provide that too.

**Comment by zikhan** [comment]
I was able to get this working on the dotnet/core/aspnet:3.0 & 3.1 containers with the .tar.gz folder being extracted to /opt/datadog (including the .netstandard folder), and upgrading the Datadog.Trace.ClrProfiler.Managed nuget to 1.10.0

**Comment by scanham** [comment]
I take that back - It was a configuration issue on mine.. Sorry! Working with core 3.0 and dd 1.10.0
