### ISSUE TITLE
Optimise dependencies

### ISSUE THREAD

**Issue by thompson-tomo** [DataDog/dd-trace-dotnet#5377]
### Is your feature request related to a problem? Please describe.
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

### Describe the solution you'd like
Within the Datadog.Trace.OpenTracing package, The System.Net.Http dependency becomes conditional so that it is only added for the older frameworks

### Describe alternatives you've considered
Accept the additional dependency

### Additional context
n/a

**Comment by andrewlock** [comment]
As far as I can see, we don't depend on _System.Net.Http_, even transitively 🤔 Which NuGet package are you referring to? [Datadog.Trace](https://www.nuget.org/packages/Datadog.Trace)?

**Comment by thompson-tomo** [comment]
So Datadog.Trace.OpenTracing depends on System.Net.Http, so I have updated the description.

**Comment by andrewlock** [comment]
OK, thanks for the details. 

To set expectations, I doubt we will take this approach. [The OpenTracing project](https://opentracing.io/) is archived and considered deprecated at this point. We recommend considering [moving to OpenTelemetry](https://www.datadoghq.com/knowledge-center/opentelemetry/) instead. We will likely deprecate the Datadog.Trace.OpenTracing package in a future version

**Comment by thompson-tomo** [comment]
@andrewlock i took a look at this topic & I was able to identify a number of locations where the dependencies can be optimised hence have submitted #5410 to cover these optimisation's.

**Comment by lucaspimentel** [comment]
Closing this issue as fixed in #5418.
