### ISSUE TITLE
ADO.NET traces missing after upgrade from 1.7 -> 1.8

### ISSUE THREAD

**Issue by gshackles** [DataDog/dd-trace-dotnet#540]
**Describe the bug**

Discussed in Slack with @lucaspimentel  but figured I'd create this for the sake of documenting and tracking it. We noticed that after upgrading the trace agent from 1.7 to 1.8 we stopped getting ADO.NET traces. When running 1.7 we'd see the following in the logs, but not in 1.8:

```
[w3wp.exe] 3372: [info] *** JITCompilationStarted() replaced calls from System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader() to System.Data.Common.DbCommand.ExecuteDbDataReader() 100668732 with calls to Datadog.Trace.ClrProfiler.Integrations.AdoNetIntegration.ExecuteDbDataReader() 167773671
[w3wp.exe] 3372: [info] *** JITCompilationStarted() replaced calls from System.Data.Common.DbCommand.ExecuteReaderAsync() to System.Data.Common.DbCommand.ExecuteDbDataReaderAsync() 100668744 with calls to Datadog.Trace.ClrProfiler.Integrations.AdoNetIntegration.ExecuteDbDataReaderAsync() 167773672
```

It looks like this is due to the change in 1.8 to instrument the public `DbCommand.ExecuteReader()` instead of the protected `DbCommand.ExecuteDbDataReader()` used previously. Our code is using the `IDbCommand` interface to call these methods ([by way of the Dapper library](https://github.com/StackExchange/Dapper)), which is now getting missed by the instrumentation [as it's skipping the instrumented method](https://github.com/dotnet/corefx/blob/179013357896ab947523bdf9961c02f8504db6ff/src/System.Data.Common/src/System/Data/Common/DbCommand.cs#L112).

**Expected behavior**
Usages of `IDbCommand` are automatically instrumented and traced.

**Runtime environment (please complete the following information):**
- Instrumentation mode: Tried both with and without the NuGet package
- Tracer version: 1.8
- OS: Windows
- CLR: .NET Core 2.2

**Comment by lucaspimentel** [comment]
[Release 1.10.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.10.0) fixes this issue and adds instrumentation for more cases that were not being instrumented even before the regression.

**Comment by jonjomckay** [comment]
We just upgraded to version 1.10.0 and this still appears to be broken for us. However now, no database traces are coming through at all, but previous broken versions still posted a few sporadic traces.

**Comment by gshackles** [comment]
@jonjomckay You're likely being bitten by #581 just like we are, if you've got any extra context from your apps feel free to toss it on there!
