### ISSUE TITLE
Release 1.9.0 assets not attached to v1.9.0 tag

### ISSUE THREAD

**Issue by rlaveycal** [DataDog/dd-trace-dotnet#549]
I have an automated build that pulls the deb installer into a container. This relies on consistent naming of releases. The deb file for 1.9.0 was attached to the tag [1.9.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/1.9.0) whereas all previous releases had been attached to the `v1.x.y` tag. 

Can you add them to [v1.9.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.9.0) or is this convention going to be the norm going forward?

**Comment by colin-higgins** [comment]
Sorry about that, the norm will continue to be with the `vX.Y.Z` format, including the `v` prefix.
I have updated the release to use the `v1.9.0` tag. Please re-open if there are any more problems.
