### ISSUE TITLE
.NET Core tracer breaks Azure Application Insights HTTP dependency telemetry 

### ISSUE THREAD

**Issue by asrichesson** [DataDog/dd-trace-dotnet#5615]
**Describe the bug**
When a .net core api running in IIS makes an http call on a windows server with the .net core tracer installed, the http dependency telemetery is not being logged to Azure Application Insights. 

**To Reproduce**
1. Create a .net core api that makes an http call to another .net core api using the normal HttpClient
2. Connect the two apis to azure app insights and make sure you are receiving http dependency telemetry
3. Install the two apis with IIS on a windows server
4. Install the datadog .net core tracer on the same windows server
5. Trigger the api to make an http dependency call to the other api
6. Http dependency telemetry no longer shows up in app insights

**Expected behavior**
Http dependency telemetry continues to show in app insights under "Dependencies"

**Screenshots**
![image](https://github.com/DataDog/dd-trace-dotnet/assets/51305664/e085a190-31ec-4e34-a2a4-04a158fa0dc5)
Notice that the majority of the telemetry is data dog http requests.
I expect all http dependency telemetry to show up here

**Runtime environment (please complete the following information):**
- Instrumentation mode: msi
- Tracer version: 2.52.0
- OS: windows server 2019 standard
- CLR: .net core 8.0

**Additional context**
I uninstalled the .net tracer and the telemetry started working again, so I know it's related. Http calls to non-instrumented routes seem to work fine, like google.com

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by lucaspimentel** [comment]
Hello @asrichesson. It looks like you're trying to instrument an application with both Datadog's .NET tracer and Application Insights at the same time. Unfortunately, loading multiple APM products into a processes is not supported since they will conflict with each other.

Quoting [our documentation](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-core):
> Note: Datadog's automatic instrumentation relies on the .NET CLR Profiling API. This API allows only one subscriber (for example, Datadog APM). To ensure maximum visibility, run only one APM solution in your application environment.

**Comment by lucaspimentel** [comment]
I you need further assistance, please contact Datadog Support at https://www.datadoghq.com/support/.
