### ISSUE TITLE
Visual Studio Cannot Debug Container When Agent is Installed 

### ISSUE THREAD

**Issue by cshaw-dmg** [DataDog/dd-trace-dotnet#5655]
**Describe the bug**
After following the directions at: https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-core/?tab=linux to enable datadog tracing I can no longer debug my container with visual studio. If I try to start my container in debug mode Visual Studio just displays an error: Failed to launch debug adapter.

![image](https://github.com/DataDog/dd-trace-dotnet/assets/96480836/aa68a471-5b82-46b2-8c0f-5c8a9141bca3)

If I look at the debug output all I see is:
The program '' has exited with code 4294967295 (0xffffffff).

**To Reproduce**
1. Clone this repo: https://github.com/cshaw-dmg/DatadogTraceBug
2. Open Example.sln using Visual Studio 2022
3. Try to start the docker container by clicking the Container (Dockerfile) button
![image](https://github.com/DataDog/dd-trace-dotnet/assets/96480836/133df503-6d78-4cef-a98a-6f0169f72891)

4. When the container tries to start you will see the error message

**Expected behavior**
The container should start and my breakpoints should be hit and tracing should also work while I'm debugging

**Runtime environment (please complete the following information):**
- Instrumentation mode: I followed these directions: https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-core/?tab=linux
- Tracer version: The latest
- OS: Ubuntu container with the .net 6.0 runtime
- CLR: dotnet 6.0

**Additional context**
I've noticed that if I comment out the line `ENV CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so` in my dockerfile I'm able to debug again but tracing doesn't work

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by andrewlock** [comment]
Thanks for reporting this @cshaw-dmg, and a _big_ thanks for the reproduction. We've identified the root cause, and have prepared a fix for it here: https://github.com/DataDog/dd-trace-dotnet/pull/5657.

You can workaround the issue for the mean time by setting `ENV DD_PROFILER_EXCLUDE_PROCESSES=vsdbg` in your dockerfile. This has the same effect as the fix, though I'd recommend removing that variable once the fix is released, as it overrides our default exclude list, which may be updated further in the future. 

Hope that helps, and thanks again!

**Comment by andrewlock** [comment]
FYI @cshaw-dmg, we've just released 2.53.0, which addresses the issue. Thanks again for reporting it, do let us know if you have any further difficulties. Thanks again!
