### ISSUE TITLE
ASP.NET Web API 2 automatic instrumentation

### ISSUE THREAD

**Issue by geofflamrock** [DataDog/dd-trace-dotnet#571]
Hi,

I'm trying to automatically instrument an ASP.NET Web API 2 application running in IIS and I've done the following:

- Installed the latest .NET tracing release 1.9.0 MSI 
- Referenced it in the web.config with 
```
<assemblies>
  <add assembly="Datadog.Trace.ClrProfiler.Managed, Version=1.9.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb" />
</assemblies>
```
- Set the following appsettings to hopefully enable the tracing

```
  <add key="DD_TRACE_ENABLED" value="true" />
  <add key="DD_TRACE_DEBUG" value="true" />
  <add key="DD_SERVICE_NAME" value="one-web-api" />	
  <add key="DD_TRACE_ANALYTICS_ENABLED" value="true" />
  <add key="DD_ASPNETWEBAPI2_ENABLED" value="true" />
  <add key="DD_ASPNETWEBAPI2_ANALYTICS_ENABLED" value="true" />
  <add key="DD_ASPNETMVC_ENABLED" value="true" />
  <add key="DD_ASPNETMVC_ANALYTICS_ENABLED" value="true" />
  <add key="DD_ADONET_ENABLED" value="true" />
  <add key="DD_ADONET_ANALYTICS_ENABLED" value="true" />
```

I can see in the dotnet-profiler.log file for the profiler the following line:

```
[w3wp.exe] 10052: [info] *** JITCompilationStarted() replaced calls from <SendAsync>d__1.MoveNext() to System.Web.Http.Controllers.IHttpController.ExecuteAsync() 100665204 with calls to Datadog.Trace.ClrProfiler.Integrations.AspNetWebApi2Integration.ExecuteAsync() 167773786
```
which I think means that the appropriate profiler hook has been added and is working.

However in the trace-agent.log file I can see the following:

```
2019-11-26 15:35:05 AEDT | TRACE | INFO | (pkg/trace/info/stats.go:108 in LogStats) | [lang:.NET lang_version:4.7.2 interpreter:.NET Framework tracer_version:1.9.0.0] -> traces received: 2, traces filtered: 0, traces amount: 720 bytes, events extracted: 0, events sampled: 0
```

Specifically the events extracted: 0 and events sampled: 0 makes me think either I've configured something incorrectly or perhaps there is a bug of some sort.

Interestingly, I have the same setup on a WCF application running in IIS (same assembly being added, same appsettings except I've used "DD_WCF_ENABLED" and it is working correctly.

Is there something I've missed with the ASP.NET Web API 2 setup here?

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Tracer version: 1.9.0
- OS: Windows Server 2016
- CLR: .NET Framework 4.7.2

Thanks.

**Comment by colin-higgins** [comment]
Hi @geofflamrock 
None of the `DD_WCF_ENABLED` style variables should be necessary.
Is this web api application on the same machine as the WCF app?
If not, it may be worth checking your agent configuration to see if you have traces enabled (https://docs.datadoghq.com/tracing/send_traces/).
Based on your log, it does look like the integration is hooked in.
If the trace agent seems good, please feel free to open a support ticket internally so we start a more in depth conversation about this and maybe grab your logs (https://docs.datadoghq.com/help/).

**Comment by geofflamrock** [comment]
Hi @colin-higgins , thanks for the information. Yes the Web API application is on the same machine as the WCF app, so I believe traces are enabled. We are also sending some custom traces using the NuGet package in another application from this same machine.

I'll raise a support ticket to see if we can work it out, if there is something of value to post back here that comes back from that to assist others I'll do so.

**Comment by geofflamrock** [comment]
@colin-higgins I didn't end up getting very far with the support ticket, I was going to collect some logs and such but ended up just installing the latest version 1.11 and the automatic instrumentation is now working (not withstanding an installation issue where the wrong dll version appears to be being installed in the GAC, but I'll raise a separate issue here for that). 

I'll close this off, thanks for your help.
