### ISSUE TITLE
[Question] Is the "rasp-rule-set.json ---rules.conditions.operator" of `RaspModule` confidential?

### ISSUE THREAD

**Issue by RTxin** [DataDog/dd-trace-dotnet#5884]
Hello, @NachoEchevarria ：
 I'm interested in rasp detection for dotnet-agent and I see that the module in question was developed by you, so can I ask you some questions about it?

In your commit log there is a `test\rasp-rule-set.json` file, in this there is a property `"operator": "***_detector"`,I'm trying to learn the logic of these detector but I don't seem to be able to search for any useful information about it, So this part of the logic code is confidential?
Can you tell me where I can view this part of the code?🌹❤

**Comment by robertpi** [comment]
Please contact support@datadoghq.com for questions about using the Datadog dotnet client library.
