### ISSUE TITLE
Build location change to /package in 2.57 breaking docker builds

### ISSUE THREAD

**Issue by tjosgood** [DataDog/dd-trace-dotnet#5896]
**Describe the bug**
Latest version of `dd-lib-dotnet-init` docker image `(2.57)` seems to now copy dd_tracer build files to `/datadog-init/package/`
instead of `/datadog-init/monitoring-home/` as it did in `2.56`

This means any build process using the instructions from DD docs using
`COPY --from=datadog/dd-lib-dotnet-init /datadog-init/monitoring-home/ /dd_tracer/dotnet/`

are now broken with the error  `"/datadog-init/monitoring-home": not found`

**To Reproduce**
1) build an image using `COPY --from=datadog/dd-lib-dotnet-init /datadog-init/monitoring-home/ /dd_tracer/dotnet/`

**Expected behavior**
It should build

**Runtime environment (please complete the following information):**
- Instrumentation mode: [e.g. automatic with msi installer or manual with NuGet package]
- Tracer version: 2.57

**Additional context**
This also applies to many other tags pushed along with it (2, v2.. etc I didnt try them all)

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\
Linux: /var/log/datadog/dotnet/
--!>

**Comment by andrewlock** [comment]
Hi @tjosgood. Sorry to here that this broke your build, but the layout of the `dd-lib-dotnet-init` is not intended to be relied on directly, it is an internal implementation detail for use by the [Datadog Admission Controller](https://docs.datadoghq.com/containers/cluster_agent/admission_controller).

The supported ways of installing the tracer directly are listed here: https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries

> using the instructions from DD docs

Could you please let me know where in the docs it suggests copying from `dd-lib-dotnet-init`, so I can make sure that gets fixed ASAP. 

Thanks!

**Comment by tjosgood** [comment]
here in the docs
https://docs.datadoghq.com/serverless/google_cloud_run/?code-lang=dotnet

![image](https://github.com/user-attachments/assets/6efb82bd-cdff-4c03-9b17-cb244cfd833e)

**Comment by tjosgood** [comment]
From the link you sent I dont see an equivalent way of installing it on an container for use in cloud functions where there is no agent available. What is the proper path to do what is described in my screenshot i.e. deploy to a serverless container alongside the .net app

**Comment by andrewlock** [comment]
Thanks, yeah, that documentation isn't correct, I'm reaching out to the serverless team to get it fixed now and to see exactly what is required

**Comment by tjosgood** [comment]
I have pinned our builds to v2.56 for now will check back later, thanks

**Comment by lucaspimentel** [comment]
Thanks for reporting this, @tjosgood. The documentation you linked was updated to remove the reference to `dd-lib-dotnet-init`, so I will close this issue. Feel free to reach out again if you have further issues.

https://docs.datadoghq.com/serverless/google_cloud_run/?code-lang=dotnet

**Comment by tjosgood** [comment]
Great, have updated to use the new instructions and all good, thanks guys!
