### ISSUE TITLE
Cannot find Datadog.Trace.AspNet 1.11.0

### ISSUE THREAD

**Issue by geofflamrock** [DataDog/dd-trace-dotnet#593]
**Describe the bug**
Using the 1.11.0 installer, I can't configure the AspNet http module properly, as the dll Datadog.Trace.AspNet can't be loaded.

**To Reproduce**
1. Install Windows trace agent 1.11.0
2. Configure TracingHttpModule by adding `<add name="DatadogModule" type="Datadog.Trace.AspNet.TracingHttpModule, Datadog.Trace.AspNet"/>` to web.config of Asp.Net application (as per samples)
3. Application won't start as Datadog.Trace.AspNet assembly cannot be loaded

**Expected behavior**
Application starts and tracing is enabled.

**Screenshots**

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic with msi installer
- Tracer version: 1.11.0
- OS: Windows Server 2016
- CLR: .NET Framework 4.7

**Additional context**
Looking in the GAC I can see the following folders with versions of assemblies:
- Datadog.Trace.ClrProfiler.Managed: v4.0_1.11.0.0__def86d061d0d2eeb
- Datadog.Trace.AspNet: v4.0_1.0.0.0__def86d061d0d2eeb (but this folder contains the dll for the 1.11.0 assembly).

I copied the various dlls directly into the application bin directory and it all works correctly, so I think it's just that the Datadog.Trace.AspNet assembly is installed into the GAC with the wrong version number so it can't be automatically found.

Thanks :)

**Comment by lucaspimentel** [comment]
@geofflamrock: Can you try using the assembly's full name?

Note that the assembly version for `Datadog.Trace.AspNet` will remain at `1.0.0.0` until we increment the Tracer's major version number to `2.0.0.0`. This will reduce the need to update the `web.config` file every time users update the .NET Tracer.

```xml
<system.webServer>
  <modules>
    <add name="DatadogModule" type="Datadog.Trace.AspNet.TracingHttpModule, Datadog.Trace.AspNet, Version=1.0.0.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb" />
  </modules>
</system.webServer>
```

**Comment by geofflamrock** [comment]
Hi @lucaspimentel thanks for getting back to me. 

Yes we can do that, I'll check and ensure it works and let you know if we encounter any further issues. 

Using this model of a static version number 1.0.0.0, if we were to upgrade the trace agent on a machine, will it update the assembly of Datadog.Trace.AspNet stored in the GAC even though the numbers are the same? I thought (and I could very well be incorrect here) that it didn't update the assemblies because it would detect that the version already existed and therefore we wouldn't actually get a newer version of the assembly.

I wonder if it also might be a good idea to put this specifically in the documentation and samples so that it's clear to users this is how configuration needs to be done.

Thanks.

**Comment by geofflamrock** [comment]
I can confirm using the assembly full name works fine.

**Comment by andrewsouthard1** [comment]
Thanks @geofflamrock for confirming, we will look to update our docs to make this more clear.
