### ISSUE TITLE
System.Data.SqlClient trace not collected

### ISSUE THREAD

**Issue by Ranjit2528** [DataDog/dd-trace-dotnet#596]
I have create simple asp.net application. click on login and open login form and enter user and password click on login button. in back end connect sql server database and execute simple database query. i see only web request trace generated.
 
{"event":[{"OperationName":"aspnet.request","ResourceName":"POST /account/login","Type":"web","Error":false,"ServiceName":"mytraceservice","TraceId":1701523631780812871,"SpanId":1868571706232432033}]}

sql server database trace not see. ?

i don't know need any other configurations. i also check Integrations.json file included  System.Data.SqlClient.

**Comment by jeremy-lq** [comment]
@Ranjit2528 We need some additional information to troubleshoot this issue. Please open a support ticket and we'll pick things up from there.
