### ISSUE TITLE
How to instrument StreamReader class which is in mscorlib

### ISSUE THREAD

**Issue by hemant-learningforever** [DataDog/dd-trace-dotnet#597]
In the earlier version of DD tracer after commenting out mscorlib from unwanted assemblies it was getting instrumented
In this newer version not able to Instrument mscorlib. Pls assist

**Comment by jeremy-lq** [comment]
@hemant-learningforever We'll need some additional information, so let's move to a [support ticket](https://docs.datadoghq.com/help/). The version of the tracer you're using and any error messages you're seeing will help. Thanks.
