### ISSUE TITLE
postgres traces missing after AspNetCore.HealthChecks.NpgSql upgrade from 2.2.0 to 3.0.0

### ISSUE THREAD

**Issue by lpodolak** [DataDog/dd-trace-dotnet#599]
Postgres traces are not appearing after upgrading AspNetCore.HealthChecks.NpgSql to version 3.0.0. I am in the process of upgrading our asp.net core app to .net core 3.1 (from 2.2) and it looks like I have solved all other problems with making sure datadog automatic instrumentation works well. Only once I upgraded the mentioned library (which is not required for the entire app) I stopped receiving postgres traces. Other 3 automatic traces that I have (asp.net, redis, httpclient) are appearing.

**Runtime environment (please complete the following information):**
- Instrumentation mode: Automatic only
- Tracer version: 1.11.0
- OS: mcr.microsoft.com/dotnet/core/aspnet:3.1.0-buster-slim (docker image) @ Fargate v1.3 (LATEST)
- CLR: .NET Core 3.1.0

**Additional context**
-  Npgsql 4.1.1

**Comment by jeremy-lq** [comment]
@lpodolak we need some additional information to troubleshoot further. Please open a support ticket and we'll pick things up from there. Thanks.

**Comment by lpodolak** [comment]
We successfully upgraded to DataDog 16.1.2 with .net core 3.1 and I confirm that the problem is gone.

**Comment by lucaspimentel** [comment]
Thanks for the update, @lpodolak.
