### ISSUE TITLE
Support OpenTracing Logs

### ISSUE THREAD

**Issue by geofflamrock** [DataDog/dd-trace-dotnet#600]
Hi,

Currently DataDog.Trace.OpenTracing doesn't appear to support sending logs alongside a trace, is this something that is planned to be supported?

Thanks.

**Comment by lucaspimentel** [comment]
Hey, @geofflamrock. Thanks for the feedback, but we currently don't have plans to support sending logs with `DataDog.Trace.OpenTracing`. We do support collecting logs from your .NET apps in different ways. See [our docs](https://docs.datadoghq.com/logs/log_collection/csharp/) for more details.
