### ISSUE TITLE
CloudWatch log enrichment for Lambda invocations no longer works after upgrading to version 3.2.0

### ISSUE THREAD

**Issue by KevinD-87** [DataDog/dd-trace-dotnet#6006]
**Describe the bug**
I'm using the latest versions of the Datadog Lambda extension (v64) and Datadog .NET Tracer AWS Layer (v15 - dd-trace-dotnet 2.46.0).
My application is running on .NET 8.0 and contained a reference to Datadog.Trace 2.57.0, which allowed me to enrich the logs that are written to CloudWatch with the dd_trace_id, dd_span_id, etc.
After upgrading Datadog.Trace to version 3.2.0, this enrichment no longer works.
The following environment variables are configured on my Lambda function:
```terraform
    DD_TRACE_ENABLED                 = true
    DD_TRACE_MANAGED_SERVICES        = true
    DD_LOGS_INJECTION                = true
    DD_TRACE_DEBUG                   = false
    DD_CAPTURE_LAMBDA_PAYLOAD        = false
    DD_SERVERLESS_LOGS_ENABLED       = false
```

I've tried adding the following environment variables, as described in the [single step instrumentation documentation](https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/single-step-apm/?tab=linuxhostorvm), which was linked via the 'Automatic Instrumenation' page in the [Migration documentation](https://github.com/DataDog/dd-trace-dotnet/blob/master/docs/MIGRATING.md), since I'm suspecting an incompatibility between the version of dd-trace-dotnet used by the Lambda layer and the Datadog.Trace package, but this doesn't work either:
```terraform
    DD_APM_INSTRUMENTATION_ENABLED   = "host"
    DD_APM_INSTRUMENTATION_LIBRARIES = "dotnet:2.46.0"
```

**To Reproduce**
Steps to reproduce the behavior: see description

**Expected behavior**
CloudWatch logs are enriched with Datadog context information like the dd_trace_id, dd_span_id, etc.

**Runtime environment (please complete the following information):**
- Instrumentation mode: [.NET Serverless (custom via Lambda layers)](`https://docs.datadoghq.com/serverless/installation/dotnet/?tab=custom`)
- Tracer version: 2.46.0
- OS: AWS Lambda runtime .NET 8 (C#/F#/PowerShell), x86_64 architecture
- CLR: .NET 8.0

**Comment by andrewlock** [comment]
Hi @KevinD-87, yes looks like an incompatibility between the versions. You should always keep the version of your Datadog.Trace NuGet package in-sync with the version used in the AWS Layer. The Lambda team are working on producing a layer with a newer version of the library, but in the mean time you should stay on 2.x.

FYI, one of the reasons for the breaking changes in the v3 version of the tracer was to reduce the coupling between the NuGet and automatic instrumentation versions, so that it becomes less important to keep them perfectly in sync (as long as both are on v3!)

**Comment by KevinD-87** [comment]
Hi @andrewlock, thanks for the quick confirmation! I'll keep an eye on the releases of the AWS layer.

**Comment by duncanista** [comment]
Hey @KevinD-87,

Just chiming in from the Serverless side, we should have a new Layer release very soon this week!

**Comment by KevinD-87** [comment]
> Hey @KevinD-87,
> 
> Just chiming in from the Serverless side, we should have a new Layer release very soon this week!

That's great news. Thanks!

**Comment by KevinD-87** [comment]
Hi @duncanista, I noticed there was a new v16 release that still uses a v2.x version of the dd-trace-dotnet package. Do you have any updates on a future version that will support a v3.x version of the dd-trace-dotnet package?
