### ISSUE TITLE
The latest Tracer agent causes errors in our docker container

### ISSUE THREAD

**Issue by ryanrivest** [DataDog/dd-trace-dotnet#6045]
**Describe the bug**
We ran into an issue with some deployments on 9/16 after we automatically installed the latest tracer agent that was released  (3.3.0).

When this version is installed, it causes some of our shell commands to return an error. For example, when we run `cat`, it fails with the following error:

>cat: symbol lookup error: /opt/datadog/continuousprofiler/Datadog.Linux.ApiWrapper.x64.so: undefined symbol: dlsym

When we switch back to 3.2.0, the error goes away. It also goes away if the dotnet runtime is updated to 8.0.

We're not quite ready to change to .NET 8, so it would be nice if this issue could be resolved with the .NET 6 container.

I've created a reprod for you here:  https://github.com/ryanrivest/dd-tracer-reprod/tree/main

**To Reproduce**
1. Run `docker build --file .\Dockerfile --tag ddtracer:test .`
2. Run `docker run --rm -it --entrypoint /bin/bash ddtracer:test`
3. Try to run `cat` or `clear`, and it should fail with the error below.

Error:
>cat: symbol lookup error: /opt/datadog/continuousprofiler/Datadog.Linux.ApiWrapper.x64.so: undefined symbol: dlsym

**Expected behavior**
No symbol lookup error when running commands.

**Runtime environment (please complete the following information):**
- Tracer version: 3.3.0
- Env: Docker
- CLR: .NET 6

**Comment by alvarovera-epam** [comment]
This also affecting our ECS Fargate containers, the health check fails due to this error. This is critical

**Comment by bouwkast** [comment]
Hi thanks a bunch for the issue and the repository to reproduce this @ryanrivest much appreciated.

For the time being would it be acceptable to revert to `3.2.0` of the .NET Tracer _or_ to disable the Continuous Profiler by setting `DD_PROFILING_ENABLED` set to `false` while we investigate this issue?

> It also goes away if the dotnet runtime is updated to 8.0.

Thanks for this bit of info as well as it'll likely help speed up the investigation.

Also, if necessary please don't hesitate to open a support ticket via Datadog Support here: https://help.datadoghq.com/hc/requests/new?tf_1260824651490=pt_product_type:apm&tf_1900004146284=pt_apm_language:.net

However, we are looking into this and I've looped in the Continuous Profilers folks to help.

**Comment by ryanrivest** [comment]
> Hi thanks a bunch for the issue and the repository to reproduce this @ryanrivest much appreciated.
> 
> For the time being would it be acceptable to revert to `3.2.0` of the .NET Tracer _or_ to disable the Continuous Profiler by setting `DD_PROFILING_ENABLED` set to `false` while we investigate this issue?

Yeah, we've reverted to 3.2.0 for now.. so that is acceptable while we wait for a fix. Thank you!

**Comment by bouwkast** [comment]
Hi @ryanrivest and @aljoveza,

We think we've identified the cause of this issue and are working on a hotfix for this as soon as we can. We will keep you posted on this though.

**Comment by andrewlock** [comment]
Hi @ryanrivest and @aljoveza,

We've just released 3.3.1 of the tracer which address the `dlsym` issue. If you could give it a try and confirm the issue is resolved for you. Thanks!

**Comment by ryanrivest** [comment]
It does appear to be fixed now. Thank you for the quick fix!
