### ISSUE TITLE
Asp.Net Core Automatic Instrumentation

### ISSUE THREAD

**Issue by mbcrawfo** [DataDog/dd-trace-dotnet#609]
Nuget has the Datadog.Trace.ClrProfiler.Managed package marked as deprecated with the note "Users who need ASP.NET instrumentation should reference the 'Datadog.Trace.AspNet' package."  However the only target supported by Datadog.Trace.AspNet is .Net Framework 4.5, so it can't be used with a .Net Core app.  Is this an oversight or is Asp.Net Core no longer supported for automatic instrumentation?

**Comment by lucaspimentel** [comment]
Hello, @mbcrawfo. All the files needed for automatic instrumentation in .NET Core are now included in the installer package, so the `Datadog.Trace.ClrProfiler.Managed` NuGet package is no longer required. In it's place, a new environment variable (`DD_DOTNET_TRACER_HOME`) was added so we can find the libraries at run time.

The `Datadog.Trace.AspNet` package is for ASP.NET instrumentation only, not ASP.NET Core.

If you have further questions, please [open a support ticket](https://docs.datadoghq.com/help/) and we'll pick things up from there.
