### ISSUE TITLE
AzureDevops SourceLink Url Incorrectly parsed

### ISSUE THREAD

**Issue by crystalworks** [DataDog/dd-trace-dotnet#6146]
**Describe the bug**
It appears that the TryParseSourceLinkUrl method utilised by the AzureDevOpsSourceLinkUrlParser is delivering the incorrect Url

e.g. 

this is picked up by sourcelink "https://dev.azure.com/organisation/project/_apis/git/repositories/example.shopping.api/items?api-version=1.0&versionType=commit&version=0e4d29442102e6cef1c271025d513c8b2187bcd6&path=/*"

and should give you 

https://dev.azure.com/organisation/project/_git/example.shopping.api

but instead it gives you

https://dev.azure.com/organisation/_git/repositories

This was identified whilst configuring DORA in DataDog, the spans/traces came in with the incorrect url. the datadog-ci metadata upload appears to be working correctly. 

**To Reproduce**
1. configure sourcelink with your project with APM configured from an ADO repo
2. inspect traces in datadog and look at git.repository.id or git.repository_url

Example project with the logic isolated showcasing the issue attached
[example.zip](https://github.com/user-attachments/files/17341594/example.zip)

**Expected behavior**
Expected behaviour is parser should correctly parse the url

**Screenshots**
![Image](https://github.com/user-attachments/assets/38418ca3-42d7-4012-88c1-3c6d92f36be0)

**Runtime environment (please complete the following information):**
- Instrumentation mode: [e.g. automatic with msi installer or manual with NuGet package]
- Tracer version: [e.g. 1.0.0]
- OS: [e.g. Windows Server 2012 R2 ]
- CLR: [e.g. .NET Framework 4.6.2, .NET Core 2.1]

**Additional context**
Noticed while configuring DORA CI

**Comment by crystalworks** [comment]
related to this PR

https://github.com/DataDog/dd-trace-dotnet/pull/3652

https://github.com/DataDog/dd-trace-dotnet/pull/3652/commits/3e2ac47b5e52a5ef689fa447be88622ab5a0ab27#diff-9b7b769acc04de52667882cc56cb573a001586d6837f834c6f6b69c29d307c19

**Comment by OmerRaviv** [comment]
@crystalworks Thank you for reporting this issue! I am investigating it and will keep you posted on our progress.

**Comment by crystalworks** [comment]
Hi @OmerRaviv 

Sorry to chase, any update on this? 

Thanks

**Comment by OmerRaviv** [comment]
Hi @crystalworks ! No worries. I am still actively working on this issue. Will post here once I have a PR ready.

**Comment by andrewlock** [comment]
Hi @crystalworks this should be fixed in v3.4.0. and v2.60.0, Thanks!
