### ISSUE TITLE
Log Correlation Injection Fails in Async Methods

### ISSUE THREAD

**Issue by d47id** [DataDog/dd-trace-dotnet#617]
**Describe the bug**
In async methods, log correlation ids are injected into any log messages that are written prior to the first await operator. After the first await operator, log correlation ids will be missing or zero.

**To Reproduce**
1. Create a sample application with an async method that uses a supported logging library (we use NLog).
2. Enable log injection via environment variable.
3. Observe that log messages emitted prior to any awaited async operations have log correlation ids.
4. Observe that log messages emitted after the first awaited async operation have missing or zero-valued log correlation identifiers.

**Expected behavior**
All log messages should contain log correlation identifiers with log injection enabled. 

**Runtime environment:**
- Instrumentation mode: manual/automatic hybrid with nuget package
- Tracer version: 1.7.0
- OS: linux
- CLR: observed on .NET Core 2.2 and .NET Core 3.1

**Comment by kevingosse** [comment]
Hello,

Do you still have the issue? I tried reproducing with 1.20.0 and couldn't:

```csharp
static async Task Main(string[] args)
{
    var logger = LogManager.GetLogger("Test");

    using (var scope = Tracer.Instance.StartActive("TestLogging"))
    {
        Console.WriteLine(scope.Span.SpanId);

        logger.Info("Before await");

        await Task.Delay(100).ConfigureAwait(false);

        logger.Info("After await");
    }
}
```
