### ISSUE TITLE
Exception "Could not load file or assembly mscorlib" when combined with <PublishTrimmed>true</PublishTrimmed>

### ISSUE THREAD

**Issue by owensearls** [DataDog/dd-trace-dotnet#618]
**Describe the bug**
After upgrading to .NET Core 3 I added the <PublishTrimmed>true</PublishTrimmed> attribute to my project file, after which my application started crashing with the following error while starting up

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

**To Reproduce**
With a working ASP.NET core project using the Datadog tracing 1.11.0 native library, add `<PublishTrimmed>true</PublishTrimmed>` attribute to your project file and try to start the application.

**Expected behavior**
The application launches, and tracing works.

**Screenshots**

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic
- Tracer version: 1.11.0
- OS: linux, docker image mcr.microsoft.com/dotnet/core/runtime:3.1
- CLR:.NET Core 3.1

**Additional context**
I also tried this with .NET Core 3.0, and had the same result.

**Comment by macrogreg** [comment]
Hi @owensearls ,

Our apologies for being slow about getting to this. :)
Do you have a full stack trace for the exception?

Thank you!

**Comment by owensearls** [comment]
Hi @macrogreg,

Thanks for taking a look at this! We have been happily using Datadog tracing without the publish trimmed setting, but I tested it again and got this stack trace. We are using version 1.16.2 of the tracing library now, and dotnet core 3.1.

Thanks,
Owen

```
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
at Microsoft.AspNetCore.Hosting.WebHostBuilder..ctor()
at Microsoft.AspNetCore.WebHost.CreateDefaultBuilder(String[] args)
at Lovepop.Firebolt.Api.Program.CreateWebHostBuilder(String[] args)
at Lovepop.Firebolt.Api.Program.Main(String[] args)
```

**Comment by macrogreg** [comment]
Thank you. @owensearls 
We are working on reducing the set of APIs that we depend on over the next few month. When that work is completed, the issue should go away. Given that you are OK with the workaround I will close it for now. However, please feel free to re-open if you disagree. :)

Cheers!

**Comment by ismail5701** [comment]
Is this issue fixed? I am still getting below error from [Release 1.26.3](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.26.3).

```sh
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(IHostBuilder builder, Action`1 configure)
   at API.Program.CreateHostBuilder(String[] args) in /src/API/Program.cs:line 17
   at API.Program.Main(String[] args) in /src/API/Program.cs:line 13
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command docker run --rm -it  -p 5000:5000/tcp api:latest" terminated with exit code: 1.
```
