### ISSUE TITLE
Thread Pool issues in .NET Core 3.1

### ISSUE THREAD

**Issue by RichardD012** [DataDog/dd-trace-dotnet#630]
**Description**
I'm not exactly sure how to describe the issue but hoping this is a jumping off point.  We've done a lot of work tuning our application and dealing with the .NET Thread Pool and the application was really stable.  We added the automatic instrumentation to our application, with a few manual span calls for dealing with our BE processing, and under low-load the application was fine. However, once we saw any sort of increase in load, we started having thread pool issues we had seen before.  This surfaced itself by causing timeout issues in Redis (we're using Stack Exchange).  Once we remove the profiling, everything resumed working as expected.  By any load, its >1000 rps per host.  We have multiple hosts load balanced and every single one of them failed so it wasn't an isolated server.  The system should easily be able to handle this.  

We dealt with issues in our own code before and it was weird blocking calls behind the scenes in async code that were causing thread pool exhaustion.

**Runtime environment:**
- Instrumentation mode: Automatic and Manual Instrumentation
- Tracer version: 1.11.1
- OS: Alpine Linux 3.7 in Docker 
- CLR: .Net 3.1

I realize this is vague but hoping there is some guidance here on resolving these issues or how I can help in tracking this down.  The tracing was really helpful in our application but the flakiness it introduced made it unusable.

**Comment by colin-higgins** [comment]
Hi @RichardD012 
One option for the time being is to explicitly disable the redis instrumentation, and then you can leave the rest in place.
You can do this by setting the environment variable like so: 
`DD_DISABLED_INTEGRATIONS` =  `ServiceStackRedis;StackExchangeRedis`
I put both redis integrations in there to illustrate that you may do multiple separated by semi-colon if you wish to.
Redis is obviously a much lighter weight call than something like an MVC request. An MVC request overall is much less affected, and redis is usually much more chatty.

**Comment by RichardD012** [comment]
FWIW we successfully did this but are definitely seeing issues with performance affected.  We have a support ticket opened with this and I know they're awaiting our feedback with some logging and debugging.  The problem is this really seems to affect us with production traffic so we have to pick and choose when we really want to potentially take a production hit to get the data we need.

**Comment by macrogreg** [comment]
The DiagnosticSource-Activity-focused collector prototyped here [avoids](https://github.com/DataDog/dd-trace-dotnet/tree/gregp/hack-a-dog-202007-diagnosticsource-activity/src/Datadog.Trace.ClrProfiler.Managed/ActivityBasedTracing) this issue. Let's keep this issue open to track the fact that is - for whichever reason - the Activity work stream stalls, we should still address this issue for the DD Span collector.

**Comment by macrogreg** [comment]
Internal tracker:
https://datadoghq.atlassian.net/browse/DOTNET-21

**Comment by dziedrius** [comment]
Any update on this? We're seeing strange behavior performance wise after adding DataDog APM too.

**Comment by RichardD012** [comment]
Not sure the latest from the DD side but I can safely say we're using `datadog-dotnet-apm-1.23.0-musl` with dotnet 5.0.103 on alpine 3.12 and haven't really run into any issues like the above lately. I don't want to say our issue is resolved because I'm not quite positive where the change may have happened but it definitely isn't as glaring, if present at all, as before (it would take itself down after about 30 minutes of high activity before).

**Comment by colin-higgins** [comment]
Hey @RichardD012 , checking in. Is this still an issue for you?

**Comment by RichardD012** [comment]
We're not seeing this issue at all anymore. I think whatever our specific use case was can be closed.
