### ISSUE TITLE
This is an inquiry for non-gac support for automatic instrumentation

### ISSUE THREAD

**Issue by kgorro** [DataDog/dd-trace-dotnet#633]
Does your profiler (Automatic instrumentation) works without using GAC for .NET framework?

**Comment by zacharycmontoya** [comment]
Hi @kgorro , yes the automatic instrumentation can work without using the GAC. In that scenario it will load the managed assemblies nested under the `DD_DOTNET_TRACER_HOME` directory.

**Comment by kgorro** [comment]
@zacharycmontoya , I tried to build this repository and set the DD_DOTNET_TRACER_HOME and i am having an error. It blows up in this method GetAssemblyAndSymbolsBytes() and it has a problem accessing Symbol size based on the log files I added to determine the crash point but this issue will occur only in x64 bit scenario.

**Comment by kevingosse** [comment]
Hello,

Sorry for leaving this issue unattended for so long. @kgorro are you still having the same problem?

**Comment by kgorro** [comment]
Hi,

@kevingosse , it is working on my end now.

**Comment by kevingosse** [comment]
Great! Closing this.
