### ISSUE TITLE
High memory usage observed when APM added

### ISSUE THREAD

**Issue by stevejgordon** [DataDog/dd-trace-dotnet#634]
**Describe the bug**
After enabling DataDog APM the memory uses by the container instance increases dramatically. Observed in two services during APM testing.

Both services have been stable in memory usage prior to adding and enabling APM.

**To Reproduce**
Update Dockerfile to include DataDog APM on ASP.NET Core 3.1 runtime image as base.

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true DOTNET_CLI_TELEMETRY_OPTOUT=1

# Install DataDog APM
RUN curl -LO https://github.com/DataDog/dd-trace-dotnet/releases/download/v1.12.0/datadog-dotnet-apm_1.12.0_amd64.deb
RUN dpkg -i ./datadog-dotnet-apm_1.12.0_amd64.deb

# Setup DataDog APM
ENV CORECLR_ENABLE_PROFILING=1 
ENV DD_LOGS_INJECTION=true 
ENV CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8} 
ENV CORECLR_PROFILER_PATH=/opt/datadog/Datadog.Trace.ClrProfiler.Native.so 
ENV DD_INTEGRATIONS=/opt/datadog/integrations.json 
ENV DD_DOTNET_TRACER_HOME=/opt/datadog 
ENV DD_DIAGNOSTIC_SOURCE_ENABLED=true 
```
The Datadog.Trace library is included in our project:

```
<PackageReference Include="Datadog.Trace" Version="1.12.0" />
```

Configure APM on startup within Program.cs

```csharp
var dataDogAgentServer = EcsHostInfo.HostIpV4;

var settings = TracerSettings.FromDefaultSources();

settings.ServiceName = configuration.GetValue<string>("DataDog:ApmServiceName");
settings.AgentUri = new Uri($"http://{dataDogAgentServer}:{configuration.GetValue<string>("DataDog:ApmPort")}", UriKind.Absolute);
settings.DebugEnabled = true;    

Tracer.Instance = new Tracer(settings);    
```

**Expected behavior**
Consistent memory usage.

**Screenshots**
![image](https://user-images.githubusercontent.com/3669103/73937266-92bbaf00-48dc-11ea-84fe-ebd7be5ee78c.png)

![image](https://user-images.githubusercontent.com/3669103/73937659-6d7b7080-48dd-11ea-8ec4-2325989b9097.png)

**Runtime environment**
- Instrumentation mode: datadog-dotnet-apm_1.12.0_amd64.deb installed into Docker image. Manual span in middleware. 
- Tracer version: 1.12.0
- OS: Debian 10 - Linux
- CLR: .NET Core 3.1

**Comment by lucaspimentel** [comment]
Hello, @stevejgordon. Thanks for reporting this issue. Can you create a [support ticket](https://docs.datadoghq.com/help/) so we can get some additional information from you? We would like to take a closer look at what your traces look like (in terms of number of traces, number of spans per trace, amount of metadata, etc). Please include a link to this GitHub issue in the ticket and ping me when it's created so I can follow up there.

In the meantime, we can try a few things:
- Is this a new issue with .NET Tracer 1.12.0, or did you see this happen in previous versions?
- Can you try disabling `DD_LOGS_INJECTION` and `DebugEnabled` to narrow down the issue to only the core instrumentation?
- Can you try setting `DD_CLR_DISABLE_OPTIMIZATIONS=false`? (see these comments [here](https://github.com/DataDog/dd-trace-dotnet/issues/302#issuecomment-496654196), [here](https://github.com/DataDog/dd-trace-dotnet/issues/302#issuecomment-498434529), and [here](https://github.com/DataDog/dd-trace-dotnet/issues/302#issuecomment-511011364) for more context on this switch)

**Comment by stevejgordon** [comment]
@lucaspimentel Thanks for the response. I'll get a support ticket opened.

I made your suggested changes and it's had a very minor impact.

This is the first time I've added the APM to this project. I needed this version for the Diagnostic Source changes, although those appear also broken per #632!

![image](https://user-images.githubusercontent.com/3669103/74242727-59b57d00-4cd6-11ea-869e-2c5c4ff50fdb.png)

**Comment by stevejgordon** [comment]
Ticket - 304865

**Comment by dan655t** [comment]
I would like to +1 this issue as we are unable to use the APM in production due to the performance impact.  We initially noticed high CPU when our app scaled out to about two times as many containers after enabling APM tracing.  After reading this post we're hypothesizing that the high CPU may be due to high memory forcing more intensive GC collect events.  

We started experimenting with the APM on 2/3:
<img width="1043" alt="Screen Shot 2020-02-07 at 10 32 26 AM" src="https://user-images.githubusercontent.com/10656337/74853035-5ab86100-530b-11ea-80c9-ec001939e63f.png">

We are running on the  mcr.microsoft.com/dotnet/core/runtime-deps:3.1 image.  The rest of our configuration is the same as the OPs.

**Comment by rlaveycal** [comment]
I also see high memory and CPU usage with the .Net framework ASP.Net integration when it is worked hard-ish.

I have a simple aspx page that returns the current time. Calling it from another PC in a continuous loop from a number of Powershell jobs (`start-job -ScriptBlock { while($true) { iwr http://test-server/heartbeat.aspx | out-null } }`) sends w3wp.exe CPU to 40% of an 8 core VM and memory just keeps climbing (2GB at present). Without APM memory is stable at 346MB

This is with MSI version 1.14.2 on .Net framework 4.7.1

The WCF integration doesn't seems to exhibit the same problem. Both CPU and memory remained flat (and low CPU) when the rest was repeated using a service info page (http://host/service.svc)

**Comment by andrewsouthard1** [comment]
Hey all - wanted to give this issue and update per @lucaspimentel PR that was submitted yesterday. 

We're actively working on reducing the performance overhead of the .NET tracer, this is one of many improvements we will be making over the coming weeks. This change specifically though, https://github.com/DataDog/dd-trace-dotnet/pull/685 we plan on adding to an official release by end of this week, once we have an updated release we encourage affected teams to update.

**Comment by andrewsouthard1** [comment]
Hey all -  as an update we have released version https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.16.0, this version includes https://github.com/DataDog/dd-trace-dotnet/pull/685 which focuses on reducing the number of heap allocations per trace - reducing memory usage in our core library. We will continue this effort in our next release, however I encourage all to update to the latest tracer and we'd definitely want to understand across your environments where any issues remain.

**Comment by rlaveycal** [comment]
Unfortunately I see no change when running under IIS / .Net framework.

**Comment by kevingosse** [comment]
Hello,

I'm sorry this issue has been pending for so long. I'll be actively looking at it, but first could you check if you're still seeing high memory usage with version 1.19.5?

We monitor memory usage internally, and you should expect a 30 to 50 MB overhead when using the tracer:

![image](https://user-images.githubusercontent.com/11140081/96263323-280e5780-0fc3-11eb-8684-9d3570164995.png)

Are you seeing a higher overhead than what we measure in our tests?

**Comment by rlaveycal** [comment]
@kevingosse I've re-run my test with .Net IIS / Framework. 1.19.4 does seem to have fixed the issue. w3wp.exe memory usage stays fairly constant.

1.19.5 doesn't work - I get no traces appearing in the UI. I'll raise a separate issue for that.

**Comment by kevingosse** [comment]
Great, thanks for the feedback!
