### ISSUE TITLE
When will MongoDB.Driver version 3 be supported?

### ISSUE THREAD

**Issue by kon-orfanou** [DataDog/dd-trace-dotnet#6345]
In the compatible Nuget versions that are listed [here](https://docs.datadoghq.com/tracing/trace_collection/compatibility/dotnet-core/#integrations), only MongoDB.Driver.Core is present and not MongoDB.Driver. 

Digging a bit deeper, in the json with the supported versions, [MongoDB.Driver](https://github.com/DataDog/dd-trace-dotnet/blob/467825fcda94d4f545e4a5575c39cb94f57b7d31/tracer/build/supported_versions.json#L806) is there but the `maxVersionSupportedInclusive` version is `2.30.0`. Version `3.0.0` is `maxVersionAvailableInclusive`. 

Could you please let me know whether version 3 will be soon supported?
After updating our system to the latest version we noticed that the mongoDB dependency disappeared in Datadog, for example it's not listed in the Downstream services in an APM, and there are no spans to mongoDB in Flame graphs.

Thank you!

**Comment by andrewlock** [comment]
Hi @kon-orfanou, sorry for the delay, this is on our radar and should be supported soon. We hope to have it implemented for the next release.
