### ISSUE TITLE
Automatic Instrumentation does not trace Microsoft.Data.SqlClient 

### ISSUE THREAD

**Issue by fehmianac** [DataDog/dd-trace-dotnet#645]
**Describe the bug**

When changing data adapter from System.Data.SqlClient to Microsoft.Data.SqlClient Tracer missing all DB transactions. We can not use Microsoft.Data.SqlClient for that reason. 

**Runtime environment (please complete the following information):**
- Instrumentation mode: Automatic
- Tracer version: 1.13.0
- OS: Ubuntu with Docker
- CLR: .NET Core 3.1

**Comment by lucaspimentel** [comment]
Thanks for the feedback, @fehmianac. Since this is basically the same sql client just moved to a different assembly/namespace, this should be pretty easy to implement.

**Comment by camp-007** [comment]
I ran into this same problem.  This is Microsoft's "go forward" package for the latest improvements in SqlClient.  Losing the Datadog automatic instrumentation is a big obstacle to being able to leverage the latest improvements with SqlClient.

This library is already on v2.  @lucaspimentel, any feedback on what Datadog's timeframe will be for supporting it?

https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/
https://devblogs.microsoft.com/azure-sql/microsoft-data-sqlclient-2-0-0-is-now-available/

**Comment by macrogreg** [comment]
Thanks for the submission. We are currently working in this.
As of now, we plan to ship support for this library in Net Core in the next few sprints, and for Net Fx some time later.

We will update this issue when we ship.

Internal trackers:
https://datadoghq.atlassian.net/browse/DOTNET-264
https://datadoghq.atlassian.net/browse/DOTNET-265

@lucaspimentel please take note.

**Comment by kevingosse** [comment]
Support for Microsoft.Data.SqlClient has been added [in 1.21.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.21.0).

Sorry for the wait!
