### ISSUE TITLE
Tracer causes IIS Application Pool to crash with IndexOutOfRangeException

### ISSUE THREAD

**Issue by mfields3** [DataDog/dd-trace-dotnet#653]
**Describe the bug**
The Datadog .NET Tracer causes an unhandled exception of w3wp.exe.
Event Viewer contains an entry which shows the following stack trace:
```
    Stack trace:    at System.Collections.Generic.HashSet`1.SetCapacity(Int32 newSize, Boolean forceNewHashCodes)
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at Datadog.Trace.AspNet.TracingHttpModule.Init(HttpApplication httpApplication)
   at System.Web.HttpApplication.InitModulesCommon()
   at System.Web.HttpApplication.InitInternal(HttpContext context, HttpApplicationState state, MethodInfo[] handlers)
   at System.Web.HttpApplicationFactory.GetNormalApplicationInstance(HttpContext context)
   at System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context)
```

**To Reproduce**
Unable to clearly determine if this only happens under load. Steps to reproduce the behavior:
1. Install the .NET Tracer
2. Hit the website with a significant number of requests to a basic/simple web page.
3. Wait for the app pool to crash - check Event Viewer for event ID 1309

**Expected behavior**
Datadog should not cause the app pool to crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/20926302/75054644-65b9ef80-54cb-11ea-9112-6fd9878fb7fe.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic with MSI installer
- Tracer version: 1.13.0 (installed MSI `datadog-dotnet-apm-1.13.0-x64.msi`)
- OS: Windows Server 2019
- CLR: .NET Framework 4.7.2

**Additional context**
Does not happen on our other web servers where the New Relic agent is installed, and we do not have New Relic installed on the machine where Datadog is installed.
HAProxy load balancer evenly routes traffic between our web servers.

**Comment by mfields3** [comment]
It appears the Tracer uses `HashSet`, however note that `HashSet` is not thread safe and this type of exception can occur in a multi-threaded environment.

**Comment by lucaspimentel** [comment]
Thanks for reporting this issue. It should be fixed in [.NET Tracer 1.13.2](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.13.2).
