### ISSUE TITLE
Assertion fails in Profiler when using Onixs FIX engine

### ISSUE THREAD

**Issue by rlaveycal** [DataDog/dd-trace-dotnet#663]
**Describe the bug**
When starting an application that uses the [Onixs FIX engine](https://www.onixs.biz/net-fix-engine.html) we get this dialog:

![image](https://user-images.githubusercontent.com/6595659/75440014-d1301100-5952-11ea-8794-60fbaf227043.png)

which is referring to https://github.com/DataDog/dd-trace-dotnet/blob/7aba67dc83acd709b9117268ec58bacb76e84cd7/src/Datadog.Trace.ClrProfiler.Native/il_rewriter.cpp#L349

We use version 3.24 of this library. It is build for specifically for x64 not MSIL. The library has been obfuscated.

NB: I'm not expecting a specific fix to make this work as tracing this app was a "nice to have". However this does indicate an underlying flaw in the native code. It would be better if it logged an error to the event log and disabled itself i.e. no tracing.

**To Reproduce**

The error is caused by creating a `FixmlConverter` as per the below
```c#
            try
            {
                Console.WriteLine("init engine");
                var engineSettings = new EngineSettings
                {
                    LicenseFile = "OnixS.lic"
                };
                Engine.Init(engineSettings);

                Console.WriteLine("create converter");
                var converter = new FixmlConverter(ProtocolVersion.FIX42);
                Console.WriteLine("after");
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
            }
```

**Expected behavior**
It doesn't crash

**Runtime environment (please complete the following information):**
- Instrumentation mode: MSI
- Tracer version: 1/13/2
- OS: Windows 10 1903; Windows 2016
- CLR: 4.8

**Comment by lucaspimentel** [comment]
Thanks, @rlaveycal. I agree that at this point in the profiler it is still possible to bail out and disable IL instrumentation instead of doing a hard `assert()`.

**Comment by lucaspimentel** [comment]
Hey, @rlaveycal. We have a PR (#708) ready to merge that removes all the `assert()` calls in the profiler code. Instead of asserting, we now return error `HRESULT` codes that are handled by skipping instrumentation for that method. This change will be included in the next release.

**Comment by lucaspimentel** [comment]
@rlaveycal: We released the fix for the failing `assert()` calls. The profiler now bails out from instrumenting that method instead of terminating the process. We're closing this ticket, but feel free to reopen if the issue persists.
