### ISSUE TITLE
Tracing Microsoft.Owin library OAuth endpoints

### ISSUE THREAD

**Issue by DavidJohnsonSN** [DataDog/dd-trace-dotnet#680]
**Describe the bug**
We have an ASP.NET application using Microsoft.Owin library to startup as described in https://docs.microsoft.com/en-us/aspnet/aspnet/overview/owin-and-katana/owin-startup-class-detection
On the `app` parameter we call the method `app.UseOAuthBearerTokens` with parameters that point to our classes to handle OAuth access and refresh token requests.
Our clients then make requests to the end points we configure.
Requests to these endpoints are not being picked up by the DataDog agent / packages. 
All other requests to our API using normal controllers work fine and we see them

**Expected behavior**
Requests to the access and refresh token endpoints when using Owin and Owin.OAuth are picked up and recorded in APM.

**Runtime environment (please complete the following information):**
- Instrumentation mode: msi installer
- Tracer version: 1.2.0
- OS: Windows Server 2016
- CLR: .NET Framework 4.6.2

**Comment by lucaspimentel** [comment]
Thanks, @DavidJohnsonSN! `Microsoft.Owin` servers and middle-ware are good candidates for new integrations.

**Comment by macrogreg** [comment]
Thank you for your submission, @DavidJohnsonSN !

I have added this to our backlog, and I will close this issue for now.
Please feel free to re-open if you have additional information that you would like to add.

If you are an existing customer and you are experiencing concrete hardship for the lack of this feature, could you please open a support case here:
https://www.datadoghq.com/support/

Our support team will work with you directly to see if there are any workarounds and to prioritize product improvements as appropriate.

Thanks!
