### ISSUE TITLE
Missing spans between 1.12.0 and 1.15.0

### ISSUE THREAD

**Issue by xfxf** [DataDog/dd-trace-dotnet#688]
**Describe the bug**
In 1.12.0, our ASP.NET application generates lots of useful traces (a single HTTP request will communicate through other ASP.NET application through a tiered architecture via bindings) .  Since upgrading to 1.15.0, we have lost a lot of information.

I believe this may be related to pull request #671 - it mentions:

"For ASP.NET applications (or other scenarios where LoaderOptimizationAttribute=MultiDomainHost), there may be missing spans from calls between framework assemblies. Affected integrations include:
HttpMessageHandler
WebRequest
Wcf (server)"

How can we get these traces back?  Attached are screenshots of a trace on 1.12.0, and the same endpoint on 1.15.0.

**Screenshots**
On 1.12.0:
![2020-03-29 20_48_44-](https://user-images.githubusercontent.com/138684/77998838-70df2580-737d-11ea-9ac7-88b75f9f0ef4.png)

On 1.15.0:
![2020-03-29 20_49_22-App Analytics _ Datadog](https://user-images.githubusercontent.com/138684/77998853-75a3d980-737d-11ea-862d-ac6566fc185c.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: Automatic with MSI installer, with relevant environment variables set.
- Tracer version: 1.15.0
- OS: Windows Server 2012 R2
- CLR: .NET Framework 4.7.2

**Comment by andrewsouthard1** [comment]
Hey @xfxf thanks for reporting this. We did indeed add this in the latest tracing client from the issue you linked as a preventative measure for that exception. However, to ensure you can use the latest tracing client, in the short term we are going to add a configuration setting to disable this while we address each integration with this new fix. We'll update this issue once that's available.

**Comment by xfxf** [comment]
Thankyou.  Was this change related any performance issues, would we expect a new release with this option disabled to be more performant than 1.12.0?  You can see the same request is significantly slower on 1.12.0 than is is on 1.15.0 (~4.49s vs 684ms), which is repeatable: but a lot of spans are generated (over 600).

**Comment by gc-dev1** [comment]
We are also having similar issues.
Already updated to 1.16.0 - still missing traces across services.
Please fix this... since tracing is pretty much useless at this point.

**Comment by lucaspimentel** [comment]
As @andrewsouthard1 mentioned above, in release 1.14.2 we added a stricter check for certain conditions what could cause exceptions to be raised if we attempt to instrument an assembly (see #671).

We have some users reporting that we are now causing some "false alarms" and disabling instrumentation automatically even when the user feels it would be safe to instrument. For those users, we are adding a setting to override the current behavior and force automatic instrumentation even if we detect what we consider a dangerous assembly to instrument (see #690). This setting will be available in the next tracer release.

For reference, the original exception that we were trying to avoid with this check is reported in #475 and #592.

**Comment by zacharycmontoya** [comment]
Hi everyone, in the latest [.NET Tracer 1.16.1](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.16.1) we added the flag `DD_TRACE_DOMAIN_NEUTRAL_INSTRUMENTATION` which you can set in your IIS environment to relax the strict check Lucas referred to in 1.14.2. Please make sure all of your Application Pools have at most one application, otherwise you may encounter the original issue.

We are continuing to investigate different integration points so that we can both have a strict check for reliable automatic instrumentation and also generate all of the spans from before. We'll keep you updated on developments here.

**Comment by xfxf** [comment]
Hi - we tried this, it didn't work.  1.16.2 also caused our processes to eat excess memory, so we've rolled back to 1.12.0 and admittedly am looking at alternative APM's now.

Is there any extra information I can provide.  Recent versions aren't usable for us and the traces the earlier versions provide are near useless.

**Comment by lucaspimentel** [comment]
@xfxf: We would like to work directly with you to determine why you lost those spans. Can you open a [support ticket](mailto:support@datadoghq.com)? Please reference this GitHub issue and include profiler logs from `%ProgramData%\Datadog .NET Tracer\logs`. If possible, [run the Tracer in debug mode](https://docs.datadoghq.com/tracing/troubleshooting/?tab=net#tracer-debug-mode) by setting `DD_TRACE_DEBUG=true` and restarting IIS.


> 1.16.2 also caused our processes to eat excess memory

We just released [1.17.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.17.0) which resolves the memory issue introduced in 1.16.2.

**Comment by zacharycmontoya** [comment]
Hi @xfxf , we've just released .NET Tracer 1.18.0 which should resolve the missing spans issue. Can you upgrade to this version and let us know if you are still experiencing this issue?

**Comment by lucaspimentel** [comment]
Closing this issue as resolved in 1.18.0. Feel free to reopen or create a new issue if needed.
