### ISSUE TITLE
Auto instrument asp.net winforms

### ISSUE THREAD

**Issue by chetanmangsuli84** [DataDog/dd-trace-dotnet#703]
Currently asp.net web application is not getting instrumented. Only AspNetHttpModule methods are getting instrumented other methods like AdoNet ,Caching methods are not getting instrumented even after adding the reference to Datadog.Trace.ClrProfiler.Managed.dll and creating the default Environement Variables.

**To Reproduce**
1. Create a asp.net winform application
2. Add a simple Db statement for SqlSever using dbCommand like insert or select
3. When we execute the Db Statement in step2 the db calls are not getting instrumented although same method works fine in .netcore MVC applications.

**Comment by andrewsouthard1** [comment]
Hey @chetanmangsuli84 - can you open a ticket with our support team and we'll be able to take a closer look? You can email them at support@datadoghq.com
