### ISSUE TITLE
ASP.NET integration captures HttpException with 404 status code

### ISSUE THREAD

**Issue by kendallb** [DataDog/dd-trace-dotnet#718]
**Describe the bug**
It is quite common in ASP.NET code to throw an HttpException(404, "Not Found") when buried deep in code when you decide a page should not exist, which then gets handled by the system wide 404 handler. However with DataDog, since the ASP.NET exception handler always logs all exceptions, those all end up in our traces which is quite annoying.

**To Reproduce**
Just add

```
    throw new HttpException(404, "Not Found");
```

anywhere in a controller, and you will notice it gets logged in the traces. Makes the trace look like it errored out, but a 404 is NOT an error.

**Expected behavior**
404 errors should be ignored

**Comment by kendallb** [comment]
I would write my own HttpModule integration to avoid this, but alas it was decided to bundle that with the core DataDog tracer library now, so I get it all no matter what. I could change the implementation and use my own custom library, but I would rather this gets fixed upstream.

My suggestion would be to simply ignore 404 exceptions in the OnError handler for the HttpModule.

**Comment by lucaspimentel** [comment]
@kendallb: your fix for this issue was included in [release 1.17.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.17.0). Thanks!

**Comment by kendallb** [comment]
Hmm, we are using 1.17 (about to upgrade to the latest now), and I am still seeing this? Might need to debug this again as I am not sure why we are still getting 404's logged. Got any ideas and where these are coming from?

We have a global, custom error handler in our code to catch the 404 and then render the appropriate page, like this one:

https://www.nashbar.com/answer-mini-crank-black-ck-ack15m-p/p1157261?v=1153012

![image](https://user-images.githubusercontent.com/535825/102946109-7f71ed80-4474-11eb-9e60-393ed0c26c39.png)
