### ISSUE TITLE
Sql Server spans missing between 1.11.0 and 1.16.2

### ISSUE THREAD

**Issue by jesanfafon** [DataDog/dd-trace-dotnet#722]
**Describe the bug**
We have an ASP.NET app with many legacy components. SQL queries made from the Microsoft.Practices.EnterpriseLibrary.Data library are not traced in 1.14.2 and later. I believe the reason for this is the same reasons discussed in #688 . However, adding the `DD_TRACE_DOMAIN_NEUTRAL_INSTRUMENTATION` environment variable didn't restore the spans in our traces, so I wonder if there's something else going on here.

**To Reproduce**
1. Install [Microsoft.Practices.EnterpriseLibrary.Data](https://www.nuget.org/packages/EnterpriseLibrary.Data/) and make a query
2. Observe the sql query is not traced.

**Expected behavior**
Queries going to sql server should be traced regardless of the library making the ADO.NET calls

**Runtime environment (please complete the following information):**
- Instrumentation mode: Mixed
- Tracer version: 1.16.2
- OS: Windows Server 2012 R2
- CLR: .NET Framework 4.8, app targets .NET Framework 4.6.2

**Additional context**
We're weighing the option of rewriting the code we have using the EPL to use plain ADO.NET instead, since the degree of change to do that is relatively minor. I wanted to file this bug, though, so that you guys know about it 😄

**Comment by zacharycmontoya** [comment]
Hi @jesanfafon , thanks for reporting this. We've just released version [1.18.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.18.0) which should address this issue. Can you upgrade to this version and let us know if you're still seeing this issue?

**Comment by jesanfafon** [comment]
Hi @zacharycmontoya 1.18.0 fixes the issue for us! Thank you very much!
