### ISSUE TITLE
Spans created using OpenTracingTracer not activated with Datadog ScopeManager

### ISSUE THREAD

**Issue by kc0isg** [DataDog/dd-trace-dotnet#724]
**Describe the bug**
After creating and activating a span using the `OpenTracingTracer`, it is activated using the `OpenTracing.IScopeManager`.  However the wrapped `Datadog.Trace.Span` is not activated with the datadog scope manager.  Because of this, an OpenTracing span can never be a parent to a datadog span.

When I manually called `Activate` on the datadog scope manager with the wrapped `Datadog.Trace.Span`, I am successfully able to have an `OpenTracingSpan` as a parent of a datadog span.

**To Reproduce**
1. Create the Datadog Tracer
2. Create the `OpenTrackingTracer` using `OpenTracingTracerFactory.WrapTracer(...)`
3. Create and activate a span using the OpenTracing Tracer
4. Create and activate a span using the Datadog Tracer
5. Observe the OpenTracing Span has a different `TraceId` than the Datadog Span

**Expected behavior**
I would expect that when I create an OpenTracing span then a `Datadog.Trace.Span` in the same method call that they would both have the same `TraceId`.  Simiarly I would also expect automatic instrumentation to pick up any currently active OpenTracing spans as well.

I would also expect that when you call `StartActive` on the OpenTracing Span, both it and the wrapped `Datadog.Trace.Span` would get activated with their respective scope managers.

**Runtime environment (please complete the following information):**
- Instrumentation mode: Using both automatic and manual instrumentation
- Tracer version: 1.16.2
- OS: Windows 10 Pro 1903
- CLR: .Net Core 3.1.101

**Additional context**
Below is the code I am using to create the two different spans.  When I run this code I get two different traces in the datadog ui.
```csharp
public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, 
    CancellationToken cancellationToken = new CancellationToken())
{
    using var openTracingScope = GlobalTracer.Instance
        .BuildSpan("CheckHealthAsync")
        .StartActive();

    using var ddScope = Tracer.Instance.StartActive($"HttpHealthCheck::GET {_requestUri.ToString()}");

    var healthCheckData = new Dictionary<string, object>();

    try
    {
        healthCheckData.Add("url", _requestUri.ToString());
        using var client = _httpClientFactory.CreateClient(context.Registration.Name);
        var checkResponse = await client
            .GetAsync(_requestUri, HttpCompletionOption.ResponseHeadersRead, cancellationToken)
            .ConfigureAwait(false);

        healthCheckData.Add("statusCode", checkResponse.StatusCode.ToString());

        if (checkResponse.IsSuccessStatusCode)
        {
            return HealthCheckResult.Healthy(data: healthCheckData);
        }

        healthCheckData.Add("content", await checkResponse.Content.ReadAsStringAsync());

        return new HealthCheckResult(context.Registration.FailureStatus,
            $"Endpoint is not responding with 200 OK, the current status is {checkResponse.StatusCode}",
            data: healthCheckData);
    }
    catch (Exception ex)
    {
        ddScope.Span.SetTag("error", "true");
        return new HealthCheckResult(context.Registration.FailureStatus,
            "Exception occured while processing health check", ex, healthCheckData);
    }
}
```

When I manually call `Activate` on the scope manager using reflection using this code, I a single trace in the datadog ui.  Note I am actually creating another OpenTracing Span a few calls up in the stack which is why there are 4 spans shown in the trace.  The first two being the OpenTracing Spans and the second two are the Datadog Spans (Manual and Automatic on `HttpClient`).
```csharp
public async Task<HealthCheckResult> CheckHealthAsyncReflection(HealthCheckContext context, 
    CancellationToken cancellationToken = new CancellationToken())
{

    var ddScopeManager = typeof(Tracer)
        .GetField("_scopeManager", BindingFlags.NonPublic | BindingFlags.Instance)
        .GetValue(Tracer.Instance);

    using var openTracingScope = GlobalTracer.Instance
        .BuildSpan("CheckHealthAsync")
        .StartActive();

    var ddSpan = openTracingScope.Span.GetType()
        .GetProperty("Span", BindingFlags.NonPublic | BindingFlags.Instance)
        .GetValue(openTracingScope.Span);

    ddScopeManager.GetType().GetMethod("Activate")
        .Invoke(ddScopeManager, new object[] { ddSpan, true });

    using var ddScope = Tracer.Instance.StartActive($"HttpHealthCheck GET {_requestUri.ToString()}");

    var healthCheckData = new Dictionary<string, object>();

    try
    {
        healthCheckData.Add("url", _requestUri.ToString());
        using var client = _httpClientFactory.CreateClient(context.Registration.Name);
        var checkResponse = await client
            .GetAsync(_requestUri, HttpCompletionOption.ResponseHeadersRead, cancellationToken)
            .ConfigureAwait(false);

        healthCheckData.Add("statusCode", checkResponse.StatusCode.ToString());

        if (checkResponse.IsSuccessStatusCode)
        {
            return HealthCheckResult.Healthy(data: healthCheckData);
        }

        healthCheckData.Add("content", await checkResponse.Content.ReadAsStringAsync());

        return new HealthCheckResult(context.Registration.FailureStatus,
            $"Endpoint is not responding with 200 OK, the current status is {checkResponse.StatusCode}",
            data: healthCheckData);
    }
    catch (Exception ex)
    {
        ddScope.Span.SetTag("error", "true");
        return new HealthCheckResult(context.Registration.FailureStatus,
            "Exception occured while processing health check", ex, healthCheckData);
    }
}
```
![image](https://user-images.githubusercontent.com/5272058/81591903-c3e7c780-9382-11ea-92bd-d90d62669eb1.png)

**Comment by lucaspimentel** [comment]
Thanks for the detailed report, @kc0isg. This is a known issue. Our OpenTracing support wasn't designed to be mixed with `Datadog.Trace.Tracer`. Three is a similar issue that occurs if you mix different versions of the automatic and manual instrumentation libraries, because they also end up using different ScopeManagers.

We intend to support both of these scenarios and we are currently thinking of ways to achieve this. You can see some related work in #635, which is actively being worked on. At the moment we cannot provide a timeline for this.

**Comment by kc0isg** [comment]
Thanks for the information.  I was experimenting and was able to get things working the way I expected by creating an `OpenTracing.IScopeManager` and `OpenTracing.IScope` that basically wrapped the datadog counter parts and then updated the `OpenTracingSpanBuilder` to use the Datadog `ScopeManager`.  You can see my changes in my fork [here](https://github.com/DataDog/dd-trace-dotnet/compare/master...kc0isg:master).  Unfortunately due to the way the access modifiers are set on some of the properties on the datadog Scope and Spans it isn't actually possible to implement this outside of the datadog specific libraries.

**Comment by macrogreg** [comment]
This issue and https://github.com/DataDog/dd-trace-dotnet/issues/797 are very related. Essentially, all of the 3 should come together in a coherent hierarchy within a single trace:
 - Spans created by auto-instrumentation;
 - Spans created via the Open Tracing APIs;
 - Spans created via the Datadog trace APIs.

The fact that Open Tracing spans do not slot into there - is that a bug or a new-feature-request? It depends on your perspective. Given our history it is a feature-request. Years ago, we supported Open Tracing before we had auto-instrumentation. Once auto-instrumentation became the heart of the product, the "glue" was never added.

Please note that Open Tracing has been superseded by Open Telemetry (OTel). We are currently working on OTel support and once that is available you will be able to mix custom spans emitted using OTel APIs, custom spans using .NET Activity APIs, and auto-instrumentation. In the meantime, you can use Datadog's Trace APIs to mix custom spans and auto-instrumentation spans.

With this context I will close this issue for now. Please feel to re-open and comment if you disagree or have questions.

Thank you!
