### ISSUE TITLE
1.16.2 causing excessive increase in RAM usage in injected processes

### ISSUE THREAD

**Issue by Ij8rx97V2m** [DataDog/dd-trace-dotnet#726]
**Describe the bug**
After upgrading from `1.10.0` to `1.16.2`, the tracing agent is causing `w3wp.exe` processes to consume more memory; nearly double what they would normally use.

**To Reproduce**
1. Install `1.16.2`
2. Add `DD_TRACE_DOMAIN_NEUTRAL_INSTRUMENTATION` as a System environment variable with the value `true`
3. Restart relevant IIS sites

**Expected behavior**
The tracing agent should not be causing memory usage to increase so substantially.

**Screenshots**
w3wp.exe process with 1.16.2:
![image](https://user-images.githubusercontent.com/65320905/81883644-1ae6da00-95d9-11ea-987e-1e894336f057.png)

w3wp.exe process with 1.10.0:
![image](https://user-images.githubusercontent.com/65320905/81882701-b7f44380-95d6-11ea-99fc-50abbaab43bc.png)

**Runtime environment:**
- Instrumentation mode: Automatic
- Tracer version: 1.16.2
- OS: Windows Server 2012 R2
- CLR: .NET Framework 4.7.2

**Additional context**
We have since reverted to `1.10.0`.

We only have 1 site per application pool.

**Comment by lucaspimentel** [comment]
Closing this as fixed in [1.17.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.17.0).
