### ISSUE TITLE
Support automatic instrumentation for System.Data.Odbc on dotnet core

### ISSUE THREAD

**Issue by nikkeeOwl** [DataDog/dd-trace-dotnet#736]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
I would like to request automatic instrumentation for:
- Framework and library: .NETStandard 2.0 System.Data.Odbc
- Library type: Database connector
- Library version: 4.7.0

**Is your feature request related to a problem? Please describe.**
On Linux with dd-trace-dotnet version 1.17.0 DataDog is not collecting dotnet core 3.1 application's Redshift traffic. The traffic goes through odbc library and it would be nice if this was supported by automatic instrumentation to avoid manual coding.

**Describe the solution you'd like**
Add support automatic instrumentation for the library.

**Comment by macrogreg** [comment]
Thank you for the submission, @nikkeeOwl .

I have added this to our backlog and will close this issue for now.
Please feel free to re-open if you have additional information you would like to add.

If you are an existing customer and you are experiencing concrete hardship for the lack of this feature, could you please open a support case here:
https://www.datadoghq.com/support/

Our support team will work with you directly to see if there are any workarounds and to prioritize product improvements as appropriate.

Thanks!
