### ISSUE TITLE
System.ValueTuple 4.0.3.0 incorrectly installed in GAC

### ISSUE THREAD

**Issue by pergardebrink** [DataDog/dd-trace-dotnet#752]
**Describe the bug**
Datadog APM .NET Tracer incorrectly installs System.ValueTuple 4.0.3.0 in GAC

**To Reproduce**
1. Install DataDog APM Tracing agent
2. Create a .NET project targeting .NET 4.8 (running on a machine with .NET Framework 4.8)
3. Add two NuGet package that requires System.ValueTuple in two different version ranges (like MoreLinq and Microsoft.Extensions.Hosting)
4. Use code dependent indirectly on ValueType (like Partition in MoreLinq) from Program.cs
5. Create a release build (dotnet publish -c Release -o publish)... (Important, otherwise the binding redirects won't be created)
6. Verify that the <projectname>.exe.config contains assembly redirects for System.ValueTuple 0.0.0.0-4.0.3.0 => 4.0.3.0
6. Run the application from the release build

**Expected behavior**
It should work, but gives "Method not found":
```
Unhandled Exception: System.MissingMethodException: Method not found: 'System.ValueTuple`2<System.Collections.Generic.IEnumerable`1<!!0>,System.Collections.Generic.IEnumerable`1<!!0>> MoreLinq.Extensions.PartitionExtension.Partition(System.Collections.Generic.IEnumerable`1<!!0>, System.Func`2<!!0,Boolean>)'.
   at vt.Program.Main(String[] args)
```

This seems to be because the assembly redirect causes it to load the GAC version from DataDog.

**Runtime environment:**
- Instrumentation mode: [e.g. automatic with msi installer]
- Tracer version: [e.g. 1.7.0]
- OS: [Windows 10/Windows Server 2019 ]
- CLR: [e.g. .NET Framework 4.8]

**Additional context**
DataDog agent should, as far as I know never install this dll in GAC.

**Comment by pergardebrink** [comment]
Example program and csproj: 
```

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="3.1.5" />
    <PackageReference Include="morelinq" Version="3.3.2" />
  </ItemGroup>

</Project>
```
```
class Program
    {
        static void Main(string[] args)
        {
            var ranges = Enumerable.Range(0, 100).Partition(x => x > 50);
            Console.WriteLine("Hello World!");
        }
    }
```

**Comment by lucaspimentel** [comment]
@pergardebrink: Thanks for reporting this and for the clear repro.

**Comment by pergardebrink** [comment]
> @pergardebrink: Thanks for reporting this and for the clear repro.

No problem, please let me know if you need more information, or if you are unable to reproduce the issue!

I looked at the https://github.com/DataDog/dd-trace-dotnet/blob/master/deploy/Datadog.Trace.ClrProfiler.WindowsInstaller/Files.Managed.Net45.GAC.wxs and I see that there are some more files added as well into the GAC, so not sure if any of these could potentially cause a similar error?

**Comment by macrogreg** [comment]
We are currently working on removing several dependencies from the tracer, so this issue should go away in one of the upcoming releases. Are you currently blocked, or do you have a workaround that is temporary acceptable?

If you do not have a workaround, can you please create a ticket by emailing our support team and mention this GitHub issue in your request (see https://www.datadoghq.com/support/ )? They will help you figuring out a temporary workaround while we are working on a permanent fix.

In the meantime, I will close the issue.

**Comment by lucaspimentel** [comment]
@pergardebrink: we removed the dependency in #806 and the change was included in [release 1.19.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v1.19.0). We no longer install `System.ValueTuple.dll` into the GAC.

**Comment by marcioalthmann** [comment]
Hello, I have the same problem with System.Threading.Tasks.ValueTask. This error occurred yesterday during the Datadog tests.

`System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<System.ValueTuple`2<Boolean,System.Collections.Generic.IReadOnlyList`1<RelampagoMarquinhos.Model.Consulta.SP.TipoSubservicoDetranSPDto>>> RelampagoMarquinhos.Client.Endpoints.SP.EndpointTipoSubServicoDetranSP.TodosAsync()'.
  File "C:\TeamCity\buildAgent2\work\29d00ba58a77456a\PagueVeloz.Servicos\DebitosVeiculares\TabelaCService.cs", line 115, col 9, in ObterCamposAsync
    Void MoveNext()
  Module "System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1", in Start
  Module "PagueVeloz.Servicos.DebitosVeiculares.TabelaCService", in ObterCamposAsync
  File "C:\TeamCity\buildAgent2\work\29d00ba58a77456a\PagueVeloz\ControllersApi\V1\Transito\SP\Despachantes\PagamentosDespachantesController.cs", line 195, col 13, in GetServicos
    Void MoveNext()
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Threading.Tasks.TaskHelpersExtensions+<CastToObject>d__1`1", in MoveNext
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  Module "System.Runtime.CompilerServices.TaskAwaiter", in ThrowForNonSuccess
  Module "System.Runtime.CompilerServices.TaskAwaiter", in HandleNonSuccessAndDebuggerNotification
  Module "System.Web.Http.Controllers.ApiControllerActionInvoker", in InvokeActionAsyncCore
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw`

**Comment by IrisClasson** [comment]
We seem to be having problems with another assembly now,  System.Diagnostics.DiagnosticSource. Is there an issue on GitHub for that (and other assemblies) so we can see how much progress has been made? We seem to be spending a lot of time trying to track down these problems.
