### ISSUE TITLE
Context Propagation of a WCF request needs support for TCP Transport 

### ISSUE THREAD

**Issue by maheshsikakolli** [DataDog/dd-trace-dotnet#757]
Hi Datadog Team,

we have a WCF service which is Running with TCP Transport, It looks like currently, context Propogation happens only through Http Transport. 

This is blocking me to connect the spans by sending headers in each request of a  WCF TCP endpoint.

can you support this in the .DotNet Tracer for WCF Integration?

regards
Mahesh

**Comment by macrogreg** [comment]
Hi @maheshsikakolli ,

Thank you for your submission. You are right in your analysis. Currently, this is not supported.
I have added your submission to our backlog for future prioritization.

Please note that in the meantime you can propagate TraceId and SpanId as a part of your message and manually set it on the other end of the communication.

I will close this issue for now.
However, if you are an existing customer and you have a business scenario that is blocked by the lack of this feature, please reopen this issue and tag me directly. We will then start a customer support process to make sure you get the help you need quickly.

Thank you!

**Comment by maheshsikakolli** [comment]
Hi Guys,

I solved this case differently by creating spans and linking to the traces. Thanks


Regards,
Mahesh Sikakolli
Architect, GCRT
Thomson Reuters
(the answer company)
Phone: +914067323036

**Comment by macrogreg** [comment]
Thanks for closing the loop, @maheshsikakolli !
