### ISSUE TITLE
Custom Tags Propagation with in a Process

### ISSUE THREAD

**Issue by maheshsikakolli** [DataDog/dd-trace-dotnet#758]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : .net Framework
- Library type: Web, ache, http-request
- Library version: latest

**Is your feature request related to a problem? Please describe.**
HI , currently I am adding my custom tags to the top Span which is created by automatic instrumentation.  I would like these tags to be propagated to all other spans generated by different integrations with the scope, so all my spans have the same custom tags. 

**Describe the solution you'd like**
Please support the method like 
.AddTag(tagname,value,propogation:true)

**Comment by macrogreg** [comment]
Hi @maheshsikakolli 
Could you please describe your use case? What would you like to use the tags for?

Thank you!

**Comment by macrogreg** [comment]
Hi @maheshsikakolli ,

Have not head back from you in a while. I will close this issue for now, but please feel free to get back to us with additional information and to reopen the issue.

**Comment by maheshsikakolli** [comment]
HI,

I am trying to add custom tags to a span that is created by auto instrumentation. The custom tags that we add is only applicable to the current span. All the integrations spans that are created under the parent span will not get these tags. So we want a feature to add the tags once and then propagate them to all the integration traces. It's like Global tags, but we want to add the global tag differently for different requests. Like userid, clientID, we want to add to parent span, and Datadog should add it to all the child span tags. so i am looking like 

.AddTag(tagname,value,**propogation:true**)

Let me know if this feature is already available ?
