### ISSUE TITLE
Tracer not working on Windows Server

### ISSUE THREAD

**Issue by nsaud-skysync** [DataDog/dd-trace-dotnet#765]
**Describe the bug**
After following the guide here (https://docs.datadoghq.com/tracing/setup/dotnet-core/?tab=environmentvariables) I am unable to trace my .NET Core application on a Windows Server. Installed version of the tracer is 1.17.0.

**To Reproduce**
I've setup the following environment variables:

![image](https://user-images.githubusercontent.com/57451779/85559809-0d6d3880-b5f8-11ea-960d-372f0296fbb8.png)

![image](https://user-images.githubusercontent.com/57451779/85559930-2d046100-b5f8-11ea-80c0-6bac05b71892.png)

Setup a datadog.json file in root of application directory:
![image](https://user-images.githubusercontent.com/57451779/85560008-3f7e9a80-b5f8-11ea-8bce-e4411c4ecb3c.png)

**Expected behavior**
Expecting that tracer sends apm traces to dd agent.

![image](https://user-images.githubusercontent.com/57451779/85560530-bcaa0f80-b5f8-11ea-9516-f373a842fd5f.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: [e.g. automatic with msi installer or manual with NuGet package]
- Tracer version: 1.17.0
- OS: Windows Server 2019
- CLR: .NET Core 3.1.2

Am I missing something? Thanks for the help.

**Comment by lucaspimentel** [comment]
@nsaud-skysync: can you open a ticket with our support team and we'll be able to take a closer look? You can email them at support@datadoghq.com.
