### ISSUE TITLE
OpenTracing implementation does not take into account the active span.

### ISSUE THREAD

**Issue by jinek** [DataDog/dd-trace-dotnet#797]
**Describe the bug**
OpenTracing Datadog implementation does not see the span created by automatic instrumentation.
Thus, result span does not have parent span created automatically.

**To Reproduce**
![image](https://user-images.githubusercontent.com/10516222/87311786-fb5c2700-c51f-11ea-8c11-06d54a034b50.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic with msi installer and manual with NuGet package

**Comment by KyleMillsSE** [comment]
Is it possible to pro grammatically attach new spans to the span created by the automatic instrumentation rather then rely on the implicit ChildOf to work, which seems to be not working?

**Comment by jinek** [comment]
I have used it implicitly, but without opentracing. Most important is that version of datadog tracer needs to match the nuget version

**Comment by macrogreg** [comment]
Hi @jinek ,

Thank you for the submission.

> I have used it implicitly, but without opentracing. Most important is that version of datadog tracer needs to match the nuget version

This is correct. Do you still experience this problem when the Datadog.Trace versions referenced by your application and by the Tracer match?

**Comment by macrogreg** [comment]
This issue and https://github.com/DataDog/dd-trace-dotnet/issues/724 are very related. Essentially, all of the 3 should come together in a coherent hierarchy within a single trace:
 - Spans created by auto-instrumentation;
 - Spans created via the Open Tracing APIs;
 - Spans created via the Datadog trace APIs.

The fact that Open Tracing spans do not slot into there - is that a bug or a new-feature-request? It depends on your perspective. Given our history it is a feature-request. Years ago, we supported Open Tracing before we had auto-instrumentation. Once auto-instrumentation became the heart of the product, the "glue" was never added.

Please note that Open Tracing has been superseded by Open Telemetry (OTel). We are currently working on OTel support and once that is available you will be able to mix custom spans emitted using OTel APIs, custom spans using .NET Activity APIs, and auto-instrumentation. In the meantime, you can use Datadog's Trace APIs to mix custom spans and auto-instrumentation spans.

With this context I will close this issue for now. Please feel to re-open and comment if you disagree or have questions.

Thank you!
