### ISSUE TITLE
Different versions of datadog loaded into one AppDomain

### ISSUE THREAD

**Issue by jinek** [DataDog/dd-trace-dotnet#800]
**Describe the bug**
When datadog's profiler loads Datadog assembly of version 1.18.0 and application itself references 1.18.2 then two different versions of same type **Datadog.Traces.Tracer** are loaded. Which results in non-correlated spans.

![image](https://user-images.githubusercontent.com/10516222/87348444-02515c80-c555-11ea-8d8b-8dd759ea73ed.png)
![image](https://user-images.githubusercontent.com/10516222/87348456-08dfd400-c555-11ea-8112-e47f23db45ca.png)

I believe exact version of dotNET and datadog don't matter in this case.

**Comment by macrogreg** [comment]
Hi @jinek ,

Thank you for your submission. 
Currently, it is required that the application uses a  Datadog.Trace version that exactly matches the version used by the auto-instrumentation tracer. Going forward we will use .NET native Activity APIs in a way that does not suffer from this issue.

Please see here:
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/13

I will close this issue for now. However, please feel free to re-open if you have any additional questions or comments.

**Comment by jinek** [comment]
@macrogreg Can I try to fix it for current implementation?

**Comment by macrogreg** [comment]
Ping @lucaspimentel who was planning to look into this in the upcoming future.
