### ISSUE TITLE
DataDog.Trace 1.18.3 Not Compatible with Latest MessagePack nuget package.

### ISSUE THREAD

**Issue by boost1231** [DataDog/dd-trace-dotnet#819]
**Describe the bug**
We were running DataDog.Trace 1.14.2 with MessagePack version 2.1.90 in a .net core 3.1 application. After updating DataDog.Trace to 1.18.3, the following exception was thrown:
```
System.TypeInitializationException: The type initializer for 'Datadog.Trace.Tracer' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Datadog.Trace.Agent.MessagePack.SpanFormatterResolver' threw an exception.
 ---> System.TypeLoadException: Method 'Serialize' in type 'Datadog.Trace.Agent.MessagePack.SpanMessagePackFormatter' from assembly 'Datadog.Trace, Version=1.18.3.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb' does not have an implementation.
   at Datadog.Trace.Agent.MessagePack.SpanFormatterResolver..cctor()
   --- End of inner exception stack trace ---
   at Datadog.Trace.Agent.Api..ctor(Uri baseEndpoint, IApiRequestFactory apiRequestFactory, IStatsd statsd)
   at Datadog.Trace.Tracer..ctor(TracerSettings settings, IAgentWriter agentWriter, ISampler sampler, IScopeManager scopeManager, IStatsd statsd)
   at Datadog.Trace.Tracer..ctor()
   at Datadog.Trace.Tracer..cctor()
   --- End of inner exception stack trace ---
   at Datadog.Trace.Tracer.get_Instance()
   at NetCoreConsoleApp1.Program.Main(String[] args) in C:\Users\md032p\Documents\Experiments\NetCoreConsoleApp1\NetCoreConsoleApp1\Program.cs:line 20
```

It seems like DataDog.Trace 1.18.3 only works with MessagePack 1.9.11.

**To Reproduce**

It can be reproduced by creating a .netcore 3.1 console app with DataDog.Trace 1.18.3 and MessagePack 2.1.90. Then add the following code:
```
using (var scope = Tracer.Instance.StartActive("test"))
{
}
```
and run.

**Expected behavior**
No exception thrown.

**Screenshots**

**Runtime environment (please complete the following information):**
- Instrumentation mode: manual with NuGet package
- Tracer version: 1.18.3
- OS: Windows 10, Centos 7 
- CLR: .netcore 3.1

**Additional context**

**Comment by lucaspimentel** [comment]
Thanks, @boost1231. We are aware of this dependency issue and are currently working on resolving it. See #806.

**Comment by boost1231** [comment]
Great, thanks!
