### ISSUE TITLE
ITracer.Extract(BuiltinFormats.TextMap, new TextMapExtractAdapter(headers)); Doesnt work

### ISSUE THREAD

**Issue by Johnsonxd4** [DataDog/dd-trace-dotnet#821]
I did the configuration as the documentation says:
`
ITracer tracer = OpenTracingTracerFactory.CreateTracer();
            collection.AddSingleton<ITracer>(tracer);
            GlobalTracer.Register(tracer);
`
But when i try to extract the headers to send with rabbitmq message, the _tracer.ScopeManager.Active is null.
I'm using the method 
`var obj = new Dictionary<string, string>();
var newCallHeaders = new TextMapInjectAdapter(obj);
 _tracer.Inject(_tracer.ScopeManager.Active.Span.Context, BuiltinFormats.TextMap, newCallHeaders);`

`_tracer` is a implementation of ITracer from opentracing lib.

To reproduce this, create an aspnet core application using the configuration above to setup the opentracing.
The `_tracer.ScopeManager.Active.Span.Context` should return null

![image](https://user-images.githubusercontent.com/23658282/88592527-8c5cf300-d034-11ea-803a-9d85e9bf5050.png)
dotnet --info
SDK do .NET Core (refletindo qualquer global.json):
 Version:   3.1.301
 Commit:    7feb845744

Ambiente de runtime:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.301/

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  3.1.103 [/usr/share/dotnet/sdk]
  3.1.301 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

  Microsoft.NETCore.App 3.1.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
- I'm running the agent inside a docker container.
- tracer version 1.18.3
- OS:arch linux
Linux workstation 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64 GNU/Linux
- CLR: dotnet core 3.1.5

**Comment by macrogreg** [comment]
Hi @Johnsonxd4 ,

Thank you for your submission!
I would like to better understand your desired outcome:
* Are you trying to generally emit custom Spans and you specifically would like to use Open Tracing?
* Are you trying to get RabbitMQ related traces and you are trying to find a good way of doing it?
* Something else?

Thank you!

**Comment by Johnsonxd4** [comment]
Hi @macrogreg, Thank you for your reply!

* Yes, I'm trying to emit customs Spans and i would like to use the default interface for Opentracing, by just injecting the needed dependencies.
* I'm trying a good way of doing that, instead of creating a direct dependency of dd-trace-dotnet inside of my code, i would like to just inject the dependencies on startup, and use the [default interfaces](https://github.com/opentracing/opentracing-csharp) for opentracing.
Let me know if you need any further information.

**Comment by macrogreg** [comment]
Hi @Johnsonxd4 ,

I took a look and it seems that this is a re-incarnation of these: https://github.com/DataDog/dd-trace-dotnet/issues/797 ,  https://github.com/DataDog/dd-trace-dotnet/issues/724 . If so, I will close this issue for now with a reference to the details in these references. However, if you disagree to this analysis, please let me know.

Thanks!
