### ISSUE TITLE
Loading profiler failed. 

### ISSUE THREAD

**Issue by jinek** [DataDog/dd-trace-dotnet#824]
**Describe the bug**
Tracing does not work. The only message in Windows Events is:
```
.NET Runtime version 4.0.30319.0 - Loading profiler failed.  The profiler COM object was instantiated, but the profiler failed during its initialization callback.  Profiler CLSID: '{846F5F1C-F9AE-4B07-969E-05C26BC060D8}'.  HRESULT: 0x80004005.  Process ID (decimal): 19028.  Message ID: [0x2505].
```

No other errors are seen in events.

**Screenshots**
![image](https://user-images.githubusercontent.com/10516222/88666676-b10ea480-d0e0-11ea-89b8-93642fa8fb1e.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: Automatic
- Tracer version: 1.8.3
- OS: Windows 10
- CLR: .NET Framework 4.8

**Comment by lucaspimentel** [comment]
This event is generated automatically by the .NET CLR when a CLR profiler returns certain status codes from its `Initialize()` method. This means we decided not to do any instrumentation or "bailed out." This can happen for many reasons and not all of them are error conditions. For example, setting the environment variable `DD_TRACE_ENABLED=false` will make this message appear in the Windows Event Log. The profiler will log _why_ this happened into its log file, which by default is located in:
```
%ProgramData%\Datadog .NET Tracer\logs\dotnet-profiler.log
```

For additional assistance, please create a support ticket by emailing support@datadoghq.com and include the profiler log file indicated above.
