### ISSUE TITLE
 DD_APM_IGNORE_RESOURCES is not considering the reported values.

### ISSUE THREAD

**Issue by ralmsdeveloper** [DataDog/dd-trace-dotnet#896]
First sorry if this is not the best place!

But I'm having problems using DD_APM_IGNORE_RESOURCES I can't help it sending a flurry of things to the datadog.

I am leaving a small repo of my container below.

I would like the agent to disregard a particular route.
`/healthcheck`

I'm running ASPNET Core 3.1

```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app

COPY ./publish /app

RUN curl -LO https://github.com/DataDog/dd-trace-dotnet/releases/download/v1.19.1/datadog-dotnet-apm_1.19.1_amd64.deb \
&& dpkg -i ./datadog-dotnet-apm_1.19.1_amd64.deb 

ENV ASPNETCORE_ENVIRONMENT= ..OTHER_VARIABLES..
DD_APM_IGNORE_RESOURCES="GET healthcheck"
```

**Comment by lucaspimentel** [comment]
Hi, @ralmsdeveloper. TL;DR: If you are running the Agent in a different container than your .NET application, you should set `DD_APM_IGNORE_RESOURCES` in the Agent container, not in your app's container.

---

`DD_APM_IGNORE_RESOURCES` is an Agent setting, not a .NET Tracer setting. These are two separate components: the .NET Tracer (this repo) is the library that runs inside your application process. It collects traces and sends them to the Agent. The Agent ([different repo](https://github.com/DataDog/datadog-agent)) is a separate process that, among other things, processes the traces it receives from tracers and sends them to Datadog servers.

If you are setting `DD_APM_IGNORE_RESOURCES` in the right place, it's worth checking that the resource name is correct. A common mistake it to leave out the leading `/` when needed or adding it when it's not needed. Have you tried setting the value to `GET /healthcheck`?

Here are some docs that might help:
- Agent configuration: [Tracing Docker Applications - Docker APM Agent Environment Variables](https://docs.datadoghq.com/agent/docker/apm/?tab=linux#docker-apm-agent-environment-variables)
- .NET Tracer configuration: [Tracing .NET Framework Applications - Configuration](https://docs.datadoghq.com/tracing/setup/dotnet-framework/?tab=environmentvariables#configuration)

If you need help configuring your Agent or the .NET Trace, you can [contact our support team](https://www.datadoghq.com/support/).

**Comment by ralmsdeveloper** [comment]
@lucaspimentel 

> Have you tried setting the value to ?DD_APM_IGNORE_RESOURCES/GET /healthcheck

First thanks for the answer, i already tried all the ways, as the image is downloaded in a very specific way: datadog-dotnet-apm_1.19.1 I believed that you could help me with something!

Another detail even if I disable an application, it continues to trace.
`Tracer.Instance.Settings.DisabledIntegrationNames.Add("AspNetCore");`
