### ISSUE TITLE
Feature request: Support for the W3C Trace Context standard

### ISSUE THREAD

**Issue by tylerohlsen** [DataDog/dd-trace-dotnet#901]
Related to [this article](https://devblogs.microsoft.com/aspnet/improvements-in-net-core-3-0-for-troubleshooting-and-monitoring-distributed-apps/), I'd like this library to use the same [W3C Trace Context](https://www.w3.org/TR/trace-context/) standard for propagating the ScopeContext on downstream http client requests (via the headers defined in the standard).  

I think one way to do this would be to hook up ScopeContext to pull the TraceId (and other trace / span) values on the root scope from the [Activity.Current](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity) and defer to that library as well to generate child TraceId, SpanId, and other values.  This approach would inherently support custom scopes for other forms for downstream propagation using standard .NET libraries (using System.Diagnostics.Activity) instead of needing to reference a Datadog library.

**Comment by macrogreg** [comment]
Hi @tylerohlsen ,

We are currently working on support of Open Telemetry and .NET activities.
As a part of this of this effort we plan to also address W3C context compatibility.

For context, see:
https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/13
and
https://github.com/dotnet/runtime/issues/42786#issuecomment-700370497

Right now I cannot share an ETA, but stay tuned!

**Comment by macrogreg** [comment]
Internal tracker:
https://datadoghq.atlassian.net/browse/DOTNET-21

**Comment by julealgon** [comment]
@macrogreg do you have any updates on adding support for working with native `System.Diagnostics.Activity`? We would also like to leverage this so we can use standard constructs in our custom instrumentations and not need to reference and use Datadog classes directly in library code.

**Comment by ozziepeeps** [comment]
Would love an update on this @macrogreg if you have the time? I lot of us in the community would love to use the .NET `Activity` abstractions combined with DataDog. Thank you in advance.

**Comment by mrtristan** [comment]
@andrewlock maybe i need to open a new issue for this but maybe you can comment as it's pretty related. Is there a concept along these lines in the dotnet side?

https://github.com/DataDog/dd-trace-js/issues/1601

I believe this is a breaking change in that we're running the new tracer version and we're having downstream (external) http services that are blowing up due to the unexpected DD headers.

**Comment by lucaspimentel** [comment]
> there needs to be a way to exclude certain domains from that process

@mrtristan: Agreed! I will close this issue as the OP's request for W3C Trace Context support is not implemented. You can open a new feature request for excluding specified domains from downstream propagation headers.

> I believe this is a breaking change in that we're running the new tracer version and we're having downstream (external) http services that are blowing up due to the unexpected DD headers.

In your new feature request, can you include more details about this? We have always injected several http headers for trace propagation. Did you notice any recent change in those headers that would cause this issue? Thanks!

**Comment by mrtristan** [comment]
all good @lucaspimentel, thanks - covered in #3000 / #3001
