### ISSUE TITLE
FollowsFrom reference type isn't linking spans 

### ISSUE THREAD

**Issue by anilca** [DataDog/dd-trace-dotnet#908]
**Describe the bug**
We can't link spans with the FollowsFrom reference type.

**To Reproduce**

1. We have an OpenTracingSevice implementation like below:
```
    public class OpenTracingService : ITracingService
    {
        private readonly ITracer _tracer;
        private readonly ILogger _logger;

        private bool _isEnabled;

        public OpenTracingService(ITracer tracer, IConfiguration configuration, ILoggerFactory logger)
        {
            _tracer = tracer ?? throw new ArgumentNullException(_tracer.GetType().GetGenericTypeName());
            var isEnabled = configuration?.GetValue<bool>("OpenTracing.Enabled", true) ?? true;
            _isEnabled = isEnabled;
            _logger = logger.CreateLogger(nameof(OpenTracingService));
        }

        public void Disable()
        {
            _isEnabled = false;
        }

        public void Enable()
        {
            _isEnabled = true;
        }

        public void TraceConsumerEvent(string transformationName, TraceableEvent transformedEvent)
        {
            if (_isEnabled)
            {
                LinkAndTrace(transformationName, null, transformedEvent);
            }
        }

        public void LinkAndTrace(string transformationName, TraceableEvent originalEvent, TraceableEvent transformedEvent)
        {
            if (_isEnabled)
            {
                using var scope = TraceEvent(transformationName, originalEvent);

                if (transformedEvent != null)
                {
                    if (_tracer.ActiveSpan != null)
                    {
                        var dictionary = new Dictionary<string, string>();
                        _tracer.Inject(_tracer.ActiveSpan.Context, BuiltinFormats.TextMap, new TextMapInjectAdapter(dictionary));
                        transformedEvent.Tracing.Headers = dictionary;
                    }
                    using (LogContext.PushProperty("dd.trace_id", scope.Span.Context.TraceId))
                    using (LogContext.PushProperty("dd.span_id", scope.Span.Context.SpanId))
                    {
                        scope.Span.SetTag("manual.keep", "true"); // this line should be moved to additional tags after introducing them
                        scope.Span.SetTag("EventType", transformedEvent.GetType().Name);
                        scope.Span.SetTag("EventId", transformedEvent.Identifier);
                        var serializedObject = JsonConvert.SerializeObject(transformedEvent);
                        scope.Span.Log(serializedObject);
                        _logger.LogInformation($"message proccessed at {DateTime.Now} / object: {serializedObject}");
                    }
                }
            }
        }

        public void TraceProducerEvent(string transformationName, TraceableEvent originalEvent)
        {
            if (_isEnabled)
            {
                LinkAndTrace(transformationName, originalEvent, null);
            }
        }

        private IScope TraceEvent(string transformationName, TraceableEvent transformedEvent)
        {
            var textMapExtractAdapter = transformedEvent != null ? new TextMapExtractAdapter(transformedEvent.Tracing.Headers) : new TextMapExtractAdapter(new Dictionary<string, string>());
            var parentSpanCtx = _tracer.Extract(BuiltinFormats.TextMap, textMapExtractAdapter);
            var span = _tracer.BuildSpan(transformationName);
            if (parentSpanCtx != null)
            {
                span = span.AddReference(References.FollowsFrom, parentSpanCtx);
            }
            var scope = span.StartActive(true);
            return scope;
        }
    }
```

2. We are registering Datadog tracer as below:
```
        public static IServiceCollection ConfigureDatadogOpenTracing(this IServiceCollection services, IConfiguration configuration)
        {
            ITracer tracer = OpenTracingTracerFactory.WrapTracer(Datadog.Trace.Tracer.Instance);
            services.AddSingleton<ITracer>(serviceProvider =>
            {
                GlobalTracer.RegisterIfAbsent(tracer);
                return tracer;
            });
            services.AddOpenTracing();
            return services;
        }
```

3. When I run my application using the above setting, I see that there are no relations between my spans. They are not being linked to each other. I see all of my spans as individual spans in datadog dashboard.

4. If I update reference type with ChildOf without any other difference:
`span = span.AddReference(References.ChildOf, parentSpanCtx);`
Then I can see my spans are being linked to each other.

**Expected behavior**
I would like to use FollowsFrom reference type to link my spans since this is the desired relation type for my case.

**Screenshots**
Screenshot of span list tab with FollowsFrom:
![image](https://user-images.githubusercontent.com/2606446/92260604-7581aa00-eed8-11ea-8c40-92f37b5df2f1.png)

Screenshot of span list tab with ChildOf:
![image](https://user-images.githubusercontent.com/2606446/92261167-4b7cb780-eed9-11ea-86df-ce5f7a624a1e.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: manual with NuGet package
- Tracer version: 1.16.1
- OS: [e.g. Windows 10 Enterprise]
- CLR: .NET Core 3.1

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\dotnet-profiler.log
Linux: /var/log/datadog/dotnet/dotnet-profiler.log
--!>

**Comment by macrogreg** [comment]
Hi @anilca ,

Thanks for this submission. The fact that this is not currently supported by the API is related to the fact that the backend and the UI experience currently do not support reasoning over the follows-from relationship.

In addition to the above, please also note that the Open Tracing standards have been superseded by Open Telemetry. We will continue maintaining existing APIs and make critical bug and security fixes, but we will focus on Open Telemetry when adding new features.

With this in mind I will close this issue for now. If you have questions or you disagree, please feel free to re-open and comment.

Thank you!
