### ISSUE TITLE
Logging to spans are not working as expected

### ISSUE THREAD

**Issue by anilca** [DataDog/dd-trace-dotnet#909]
**Describe the bug**
We can't log data to our spans.

**To Reproduce**

1. We have an OpenTracingSevice implementation like below:
```
    public class OpenTracingService : ITracingService
    {
        private readonly ITracer _tracer;
        private readonly ILogger _logger;

        private bool _isEnabled;

        public OpenTracingService(ITracer tracer, IConfiguration configuration, ILoggerFactory logger)
        {
            _tracer = tracer ?? throw new ArgumentNullException(_tracer.GetType().GetGenericTypeName());
            var isEnabled = configuration?.GetValue<bool>("OpenTracing.Enabled", true) ?? true;
            _isEnabled = isEnabled;
            _logger = logger.CreateLogger(nameof(OpenTracingService));
        }

        public void Disable()
        {
            _isEnabled = false;
        }

        public void Enable()
        {
            _isEnabled = true;
        }

        public void TraceConsumerEvent(string transformationName, TraceableEvent transformedEvent)
        {
            if (_isEnabled)
            {
                LinkAndTrace(transformationName, null, transformedEvent);
            }
        }

        public void LinkAndTrace(string transformationName, TraceableEvent originalEvent, TraceableEvent transformedEvent)
        {
            if (_isEnabled)
            {
                using var scope = TraceEvent(transformationName, originalEvent);

                if (transformedEvent != null)
                {
                    if (_tracer.ActiveSpan != null)
                    {
                        var dictionary = new Dictionary<string, string>();
                        _tracer.Inject(_tracer.ActiveSpan.Context, BuiltinFormats.TextMap, new TextMapInjectAdapter(dictionary));
                        transformedEvent.Tracing.Headers = dictionary;
                    }
                    using (LogContext.PushProperty("dd.trace_id", scope.Span.Context.TraceId))
                    using (LogContext.PushProperty("dd.span_id", scope.Span.Context.SpanId))
                    {
                        scope.Span.SetTag("manual.keep", "true"); // this line should be moved to additional tags after introducing them
                        scope.Span.SetTag("EventType", transformedEvent.GetType().Name);
                        scope.Span.SetTag("EventId", transformedEvent.Identifier);
                        var serializedObject = JsonConvert.SerializeObject(transformedEvent);
                        **scope.Span.Log(serializedObject);**
                        _logger.LogInformation($"message proccessed at {DateTime.Now} / object: {serializedObject}");
                    }
                }
            }
        }

        public void TraceProducerEvent(string transformationName, TraceableEvent originalEvent)
        {
            if (_isEnabled)
            {
                LinkAndTrace(transformationName, originalEvent, null);
            }
        }

        private IScope TraceEvent(string transformationName, TraceableEvent transformedEvent)
        {
            var textMapExtractAdapter = transformedEvent != null ? new TextMapExtractAdapter(transformedEvent.Tracing.Headers) : new TextMapExtractAdapter(new Dictionary<string, string>());
            var parentSpanCtx = _tracer.Extract(BuiltinFormats.TextMap, textMapExtractAdapter);
            var span = _tracer.BuildSpan(transformationName);
            if (parentSpanCtx != null)
            {
                span = span.AddReference(References.FollowsFrom, parentSpanCtx);
            }
            var scope = span.StartActive(true);
            return scope;
        }
    }
```

2. We are registering Datadog tracer as below:
```
        public static IServiceCollection ConfigureDatadogOpenTracing(this IServiceCollection services, IConfiguration configuration)
        {
            ITracer tracer = OpenTracingTracerFactory.WrapTracer(Datadog.Trace.Tracer.Instance);
            services.AddSingleton<ITracer>(serviceProvider =>
            {
                GlobalTracer.RegisterIfAbsent(tracer);
                return tracer;
            });
            services.AddOpenTracing();
            return services;
        }
```

3. When I run my application using the above setting, I can't see the logs I am adding to my spans.

**Expected behavior**
I would like to observe the logs I attached to my spans.

**Screenshots**
Screenshot of span list tab with FollowsFrom:
![image](https://user-images.githubusercontent.com/2606446/92261802-64399d00-eeda-11ea-8d06-da3748af049a.png)

![image](https://user-images.githubusercontent.com/2606446/92261862-7f0c1180-eeda-11ea-9abf-820ec614d62a.png)

**Runtime environment (please complete the following information):**
- Instrumentation mode: manual with NuGet package
- Tracer version: 1.16.1
- OS: [e.g. Windows 10 Enterprise]
- CLR: .NET Core 3.1

<!--
NOTE: To contact our support team, see https://www.datadoghq.com/support/
When contacting support, please include the information requested above.
If possible, also include the tracer log files found (by default) in:
Windows: %ProgramData%\Datadog .NET Tracer\logs\dotnet-profiler.log
Linux: /var/log/datadog/dotnet/dotnet-profiler.log
--!>

**Comment by macrogreg** [comment]
Hi @anilca ,

Thanks for bringing this to our attention. The fact that this is not currently supported by the API is related to the fact that the backend and the UI experience currently do not support attaching logs to spans.

We do support span tags that you can use for sending some custom information. We also automatically tag logs with references to the current span and trace during which they were emitted. @jaycdave88 could you please add some doc links here?

In addition to the above, please also note that the Open Tracing standards have been superseded by Open Telemetry. We will continue maintaining existing APIs and make critical bug and security fixes, but we will focus on Open Telemetry when adding new features. Initially, we plan to support mixing custom and auto-instrumentation emitted using Open Telemetry, and/or .NET Activities (work in progress). 

Thank you!

**Comment by macrogreg** [comment]
Copying @jaycdave88 's response from the linked PR:

> Here are some of our documentation that details a bit more about how to connect .NET logs and traces together:
https://docs.datadoghq.com/tracing/connect_logs_and_traces/dotnet?tab=serilog

**Comment by macrogreg** [comment]
I will close this issue with a reference to the above information. Please feel free to re-open if new information becomes available.

Please also note some workaround details described here:
https://github.com/DataDog/dd-trace-dotnet/pull/983#issuecomment-709951418
