### ISSUE TITLE
API to pass custom IScopeManger to OpenTracingTracer

### ISSUE THREAD

**Issue by RustyChain** [DataDog/dd-trace-dotnet#948]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
- Framework or library name : [`Akka.net`]
- Library type: [Actor based, concurrent, distributed, and resilient message-driven application framework]

**Is your feature request related to a problem? Please describe.**
Akka.net has an actual extension for tracing that built top of the OpenTracing standard, however it uses a special IScopeManger to trace the messages inside of the Actor system, that IScopeManager is just wrapper top of the tracer's IScopeManager.
If the default IScopeManger used then the traces from Rest API and Actor System won't be corelated, it behaves as 2 different trace.
Unfortunately Datadog implementation has no exposed API where it is possible to pass a custom IScopeManager

**Describe the solution you'd like**
Expose the internal constructor of the [OpenTracingTracer](https://github.com/DataDog/dd-trace-dotnet/blob/ae4feac06f98009d12c9dfa325d66f88c820c919/src/Datadog.Trace.OpenTracing/OpenTracingTracer.cs#L20) in the 
[OpenTracingTracerFactory](https://github.com/DataDog/dd-trace-dotnet/blob/ae4feac06f98009d12c9dfa325d66f88c820c919/src/Datadog.Trace.OpenTracing/OpenTracingTracerFactory.cs#L10)
**Describe alternatives you've considered**

**Comment by macrogreg** [comment]
Hi @RustyChain 

Thank you for your submission. I have added your submission to our backlog for future prioritization.

Please note that we need to strike a balance between investments into OpenTracing API (which is, essentially, a legacy standard) and Open Telemetry APIs.

I will close this issue for now.
However, if you are an existing customer and you have a business scenario that is blocked by the lack of this feature, please reopen this issue and tag me directly. We will then start a customer support process to make sure you get the help you need quickly.

Thank you!
