### ISSUE TITLE
Proposal: Reorganize directories for simplicity and clarity

### ISSUE THREAD

**Issue by zacharycmontoya** [DataDog/dd-trace-dotnet#951]
## Main Goals
- Simplify root directory so the repository feels more accessible to first time readers or contributors.
  - There are 4 `sample*` directories and 2 `reproduction*` directories that should be more clearly identified as test projects
  - There are several build and test files cluttered in the root directory that could be placed in more specific subdirectories
- Change the convention of "customer-samples" to "samples". My assumption is that new developers would expect to look at samples as small code projects that use the provided SDK in some meaningful way, so this proposed change would align with that.
- Change the convention of "samples" to "test-applications". The "samples" in our repository really act as test applications to ensure our automatic instrumentation works as advertised. Renaming to "test-applications" is a little more clear about the intent, but I'm open to other suggestions on the name of this.
- Change the convention of "reproductions" to "regression". These test applications serve as small regression tests to make sure previous bugs do not reoccur. Renaming to regression might convey that idea more clearly.

#### Directory: `/`
| Subdirectory name | Purpose |
| --------------------- | --------- |
| blog                        | Articles and walkthroughs (i.e. not code) to describe how the .NET Tracer can be used in various scenarios |
| build                       | Contains artifacts, docker files, shell scripts, and code needed to run builds and CI |
| docs                        | High-level documents |
| samples                  | Previously named `customer-samples`, this contains .NET code that can be easily built against the `Datadog.Trace` NuGet package to demonstrate how it can be used for custom instrumentation |
| src                          | Contains all project files and source files for .NET code, profiler code, and MSI code |
| test                         | Contains all test projects (managed and native) and test applications |
| tools                       | Miscellaneous .NET projects that are not product code or directly related to generating build artifacts |

#### Directory: `/build`
| Subdirectory name | Purpose |
| --------------------- | --------- |
| artifacts                   | `createLogPath.sh`, Datadog png's, and `integrations.json` |
| docker                     | Directly moved from the `/docker` directory |
| tools                        | Contains `GeneratePackageVersions` and `PrepareRelease` that were previously in the `/tools` directory |

#### Directory: `/blog`
Contents unchanged

#### Directory: `/docs`
Contents unchanged

#### Directory: `/samples` (renamed from `/customer-samples`)
Contents unchanged

#### Directory: `/src`
| Subdirectory name    | Purpose |
| ----------------------- | --------- |
| WindowsInstaller  | Project that generates MSI. Directly moved from the `/deploy/Datadog.Trace.ClrProfiler.WindowsInstaller` directory |
| Datadog.Trace.ClrProfiler.Native/lib | CoreCLR headers needed to build CLR Profiler. Directly moved from the `/lib` directory |
| Remaining Datadog.Trace.* projects | **Unchanged** |

#### Directory: `/test`
| Subdirectory name    | Purpose |
| ----------------------- | --------- |
| benchmarks               | Contains all benchmark projects |
| Datadog.Trace.*Tests | **Unchanged** |
| test-applications       | All sample applications intended to test automatic instrumentation will be moved to this directory |

#### Directory: `/tools`
| Subdirectory name | Purpose |
| --------------------- | --------- |
| Datadog.Core.Tools | **Unchanged** |
| StartDistributedTrace | **Unchanged** |
| UpdateVendors  | **Unchanged** |

#### Directory: `/test/test-applications`
| Subdirectory name | Purpose |
| --------------------- | --------- |
| aspnet                     | Contents will be a combination of the original `/samples-aspnet` directory and the `/samples-iis` directory |
| integrations             | Directly moved from the `/samples` directory |
| integrations/dependency-libs | Directly moved from the `/sample-libs` directory |
| regression               | Directly moved from the `/reproductions` directory |
| regression/dependency-libs | Directly moved from the `/reproduction-dependencies` directory |

## Updates
- Originally the two subfolders `aspnet` and `iis` were proposed as subdirectories of `/test/Datadog.Trace.ClrProfiler.IntegrationTests/test-applications`. Instead, they'll be combined into the `aspnet` subdirectory
- Originally the `test-applications` directory was proposed to be a subdirectory of `/test/Datadog.Trace.ClrProfiler.IntegrationTests`. Instead, it will be a subdirectory of `test`
- Updated new directory name to `/src/WindowsInstaller` based on feedback
- Updated the proposal to reflect the directory move from `/lib` to `/src/Datadog.Trace.ClrProfiler.Native/lib`

**Comment by macrogreg** [comment]
I have a suggestion for the structure of the src directory (applies to test too). If we like it, we can apply this in the same or in a separate PR. The proposed approach would 
* be more similar to conventions
* help making public APIs explicit.

Example:

```
/src
    /Some.Assembly.Name.Without.The.Dll.Extension
        /DataDog.AutoInstrumentation.Or.Whatever.Namespace
            /internal
                InternalClassInThisNamespace.cs
                OtherInternalClassInThisNamespace.cs
            /public
                PublicClassInThisNamespace.cs
        /Some.Other.Namespace
            /internal
                ...
            /public
                ... 
        /Some.OtherNamespace.SubNamespane
            /internal
                ...
            /public
                ...
        Some.Assembly.Name.Without.The.Dll.Extension.csproj
        OtherBuildRelatedFile.xyz
        AssemblyInfo.cs
        ...
```

(Note, I am not proposing to change namespaces of classes. Just to change the file structure on disk.)

So:
* the name of the folder under `src` is the assembly name (without the "dll")
* directly under it we would have only build-related, configuration and resource files
* actual source code lives in folders names like the namespace
* each namespace folder is the full namespace. E.g. this:
   * `/Datadog.Trace.Integrations.Redis` for a particular integration
   * `/Datadog.Trace` for generic public APIs
   * `/Datadog.Trace.Util` some shared utility
etc..
Not this:
```
/Datadog
    /Trace
        /Integrations
            /Redis
        /Util
```
* within each namespace folder, there is a sub-folder "internal" and "public".

**Comment by pjanotti** [comment]
@macrogreg I like the idea above at first. I do worry about getting the paths too long since Windows doesn't make easy to workaround the old MAX_PATH. Anyway, a separate PR makes easier to review it as separately from the higher-level re-org.

**Comment by lucaspimentel** [comment]
Thanks, @zacharycmontoya! This is one of those things we've wanted to do for a long time, but the more files we added the harder it became. Happy to see some progress! Proposal looks good to me with a few comments about `/test/*`.

- I'm not sure I would move `benchmarks` inside `test`, but I don't feel strongly about it.
- Moving `test-applications` inside `Datadog.Trace.ClrProfiler.IntegrationTests` seems weird to me, since the latter already contains a project. We don't place project folders inside other projects folders anywhere else, and it would require excluding child folders when building the parent. Can we move it to `test/test-applications` instead so it's a sibling of `Datadog.Trace.ClrProfiler.IntegrationTests`?
- I think we can merge the `iis` and `aspnet` folders. What sets them apart from other test apps is that they cannot be SDK-style projects and they require a blank `Directory.Build.props`.

**Comment by zacharycmontoya** [comment]
> * I'm not sure I would move `benchmarks` inside `test`, but I don't feel strongly about it.
I could be swayed either way on this one, as moving it inside `test` helps remove clutter from the root while at the same time it's not really a functional test. I wonder if there are other opinions on this particular move.

> * Moving `test-applications` inside `Datadog.Trace.ClrProfiler.IntegrationTests` seems weird to me, since the latter already contains a project. We don't place project folders inside other projects folders anywhere else, and it would require excluding child folders when building the parent. Can we move it to `test/test-applications` instead so it's a sibling of `Datadog.Trace.ClrProfiler.IntegrationTests`?
Yes that sounds completely reasonable. The main goal is to move them out of the root. I think @pjanotti and I were going back and forth on where to put the `test-applications` folder. Placing it at `test/test-applications` is fine by me ✔️ 

> * I think we can merge the `iis` and `aspnet` folders. What sets them apart from other test apps is that they cannot be SDK-style projects and they require a blank `Directory.Build.props`.
Yes I agree. I'll make that modification in the proposal at the top.

**Comment by zacharycmontoya** [comment]
@macrogreg I think we should move discuss on your ideas into a separate PR. I think that's a good start to re-organizing the product code

**Comment by kevingosse** [comment]
> I could be swayed either way on this one, as moving it inside test helps remove clutter from the root while at the same time it's not really a functional test. I wonder if there are other opinions on this particular move.

I don't think it's worth having a dedicated folder at the root level. Then the only alternative is `tools`, which is just as questionable, if not more. So I'm good with `test`.

**Comment by tonyredondo** [comment]
With the update looks good to me

**Comment by zacharycmontoya** [comment]
I have a branch with all of the changes at https://github.com/DataDog/dd-trace-dotnet/tree/zach/directory-restructuring . Since this touches a lot of files, it might be easier for reviewers to review one subdirectory tree at a time. If that sounds good, I can begin preparing the 6 PR's separately:
1. build
1. samples
1. src/Datadog.Trace.ClrProfiler.Native/lib
1. src/Datadog.Trace.ClrProfiler.WindowsInstaller
1. test/benchmarks
1. test/test-applications

**Comment by zacharycmontoya** [comment]
I've decided to perform all changes in one #973 . It's currently in a draft format because I anticipate a couple of CI build/script issues from the changes, but I'll open it up as a regular PR once that is figured out. @pjanotti looks like you have peeked at this recently, but I wanted to let you know that this is making real progress 😄

**Comment by zacharycmontoya** [comment]
#973 has been merged! 🎉 Closing this issue.
